### ISSUE TITLE
scratcphads

### ISSUE THREAD

**Issue by kronikpillow** [bakkeby/dwm-flexipatch#100]
hey mate... is it possible to use non ST terminals in the dwm scratchpad patch or are we forced to use things like tdrop if we don't want to use St with dwm?

**Comment by bakkeby** [comment]
Of course you can. Scratchpads doesn't necessarily mean terminals - you can have a browser as a scratchpad, or a text editor, or a calculator, and so forth.

**Comment by kronikpillow** [comment]
I'v been digging my head around for days and days of how to achieve the same result with Alacritty

```
const char *spcmd1[] = {"st", "-n", "spterm", "-g", "120x34", NULL };

const char *spcmd2[] = {"st", "-n", "spcalc", "-f", "monospace:size=16", "-g", "50x20", "-e", "dropdowncalc", NULL };
```

i simply want to use the same commands, size, different terminal .. and unsuccessful ... i'v even tried kitty, it's driving me nuts

**Comment by bakkeby** [comment]
Have you compared the st and Alacritty man pages?

They are different terminals and don't have the same command line arguments.

**Comment by bakkeby** [comment]
As already outlined in https://www.reddit.com/r/suckless/comments/m5177c/probably_a_dumb_question_but_iv_been_struggling/ Alacritty is meant to be configured using a configuration file, but if you don't want to point to a separate configuration file then you can pass the `-o` flag to override specific options.

It is not pretty, but the exact same commands would probably look like this:
```c
const char *spcmd1[] = {"alacritty", "--class", "spterm", "-o", "window.dimensions.columns=50", "-o", "window.dimensions.lines=20", NULL };
const char *spcmd2[] = {"alacritty", "--class", "spcalc", "-o", "font.size=16", "-o", "font.normal.family=monospace", "-o", "window.dimensions.columns=50", "-o", "window.dimensions.lines=20", "-e", "dropdowncalc", NULL };
```

**Comment by kronikpillow** [comment]
eee man thanks for your assistance :) that's what i'v been struggling to figgure out ... i'v been placing spaces in between "window dimensions" similar stuff... I will try out now if these commands work :) do you have a Brave wallet? I wanna contribute some bat that I have stored to you for all the help you'v done to me

**Comment by kronikpillow** [comment]
buyaaaa it works! wooohoo :)) ... topic can be closed ... get verified with Brave so that I can contribute you my BAT please :))

**Comment by bakkeby** [comment]
No need for compensation, just glad it worked out for you :)
