### ISSUE TITLE
systray

### ISSUE THREAD

**Issue by plasmoduck** [bakkeby/dwm-flexipatch#102]
Hey dude, how can I make just 1 space between the statusbar and systray so its more consistant instead of having a big space like in the screenshot 
![area-210321-2108-47](https://user-images.githubusercontent.com/38978656/111901264-fea09e80-8a2e-11eb-911c-9728e2298674.png)

**Comment by bakkeby** [comment]
That is just because of `lrpad` being added added on the left and right of the status and on the left and right of the systray. Either reduce `lrpad` in itself or remove the references from patch/bar_systray.c.
