### ISSUE TITLE
Increase size of every side using floatpos

### ISSUE THREAD

**Issue by fitrh** [bakkeby/dwm-flexipatch#103]
Is it possible to increase the size of every side using `floatpos` patch ? i can increase to the right or down side using this :
```c
{ CTRL|ALT,          XK_l,             floatpos,       {.v = "-1S -1S  8w  0h" } }, // →
{ CTRL|ALT,          XK_j,             floatpos,       {.v = "-1S -1S  0w  8h" } }, // ↓
```
but i'm still confused about how to increase to the left and up

**Comment by bakkeby** [comment]
That is a good question.

Here you have that the left x position is sticky and the top y position is fixed (sticky), and you increase the width or height.

If you omit the position or use `-1C` then the center point of the client is fixed and the size is increased in both directions (e.g. 4 pixels to the left and 4 pixels to the right).
```c
{.v = "-1C -1C  8w  0h" } },
{.v = "-1C -1C  0w  8h" } },
```

To only increase the size to the left and up you want to make the right x and bottom y position of the client sticky, in which case you'd use `-1Z`.

```c
{.v = "-1Z -1Z  8w  0h" } },
{.v = "-1Z -1Z  0w  8h" } },
```

Trying this out, however, it didn't quite behave as one would expect. I'm committing a proposed fix for this.

**Comment by fitrh** [comment]
> 
> To only increase the size to the left and up you want to make the right x and bottom y position of the client sticky, in which case you'd use `-1Z`.
> 
> ```c
> {.v = "-1Z -1Z  8w  0h" } },
> {.v = "-1Z -1Z  0w  8h" } },
> ```
I've tried this idea before, and it's what confuses me, because the wiki says that `Z` does what `S` does, but for the opposite side.

**Comment by fitrh** [comment]
4751d73 seems to fix it
