### ISSUE TITLE
Incrgaps and pertag

### ISSUE THREAD

**Issue by explosion-mental** [bakkeby/dwm-flexipatch#106]
incrgaps and store it pertag, Is this possible? I know its not usefull but that's something thats annoying me lately.

**Comment by bakkeby** [comment]
Almost anything is possible.

Gaps are configured on a per monitor basis currently, but I can have a look at options to have gaps on a per tag basis.

**Comment by bakkeby** [comment]
Can you try the above out? I added a new option `PERTAG_VANITYGAPS_PATCH` that you need to set. I could have enabled this by default when you have both pertag and vanitygaps patches enabled, but chances are that some people would prefer not to have this behaviour so decided to make it configurable.

**Comment by explosion-mental** [comment]
IT WERKS!!
it doesn't set up the gaps at the start defined on config.h tho.
Here is my dwm.c (inside is vanitygaps, also pertagview = view for me)
struct pertag
https://github.com/explosion-mental/Dwm/blob/a7cdbaaff8b8183485d08a4a0cf6b2098da88bce/dwm.incrgaps.c#L384
setgaps
https://github.com/explosion-mental/Dwm/blob/a7cdbaaff8b8183485d08a4a0cf6b2098da88bce/dwm.incrgaps.c#L1747
view
https://github.com/explosion-mental/Dwm/blob/a7cdbaaff8b8183485d08a4a0cf6b2098da88bce/dwm.incrgaps.c#L2784
or just search PERTAG_VANITYGAPS

**Comment by bakkeby** [comment]
Thanks, and yes of course the gaps need to be set for each tag when the monitor is created. I totally forgot about that.

**Comment by explosion-mental** [comment]
That's all thanks! and good job you wizard :) closing this.
