### ISSUE TITLE
monocle layout & pertag don't respect gaps

### ISSUE THREAD

**Issue by kronikpillow** [bakkeby/dwm-flexipatch#11]
when I switch to monocle gaps are disabled ... can you make it in such a way to respect gaps so that we can have monocle window with gaps?

also, when i toggle on / off gaps, it toggles them on all tags regardelss of the pertag patch, it would be good to have the ability to have gaps on on 1 tag in 1 layout and gaps off in a different layout on a different tag ...
^^

**Comment by bakkeby** [comment]
Hi @kronikpillow,

> when I switch to monocle gaps are disabled ... can you make it in such a way to respect gaps so that we can have monocle window with gaps?

Yes I can look into making this an option.

> also, when i toggle on / off gaps, it toggles them on all tags regardless of the pertag patch, it would be good to have the ability to have gaps on on 1 tag in 1 layout and gaps off in a different layout on a different tag ...

Should be straightforward enough. Will look into it. Meanwhile you could just change the gaps to be 0 for that tag if need be.

I don't know when I'll find time to do this, but I'll let you know once I have something.

\
Thanks,

-Stein

**Comment by bakkeby** [comment]
Hi @kronikpillow,

I have pushed two changes now that aims to address both of the above. Enable the VANITYGAPS_MONOCLE_PATCH option for gaps on the monocle layout.

It should hopefully work out of the box. Let me know if there are any issues.

\
Thanks,

-Stein

**Comment by kronikpillow** [comment]
found some errors along the way regarding other patches, so I will test this out once I report all errors found :) going 1 by 1 patch now to find what is wrong and where :)

**Comment by kronikpillow** [comment]
works fine
