### ISSUE TITLE
[ Request ] Add XKB patch please

### ISSUE THREAD

**Issue by mrbooshehri** [bakkeby/dwm-flexipatch#111]
Please add this patch [XKB](https://dwm.suckless.org/patches/xkb/).
Thanks

**Comment by bakkeby** [comment]
Hi @mrbooshehri,

I added that patch on a separate branch [xkb](https://github.com/bakkeby/dwm-flexipatch/tree/xkb) for now.

Would it be possible for you to have a play around?

It seems to work fine, but you'll need to set config ref. https://www.x.org/archive/X11R7.5/doc/input/XKB-Config.html first.

I am not sure if the default layout of "en" is actually valid or not, maybe it should be "us".

**Comment by mrbooshehri** [comment]
Cool!
I'm going to test it.
@bakkeby thx

**Comment by mrbooshehri** [comment]
> Hi @mrbooshehri,
> 
> I added that patch on a separate branch [xkb](https://github.com/bakkeby/dwm-flexipatch/tree/xkb) for now.
> 
> Would it be possible for you to have a play around?
> 
> It seems to work fine, but you'll need to set config ref. https://www.x.org/archive/X11R7.5/doc/input/XKB-Config.html first.
> 
> I am not sure if the default layout of "en" is actually valid or not, maybe it should be "us".
> 
> 
> 

@bakkeby it's properly work.

**Comment by bakkeby** [comment]
Thanks @mrbooshehri, I have merged in these changes now.
