### ISSUE TITLE
Staticstatus patch missing

### ISSUE THREAD

**Issue by Snow-0** [bakkeby/dwm-flexipatch#113]
The changelog in the readme says that staticstatus was added in July of last year, but I don't see it in the patches.h.

**Comment by bakkeby** [comment]
It is not actually missing.

If you look further down at the patch listing you'll see that ~staticstatus~ is striked out and later in the changelog there's this line saying that it has been made redundant with [barmodules](https://github.com/bakkeby/patches/wiki/barmodules).
https://github.com/bakkeby/dwm-flexipatch/blob/bd5f5608a331b10746cde9c3ecbba24ae100f64d/README.md#L72

If you want that patch as-is then you'd need to have a look at [dwm-flexipatch-1.0](https://github.com/bakkeby/dwm-flexipatch/tree/dwm-flexipatch-1.0) instead.

If you want the status to be static in the current build then you need to adjust the barmodules config changing the `'A'` (show on the active monitor) to `0` (show on the first and normally the primary monitor) or `1` for an adjacent monitor, etc. You could also set this to `-1` if you wanted to have the status to show on all monitors as per the statusallmons patch.
https://github.com/bakkeby/dwm-flexipatch/blob/bd5f5608a331b10746cde9c3ecbba24ae100f64d/config.def.h#L484


This is similar to #101 regarding the statusallmons patch.
