### ISSUE TITLE
optional colors?

### ISSUE THREAD

**Issue by kronikpillow** [bakkeby/dwm-flexipatch#115]
can optional functionality of color schemes be restored please? :)

**Comment by bakkeby** [comment]
What do you mean? Can you give an example?

**Comment by kronikpillow** [comment]
`static char normfgcolor[]                = "#bbbbbb";
static char normbgcolor[]                = "#222222";
static char normbordercolor[]            = "#444444";
static char normfloatcolor[]             = "#db8fd9";

static char selfgcolor[]                 = "#eeeeee";
static char selbgcolor[]                 = "#005577";
static char selbordercolor[]             = "#005577";
static char selfloatcolor[]              = "#005577";

static char titlenormfgcolor[]           = "#bbbbbb";
static char titlenormbgcolor[]           = "#222222";
static char titlenormbordercolor[]       = "#444444";
static char titlenormfloatcolor[]        = "#db8fd9";

static char titleselfgcolor[]            = "#eeeeee";
static char titleselbgcolor[]            = "#005577";
static char titleselbordercolor[]        = "#005577";
static char titleselfloatcolor[]         = "#005577";

static char tagsnormfgcolor[]            = "#bbbbbb";
static char tagsnormbgcolor[]            = "#222222";
static char tagsnormbordercolor[]        = "#444444";
static char tagsnormfloatcolor[]         = "#db8fd9";

static char tagsselfgcolor[]             = "#eeeeee";
static char tagsselbgcolor[]             = "#005577";
static char tagsselbordercolor[]         = "#005577";
static char tagsselfloatcolor[]          = "#005577";

static char hidfgcolor[]                 = "#005577";
static char hidbgcolor[]                 = "#222222";
static char hidbordercolor[]             = "#005577";
static char hidfloatcolor[]              = "#f76e0c";

static char urgfgcolor[]                 = "#bbbbbb";
static char urgbgcolor[]                 = "#222222";
static char urgbordercolor[]             = "#ff0000";
static char urgfloatcolor[]              = "#db8fd9";
`

what im saying is theming dwm like this is a major pita, especially if you have no interest in actually using separate coloring for example for urgent or tags etc ...

**Comment by bakkeby** [comment]
But it is a config file, you can configure it just how you like it.

You can delete those variables as long as you don't rely on the xrdb patch.

If you wanted everything to be the same you could do this for example:
```c
static char *colors[][ColCount] = {
	/*                       fg                bg                border                float */
	[SchemeNorm]         = { samefgcolor,      samebgcolor,      samebordercolor,      samefloatcolor },
	[SchemeSel]          = { samefgcolor,      samebgcolor,      samebordercolor,      samefloatcolor },
	[SchemeTitleNorm]    = { samefgcolor,      samebgcolor,      samebordercolor,      samefloatcolor },
	[SchemeTitleSel]     = { samefgcolor,      samebgcolor,      samebordercolor,      samefloatcolor },
	[SchemeTagsNorm]     = { samefgcolor,      samebgcolor,      samebordercolor,      samefloatcolor },
	[SchemeTagsSel]      = { samefgcolor,      samebgcolor,      samebordercolor,      samefloatcolor },
	[SchemeHid]          = { samefgcolor,      samebgcolor,      samebordercolor,      samefloatcolor },
	[SchemeUrg]          = { samefgcolor,      samebgcolor,      samebordercolor,      samefloatcolor },
}
```

or define the colors directly:
```c
static char *colors[][ColCount] = {
	/*                       fg          bg          border      float */
	[SchemeNorm]         = { "#FF0000",  "#00FF00",  "#0000FF",  "#FF00FF" },
	[SchemeSel]          = { "#FF0000",  "#00FF00",  "#0000FF",  "#FF00FF" },
	[SchemeTitleNorm]    = { "#FF0000",  "#00FF00",  "#0000FF",  "#FF00FF" },
	[SchemeTitleSel]     = { "#FF0000",  "#00FF00",  "#0000FF",  "#FF00FF" },
	[SchemeTagsNorm]     = { "#FF0000",  "#00FF00",  "#0000FF",  "#FF00FF" },
	[SchemeTagsSel]      = { "#FF0000",  "#00FF00",  "#0000FF",  "#FF00FF" },
	[SchemeHid]          = { "#FF0000",  "#00FF00",  "#0000FF",  "#FF00FF" },
	[SchemeUrg]          = { "#FF0000",  "#00FF00",  "#0000FF",  "#FF00FF" },
}
```

If I were to make things optional then that would just complicate things further and be even more of a pita to configure.

**Comment by kronikpillow** [comment]
thx :)

**Comment by bakkeby** [comment]
![image](https://user-images.githubusercontent.com/1438008/115545206-d3b2a000-a2a3-11eb-9db1-82a9f41b8039.png)

Really awesome color scheme I just proposed to you, lol.

**Comment by kronikpillow** [comment]
LOL ... Nord all the way, I did a great Nord Nordic / blue color scheme for DWM, but only the base colors, these additional titles and stuff completely messed up my scheme :-/ now i need to rework it from scratch and frankly i can't seem to figure out what some things are, hence i was looking for a solution to dump what i don't really need, like the urgent and floating colors ... i just want them to use what they use without that patch (which i have no clue what the default behavior is)

**Comment by nullndvoid** [comment]
Can I get away with SchemeNorm and SchemeSel?

**Comment by nullndvoid** [comment]
> Can I get away with SchemeNorm and SchemeSel?

I just did a little find and replace job in my case so I don't have to work out what each color corresponded to.

Also this issue should probably be closed.

**Comment by nullndvoid** [comment]
![image](https://user-images.githubusercontent.com/99098380/163685852-4931eb8c-2f7d-4d37-8d1e-d08786340881.png)

Maybe it's how my VSCode is setup (taking preprocessor values into account?) but do the extra color schemes in the enum do anything?

**Comment by bakkeby** [comment]
> do the extra color schemes in the enum do anything?

Technically the colour schemes only define a set of colours (foreground, background border and float border colour) - they don't do anything as such. How and where the colour schemes are used is another matter and you can usually find this using a simple grep.

> Can I get away with SchemeNorm and SchemeSel?

An unpatched / bare dwm uses only SchemeNorm and SchemeSel, so you can definitely get away with that.

There are a myriad of patches adding different colours for this and that, like the [urgentborder](https://dwm.suckless.org/patches/urgentborder/) patch adding a different colour for clients that have the urgency bit set.

I used to have the extra colour schemes being enabled only when their respective patches were enabled, e.g.

https://github.com/bakkeby/dwm-flexipatch/blob/9c2283dec94d27b4812262b73c308e48201da41f/config.def.h#L152-L278

but it was borderline unmanageable and confusing to say the least for users, so after some refactoring / simplification I ended up having the extra colour schemes by default. They allow you to differentiate the colours between window titles, the tags, hidden windows and urgent windows. You can have them all refer to the same colours should you want that of course.
