### ISSUE TITLE
layouts bug

### ISSUE THREAD

**Issue by kronikpillow** [bakkeby/dwm-flexipatch#12]
there seems to be a bug when I enable the cfacts patch, after opening many windows in the stack, the bottom border of the last window in the stack is like moving around, and it's creating a gap between it and the edge of the screen ... this doesn't happen without the dwmc patch, had to backward patch my build to figure out where the bug came from :)

[link to video](https://youtu.be/WcsvweWwpI0)

**Comment by bakkeby** [comment]
Not entirely sure that this has anything to do with the cfacts patch in itself. It depends on the amount of pixels available on the monitor to draw these boxes and the number of clients it needs to divide this by.

For some combinations you won't be able to divide the available space evenly, so if you have two clients in the stack area and the available space is 821 pixels, then you'd end up with 410 pixels per client (not taking the border into account) and you'd have 1 pixel too many. At worst you'd end up with n - 1 lost pixels, which means that if you have 17 clients then that could potentially be 16 pixels which becomes a lot more noticeable (and you have this jumping effect as you have observed).

If you take a bare dwm 6.2 build then you'll see this behaviour as well, except that the last client will simply be larger than the others.

I guess comes down to a personal preference thing whether one favours evenly sized clients or a filled pane. I suspect that it's always going to look just a tad off no matter how you do it, but I guess it is something to keep in mind when building your own dwm.

In the end you won't ever be using that many clients in practice - even if you were to have a lot of screen real estate.

\
Thanks,

-Stein

**Comment by kronikpillow** [comment]
pure dwm-flexipatch with only facts patch contains this bug, it doesn't happen when dwmc is disabled

**Comment by bakkeby** [comment]
I don't think that it would have anything to do with the dwmc patch - that one doesn't have anything to do with how the layouts are arranged.

I found an alternative solution which would be to work out how many pixels are left over after the clients have been divided evenly in the available space, then distribute these extra pixels among the first n clients. I'll let you know once I have something ready, just note that it will take a bit of time as it will affect the majority of layouts.

**Comment by kronikpillow** [comment]
yes possible that it has nothing to do with the dwmc patch, but it's hard to figure out which one triggers it, maybe if we go trough my patch history / enable / disable each patch one by one till we find the one that is causing this, but again that's such a pain :D

**Comment by bakkeby** [comment]
No worries, this is a bit of an issue that applies to the majority of my layouts.

**Comment by kronikpillow** [comment]
further analasis shows me that this bug applies once i enable vanitygaps patch

**Comment by kronikpillow** [comment]
I just tested your vanitygaps-6.2.diff on pure dwm, the bug seems to be in your layouts, you are correct ... I have tested your vanitygaps patch that is on the suckless website as well, it's not present there

**Comment by bakkeby** [comment]
Hi @kronikpillow,

Yes so if you have 900 pixels, and you need to divide this by, say, 7 clients in the stack area, then the way I did it was that I split this number by 7 to determine the size of each client window, then place them. The side effect of this is that an even split gives a height of 128, and 128*7 is 896 - so we are losing 4 pixels.

You may not notice this on the bare dwm tile layout that much as it calculates the size of the next client dynamically, and the last client simply gets the remaining space. In this scenario the last client would have a height of 132 and you can sometimes notice that the last client is simply larger than the rest. This is also the case with my old vanitygaps patch on the suckless website.

I have taken a different approach to this by calculating the remaining pixels (4 in this scenario), and re-distribute these among the first n clients - i.e. the first four clients in the stack area would have a height of 129 pixels while the rest have 128. This gives a more consistent split I find.

This change affects the following layouts:
- tile
- bstack
- bstackhoriz
- centered master
- centered floating master
- columns
- deck
- flextile-deluxe

I have checked these with and without both cfacts and vanitygaps patches and cases where nmaster is 0 or all clients are in the master area and as far as I can tell these should all be pixel perfect now. They won't win any awards for minimum number of code lines though :D

All in all this feels a lot more solid for me, but let me know if you find any discrepancies.

Other layouts that will also have such inconsistencies will be the fibonacci ones and all the grid layouts. Perhaps I will revisit these at some point in the future, but not today.

\
Thanks,

-Stein

**Comment by kronikpillow** [comment]
meeh mate :) tbh the minimum # of code lines is, in my opinion, exaggerating, functionality is what matters

**Comment by kronikpillow** [comment]
your latets commit completly broke dmw, this is with just the centered floating master patch enabled

```
❯ make
dwm build options:
CFLAGS   = -std=c99 -pedantic -Wall -Wno-deprecated-declarations -Os -I/usr/X11R6/include -I/usr/include/freetype2 -D_DEFAULT_SOURCE -D_BSD_SOURCE -D_POSIX_C_SOURCE=2 -DVERSION="6.2" -DXINERAMA
LDFLAGS  = -L/usr/X11R6/lib -lX11 -lXinerama -lfontconfig -lXft -lXrender
CC       = cc
cc -c -std=c99 -pedantic -Wall -Wno-deprecated-declarations -Os -I/usr/X11R6/include -I/usr/include/freetype2 -D_DEFAULT_SOURCE -D_BSD_SOURCE -D_POSIX_C_SOURCE=2 -DVERSION=\"6.2\" -DXINERAMA dwm.c
In file included from patch/include.c:6,
                 from dwm.c:288:
patch/centeredfloatingmaster.c: In function ‘centeredfloatingmaster’:
patch/centeredfloatingmaster.c:53:29: error: ‘Client’ {aka ‘struct Client’} has no member named ‘cfact’
   53 |    resize(c, sx, sy, sw * (c->cfact / sfacts) + ((i - m->nmaster) < srest ? 1 : 0) - (2*c->bw), sh - (2*c->bw), 0);
      |                             ^~
make: *** [Makefile:18: dwm.o] Error 1
```

**Comment by bakkeby** [comment]
Woops, thanks for finding. I've fixed this now.

**Comment by kronikpillow** [comment]
still gets a broken window :D eg it doesnt work

**Comment by bakkeby** [comment]
What layout do you have issues with?

**Comment by kronikpillow** [comment]
https://github.com/bakkeby/dwm-flexipatch/issues/18

**Comment by kronikpillow** [comment]
layouts seem to be good now :)
