### ISSUE TITLE
When I change tag names to my glyphs, dwm dies.

### ISSUE THREAD

**Issue by der-zonk** [bakkeby/dwm-flexipatch#123]
So I used the finalizer because I got all in that I want and tried to change the tag names to the glyphs I use.
Works great on my own built:
![Wed 05-05-2021 06:23:35](https://user-images.githubusercontent.com/80225209/117096981-d06ee800-ad6a-11eb-97f8-268c641780fd.png)
The finalized build is here:
https://github.com/der-zonk/dwm
If I add my glyphs and reload, dwm dies. It is definitely this, because when I pull this exact build it works np but as soon as I add my glyphs, it's over.
All I changed is this:
```
static char *tagicons[][NUMTAGS] = {
	[DEFAULT_TAGS]        = { "1", "2", "3", "4", "5", "6", "7", "8", "9" },
	[ALTERNATIVE_TAGS]    = { "A", "B", "C", "D", "E", "F", "G", "H", "I" },
	[ALT_TAGS_DECORATION] = { "<1>", "<2>", "<3>", "<4>", "<5>", "<6>", "<7>", "<8>", "<9>" },
};
```
to this:
```
static char *tagicons[][NUMTAGS] = {
	[DEFAULT_TAGS]        = { "", "", "", "", "", "" },
	[ALTERNATIVE_TAGS]    = { "A", "B", "C", "D", "E", "F" },
	[ALT_TAGS_DECORATION] = { "<1>", "<2>", "<3>", "<4>", "<5>", "<6>" },
};
```
it runs fine with numbers.
it runs fine with all polybars enabled except the tag polybar.
it dies with glyphs.
I haven't tried it on the pre-finalized build yet as I would have to apply all patches again.. But maybe this is sufficient info?

**Comment by bakkeby** [comment]
This doesn't actually have anything to do with the glyphs themselves, but that you are only defining icons for the first 6 tags and leaving the remaining three as empty (null).

If you change `NUMTAGS` in dwm.c from 9 to 6 then that should resolve the issue for you.

The reason dwm was crashing is because in your case you are using dwm with an external bar and the tags are retrieved via the IPC patch - and the IPC patch did not like providing JSON output for a null value. I added a safeguard to not include such tags in the dwm-msg output, optionally an empty string could have been returned instead.

**Comment by der-zonk** [comment]
So what exactly does "do not dump" here mean? That it just won't show anything if it doesn't have the same value as NUMTAGS or it ignores it and shows what's there? If my dump questions at any point start to bother you tell me. xD

**Comment by bakkeby** [comment]
The function is called "dump_tag" in the context of c. The "do not dump" means do not dump the tag name if it is null and "dump" in this context can be read as "spit out" or "output".

All the code change does is to avoid printing the tag name when using `dwm-msg` and the tag name is null.

If you have NUMTAGS as 9 and you put 6 values then the memory is still allocated and you would end up with:

```c
{ "1", "2", "3", "4", "5", "6", 0, 0, 0 }
{ "A", "B", "C", "D", "E", "F", 0, 0, 0 },
{ "<1>", "<2>", "<3>", "<4>", "<5>", "<6>", 0, 0, 0 },
```

> What if I have NUMTAGS 6 and put 7 tags in config? there woueldn't be null then?

That is a different issue.

You have an array of arrays, or a list of lists if you will. When data is stored like this then memory needs to be allocated to store all of it. For C to be able to know when the inner lists start the size of the inner lists need to be specified. The memory would also be stored / read sequentially, as in one array or "list" would be tacked onto the other.

So if you were to have NUMTAGS as 6 and you put 7 values, then the 7th value would actually end up being the first value of the second list. It wouldn't crash or anything like that, but what is displayed would not be what you'd expect.

```c
{ "1", "2", "3", "4", "5", "6" }
{ "7", "A", "B", "C", "D", "E" }
{ "F", "G", "<1>", "<2>", "<3>", "<4>" },
{ "<5>", "<6>", "<7>", 0, 0, 0 },
```

At least that's my recollection of it, this explanation may not be entirely correct.

**Comment by der-zonk** [comment]
Holy shit man I don't even understand half of this xD
Thanks for the help! It's good to know I can get back to this issue and read it.
