### ISSUE TITLE
Support for another scratchpad patch?

### ISSUE THREAD

**Issue by GasparVardanyan** [bakkeby/dwm-flexipatch#124]
https://github.com/GasparVardanyan/dwm-scratchpad

**Comment by bakkeby** [comment]
It's there actually:
https://github.com/bakkeby/dwm-flexipatch/blob/579f8f892b45b89355f48563c854bffd6b29a1d8/patches.def.h#L861-L865

**Comment by GasparVardanyan** [comment]
Ok, thanks ))

**Comment by GasparVardanyan** [comment]
But you use an older version of that patch.

**Comment by bakkeby** [comment]
I did add that a long time ago indeed, I can look into upgrading it.

As for SCRATCHPAD_MASK you could also have just used 0 (as in no tags).

**Comment by GasparVardanyan** [comment]
Yes ))
