### ISSUE TITLE
steam login window doesn't obey floating.

### ISSUE THREAD

**Issue by der-zonk** [bakkeby/dwm-flexipatch#127]
So in my old build I used to use
```
	/* class   instance    title       tags mask      iscentered        isfloating       isfakefullscreen         monitor */
	{ "Steam" ,NULL,       NULL,       1 << 5,        0, 	            0,               0,                       -1 },
	{ NULL,    NULL,       "Steam",    1 << 5,        0, 	            0,               0,                       -1 },
```
to tell the little fuckwindow that comes up on any tag you're on, when starting steam, to open on a specific tag. dwm did not need any additional patches for it to have the window floating.
"class" is all steam stuff and "title" is used for the little window.
Now on flexipatch it's fullscreen and when I try to do something like
`	RULE(.class = NULL, .instance = NULL, .title = "Steam", .tags = 1 << 5, .isfloating = 1)`
with the other option for rules all steam windows are floating.
I checked your setup before asking here but it seems like you're doing something individual. the steam_app__ thing did nothing for me. Any idea? It works on my old build where I have nothing related to rules applied. steam patch is on both builds tho.
It's not a big issue but an annoyance nonetheless..

edit: I figured this is pretty dumb.. I could probably have used class and title in one line as it probably adds up..
So the issue isnt the settings but that I don't know why flexipatch does not make it floating whereas the default dwm with basically same patches makes the window float.

**Comment by bakkeby** [comment]
Can check tomorrow, but I have these two:
```c
.class = "Steam"
.class = "steam_app_"
```

What's the "little fuckwindow", a new steam feature?

Note that certain window types are floating by default:
https://github.com/bakkeby/dwm-flexipatch/blob/23c76d13b5376e78c268006da57d132883d5df9b/config.def.h#L407-L410

In a bare dwm it was only dialog windows that were floating by default.

**Comment by der-zonk** [comment]
![scrr](https://user-images.githubusercontent.com/80225209/117187340-1a43e680-addc-11eb-9458-05fb259574c0.png)
This window should be very tiny.. but it's fullscreen.
xprop gives:
```
_IS_FLOATING(CARDINAL) = 0
WM_STATE(WM_STATE):
		window state: Normal
		icon window: 0x0
WM_NAME(UTF8_STRING) = "Steam"
WM_PROTOCOLS(ATOM): protocols  WM_DELETE_WINDOW
WM_HINTS(WM_HINTS):
		Client accepts input or input focus: True
_NET_WM_ICON(CARDINAL) = 	Icon (48 x 48):
"icon here"
_MOTIF_WM_HINTS(_MOTIF_WM_HINTS) = 0x2, 0x0, 0x0, 0x0, 0x0
WM_CLASS(STRING) = "Steam", "Steam"
WM_NORMAL_HINTS(WM_SIZE_HINTS):
		user specified location: 24, 78
		user specified size: 1367 by 1338
		program specified minimum size: 1367 by 1338
		program specified maximum size: 1367 by 1338
```

**Comment by bakkeby** [comment]
Yes so you'll want it to look like this:
![image](https://user-images.githubusercontent.com/1438008/117257514-4303c480-ae4c-11eb-9175-ebed710946ce.png)

You can achieve this with a rule like this:
```c
RULE(.class = "Steam", .isfloating = 1)
```
This of course also makes the Steam client window floating as well. I don't see anything that allows you to differentiate between the "logging in" window (or "checking for updates" window) and the Steam client.

**Comment by der-zonk** [comment]
Again, it works on my old dwm build, so basically stock dwm. I just checked again right now and it works there.

**Comment by der-zonk** [comment]
![1](https://user-images.githubusercontent.com/80225209/117265511-99750100-ae54-11eb-98b8-be46bb4bc7da.png)
![2](https://user-images.githubusercontent.com/80225209/117265545-a09c0f00-ae54-11eb-8a01-6d0ea907890a.png)

**Comment by bakkeby** [comment]
So it works in a bare dwm and it also works in a bare dwm-flexipatch, but not in your setup.

In a bare dwm the window is floating because it is fixed, and it is fixed based on the client's resize hints.

In your build you have enabled the floatpos which avoids updating the resize hints as it interferes to some degree when you try to have fine control over the size and position of floating windows.

https://github.com/bakkeby/dwm-flexipatch/blob/9edce6b60686450a875f59a700df84aac377dbf6/dwm.c#L2361-L2363

You can remove the if and endif there and it should make the "Connecting Steam account" window floating. I'll see if there are better ways to work around this.

**Comment by der-zonk** [comment]
Oh okay.. Well I didn't know this would interfere.. and I don't really need this patch, I just added almost everything on the list just to have it in xD
Guess I need to go back to the drawing board. Thanks!
