### ISSUE TITLE
fakefullscreen missing definitions in default configs 

### ISSUE THREAD

**Issue by kronikpillow** [bakkeby/dwm-flexipatch#13]
IF FAKEFULLSCREEN definitions not set in the default config, the patch doesn't apply

there is only 	#if FAKEFULLSCREEN_CLIENT_PATCH

also the FAKEFULLSCREEN.c gets deleted when running flexipatch finalized, and I assume that the patch doesn't apply since everything goes missing

**Comment by bakkeby** [comment]
Hi @kronikpillow,

not entirely sure which configs you are referring to.

There are two patches, FAKEFULLSCREEN_PATCH and FAKEFULLSCREEN_CLIENT_PATCH, one works globally and the other on a per-client basis. These are ref. [fakefullscreen](https://dwm.suckless.org/patches/fakefullscreen/) and #1 respectively.

The first one is enabled here:
https://github.com/bakkeby/dwm-flexipatch/blob/master/patches.def.h#L177

and the other one is enabled 7 lines below that. Perhaps you are using an old patches.h file?

There is no fakefullscreen.c file as it's all embedded in dwm.c and the entire patch is just about deleting code.

The default patches.def.h file is copied to patches.h if it does not already exist, the same as config.def.h > config.h (differentiating between default and personal configuration).

\
Thanks,

-Stein

**Comment by kronikpillow** [comment]
the #if FAKEFULLSCREEN_CLIENT_PATCH exits in config.def.h but when not the #if FAKEFULLSCREEN_PATCH ... eg when you apply the patch and run flexipatch finalized it doesn't have a keybinding in the config

**Comment by bakkeby** [comment]
Hi @kronikpillow,

sorry, I still don't quite understand what you are on about.

If I check out a clean dwm-flexipatch build, run `make` in order for a patches.h file to be created, then I change / enable
```
#define FAKEFULLSCREEN_CLIENT_PATCH 1
```

and run the flexipatch-finalizer on it, then the keybinding for `togglefakefullscreen` remains in the config.

Now, if I check out a clean dwm-flexipatch build, run `make` in order for a patches.h file to be created, then I change / enable
```
#define FAKEFULLSCREEN_PATCH 1
```

and run the flexipatch-finalizer on it, then the keybinding for `togglefakefullscreen` is removed from the config. This is as expected as the fakefullscreen patch affects all clients globally.

That said, if you enable *both* FAKEFULLSCREEN_PATCH and FAKEFULLSCREEN_CLIENT_PATCH, then the keybinding remains, but will have no effect as the global fakefullscreen patch takes precedence. I guess I could make changes to ensure that the client patch is fully removed when the global one is enabled.

Am I misunderstanding something with regards to what you are trying to achieve?

\
Thanks,

-Stein

**Comment by kronikpillow** [comment]
so wait, the FAKEFULLSCREEN patch doesn't need to be toggled? am I understanding it correctly? it is "toggled on by default" and can't be toggled off?

**Comment by bakkeby** [comment]
As mentioned earlier they are two different, mutually exclusive, patches.

By default dwm offers proper fullscreen.

If you enable FAKEFULLSCREEN_PATCH then that removes the proper fullscreen functionality (by deleting a bunch of code), with the aim that when a client window goes into fullscreen (e.g. you hit F11 in your browser) then that is limited to the area that it is given (i.e. the size of the tile).

If you enable FAKEFULLSCREEN_CLIENT_PATCH then that keeps the proper fullscreen, and allows you to enable / toggle fake fullscreen on a per-client basis. This way you could say that your media player should only play fullscreen within the one tile, but you can still go proper fullscreen with other windows.

If you enable both then I think there is room for confusion as some code of the latter remains. I have made some changes to make it a bit more clear that the former takes precedence over the latter.

\
Thanks,

-Stein

**Comment by kronikpillow** [comment]
I didn't enable both, I just enabled 1, then disabled it, and enabled the other one, but now I understand thanks for explaining
