### ISSUE TITLE
Make error

### ISSUE THREAD

**Issue by Sous-98** [bakkeby/dwm-flexipatch#140]
Currently having an issue while trying to run a make install. 

`rm -f dwm drw.o dwm.o util.o dwm-6.2.tar.gz
rm -f dwm-msg
dwm build options:
CFLAGS   = -std=c99 -pedantic -Wall -Wno-deprecated-declarations -Os -I/usr/X11R6/include -I/usr/include/freetype2   -D_DEFAULT_SOURCE -D_BSD_SOURCE -D_POSIX_C_SOURCE=200809L -DVERSION="6.2" -DXINERAMA
LDFLAGS  = -L/usr/X11R6/lib -lX11 -lXinerama -lfontconfig -lXft
CC       = cc
cc -c -std=c99 -pedantic -Wall -Wno-deprecated-declarations -Os -I/usr/X11R6/include -I/usr/include/freetype2   -D_DEFAULT_SOURCE -D_BSD_SOURCE -D_POSIX_C_SOURCE=200809L -DVERSION=\"6.2\" -DXINERAMA drw.c
cc -c -std=c99 -pedantic -Wall -Wno-deprecated-declarations -Os -I/usr/X11R6/include -I/usr/include/freetype2   -D_DEFAULT_SOURCE -D_BSD_SOURCE -D_POSIX_C_SOURCE=200809L -DVERSION=\"6.2\" -DXINERAMA dwm.c
In file included from patch/include.c:36,
                 from dwm.c:788:
patch/bar_status.c:30:1: warning: ‘click_status’ defined but not used [-Wunused-function]
   30 | click_status(Bar *bar, Arg *arg, BarArg *a)
      | ^~~~~~~~~~~~
cc -c -std=c99 -pedantic -Wall -Wno-deprecated-declarations -Os -I/usr/X11R6/include -I/usr/include/freetype2   -D_DEFAULT_SOURCE -D_BSD_SOURCE -D_POSIX_C_SOURCE=200809L -DVERSION=\"6.2\" -DXINERAMA util.c
cc -o dwm drw.o dwm.o util.o -L/usr/X11R6/lib -lX11 -lXinerama -lfontconfig -lXft
/usr/bin/ld: dwm.o: undefined reference to symbol 'XRenderFindVisualFormat'
/usr/bin/ld: /usr/lib/libXrender.so.1: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make: *** [Makefile:35: dwm] Error 1`

Would appreciate any assistance. Thanks!

**Comment by bakkeby** [comment]
Incidentally I created #140 yesterday on the [Known Issue](https://github.com/bakkeby/dwm-flexipatch/discussions/categories/known-issues) discussion category.

**Comment by Sous-98** [comment]
Thank you! This fixed my problem I can't believe I didn't think to check the config first. Appreciate your assistance.
