### ISSUE TITLE
fakefullscreen_client + centered floating master

### ISSUE THREAD

**Issue by kronikpillow** [bakkeby/dwm-flexipatch#15]
when using the centered floating master, and toggling the fakefullscreen_client patch, about 10-15% of the fullscreen window gets cut off from the actual window size, refreshing the window (for example Brave Browser) doesn't rescale it to the new centered floating master size, only way I was able to get it to rescale the window to fit it all in fake full screen was to switch to tile layout then back to centered floating master with the fakefullscreen_client toggled ... if your unable to replicate what I'm talking about or don't understand ill record a new video :)

**Comment by bakkeby** [comment]
Likely this has something to do with the client itself and how it handles fullscreen internally, some applications assumes that it has the whole monitor size at it's disposal when going fullscreen, rather than the strict window size.

You might want to double check with other applications. I can have a look, but I'll probably need to install Brave Browser as I wasn't able to replicate this on my setup.

**Comment by kronikpillow** [comment]
I'll record a video, to show you, Brave is chromium based so it should be the same with every chromium based browser

**Comment by bakkeby** [comment]
I have seen the behaviour you are referring to. So if I set the fake fullscreen for the browser client using a keybinding such as MOD+shift+f, then nothing really happens as the browser apparently does not react to the NetWMFullscreen signal.

If I then hit the F11 key, which is the keyboard shortcut for the browser to go into it's bespoke fullscreen mode, then that seemingly assumes that it has the entire height and width of the monitor at it's disposal. As the window size in dwm is fixed the fullscreen view is cropped.

Note that when the browser goes into fullscreen mode like this there is no change from the window manager's perspective as such, but it does receive a client message saying that the client has gone into fullscreen mode.

I'm adding a proposed fix for this which is to apply another resize of the client when receiving this message. This seems to work for me, although you'll notice that the browser first goes into the full fullscreen size and is cropped, but later re-adjusts to the new size. You might want to try this out.

**Comment by kronikpillow** [comment]
sorry for late replies to the issues i opened, I was very busy in RL, i will look in to it today and give you feedback :) thanks your for your efforts

**Comment by kronikpillow** [comment]
seems centered floating master is good now :)
