### ISSUE TITLE
FocusAdjacenttag and pertag patch

### ISSUE THREAD

**Issue by LorenzoMioso** [bakkeby/dwm-flexipatch#152]
Pertag patch does not not work when switching tag with focusadjacenttag.

**Comment by bakkeby** [comment]
Yes I see, there is no direct compatibility between these patches.

The expectation I presume is that when viewing the tag on the immediate left or right then the layout etc. of that tag is restored.

**Comment by bakkeby** [comment]
You may try with the above changes, seems to work fine in my testing.
