### ISSUE TITLE
firefox opens in 8th tag by default

### ISSUE THREAD

**Issue by godspeed-x** [bakkeby/dwm-flexipatch#154]
I believe it's because of this:
https://github.com/bakkeby/dwm-flexipatch/blob/c968fd9aae7c18e61428bcab0f09798c2f9bdfb5/config.def.h#L417
After searching for a bit I found that after changing `1 << 7` to `0`, it opens in the current tag.
Why is it like this by default?

**Comment by bakkeby** [comment]
It's just an example rule that comes with a bare 6.2 dwm:

See https://git.suckless.org/dwm/file/config.def.h.html

**Comment by godspeed-x** [comment]
I see. It actually works as I expect it to in arch but for some reason the issue arises in void linux.

**Comment by bakkeby** [comment]
Yes this is a known issue. I don't know why exactly, but the class hint for firefox seems to depend on the distribution or on the version. It is either "firefox" or "Firefox".

**Comment by godspeed-x** [comment]
Oh wow.  I didn't know that. I guess the issue is with firefox itself then and not dwm.
Thanks.
