### ISSUE TITLE
Azety Patch

### ISSUE THREAD

**Issue by mkblast** [bakkeby/dwm-flexipatch#159]
Can you add the azerty patch to the list?
I have an azerty keyboard and i can't change the workspaces without this patch.

**Comment by bakkeby** [comment]
All the patch does is change keybindings, which you can do yourself in your config.h file.

Actually you are encouraged to do that anyway to make the keybindings more optimal for your own workflow (as opposed to just getting used to the defaults). The default keybindings are also by no means optimal, with so many patches wanting attention. 

The critical bit here being that including a second set of keybindings would make the configuration file a lot more complicated to use and to maintain.

**Comment by bakkeby** [comment]
Come to think of it, the [azerty](https://dwm.suckless.org/patches/azerty/) patch is specifically for when you want to use the Alt key as the modifier key no?

I suspect that if you use Super / ModMask4 as the modifier key then you don't need that patch.

**Comment by mkblast** [comment]
> Come to think of it, the [azerty](https://dwm.suckless.org/patches/azerty/) patch is specifically for when you want to use the Alt key as the modifier key no?
> 
> I suspect that if you use Super / ModMask4 as the modifier key then you don't need that patch.

nah you need it both, I have ModMask4 as the modifier key and can't change the workspaces

**Comment by mkblast** [comment]
> All the patch does is change keybindings, which you can do yourself in your config.h file.
> 
> Actually you are encouraged to do that anyway to make the keybindings more optimal for your own workflow (as opposed to just getting used to the defaults). The default keybindings are also by no means optimal, with so many patches wanting attention.
> 
> The critical bit here being that including a second set of keybindings would make the configuration file a lot more complicated to use and to maintain.
