### ISSUE TITLE
CENTEREDFLOATINGMASTER_PATCH + CFACTS

### ISSUE THREAD

**Issue by kronikpillow** [bakkeby/dwm-flexipatch#16]
I find the Center floating master a very useful layout for my workflow, but due to resizehints 1 some windows in the stack are sized unequally, I noticed that with Mod+Shift+H/L with the cfacts patch enabled enables the user to resize the windows in the stack, but one issue I have with it is every time I press the keybindings to change the cfact it pulls the master window from the background back on top of everything ....

best scenario to reproduce this is to use CENTEREDFLOATINGMASTER_PATCH / layout and open 3 windows (for example Brave, Discord, and a file manager) place 1 in the master, then MOD+J 2x to put the master in the background, and then Mod+Shift+H & Mod+Shift+L to change cfacts, every time you change cfat it will pull up the master back to focus ...

it would be good if changing cfact wouldn't pull the master back in to focus

**Comment by bakkeby** [comment]
Hi @kronikpillow,

the master window isn't actually "floating", it's just drawn on top of the other clients.

The centered floating master patch on the suckless website was flimsy at best, where clients in the "stack" area (i.e. the ones in the background) would be drawn on top of the master windows in a seemingly unpredictable manner.

Changing the focus to that of the master window was merely a hacky workaround to make the master window stay on top of the other clients and it was clearly not an ideal solution. I worked out how to do this without having to change focus, so this should be working as you'd expect now (fix included as part of #12).

\
Thanks,

-Stein

**Comment by kronikpillow** [comment]
changing CFACTS in centered floating master now does change the CFACT of the stack without changing focus, it still does pull the master window back up but i guess that doesn't matter much

**Comment by bakkeby** [comment]
> it still does pull the master window back up but i guess that doesn't matter much

Yes that's kind of intentional. It's weird having a master window that is behind stack windows.

If you don't want this then you'd just need removing these two lines:
https://github.com/bakkeby/dwm-flexipatch/blob/master/patch/centeredfloatingmaster.c#L81,L82

I can make an option for it if need be.
