### ISSUE TITLE
Can You Add This Patch

### ISSUE THREAD

**Issue by usdogu** [bakkeby/dwm-flexipatch#162]
[this](https://dwm.suckless.org/patches/keychain/) is a patch for enabling keychords so we can use something like "MOD-p e" means press "modkey+p" then release it then press "e". I can't see there is something like this in already included patches. Can you add that?

Edit : I see there is *keymodes* patch but I think it is not the exactly same thing but I am not sure

**Comment by bakkeby** [comment]
There are four patches that I know of that changes the way keybindings are handled:
   - [keychain](https://dwm.suckless.org/patches/keychain/)
   - [keycodes](https://dwm.suckless.org/patches/keycodes/)
   - [keymodes](https://dwm.suckless.org/patches/keymodes/)
   - [keypressrelease](https://dwm.suckless.org/patches/keypressrelease/)
 
Adding these kind of patches complicate things.

If I were to make one of these patches optional in dwm-flexipatch then I would end up with two sets of keybindings and one set is nearly 400 lines in config.h:

https://github.com/bakkeby/dwm-flexipatch/blob/0733c39e0c8d423bb53a389c167fcfe9dcbb7a72/config.def.h#L806-L1176

If I were to make two of these patches optional then I would end up with four sets of keybindings.

If I were to make three of these patches optional then I would end up with eight sets of keybindings.

If I were to make three of these patches optional then I would end up with eight sets of keybindings.

If I were to make all four of these patches optional then I would end up with sixteen sets of keybindings.

The alternative would be to make such patches non-optional and everyone using this would just have to live with it.

The main problem with these kind of patches is that they have only a few use-cases where they might be practical. This is the reason why the patches has not been added to this project so far and why they are not going to.

On the plus side each of these are relatively easy to patch into your own build of dwm-flexipatch should you need them - you just need to apply the patches by hand.

-----

It is worth noting though that [sxhkd](https://github.com/baskerville/sxhkd) can handle key chaining.

From the man page:

> When multiple chords are separated by semicolons, the hotkey is a chord chain: the command will only be executed after receiving each chord of the chain in consecutive order.

Example sxhkd configuration:
```java
super + p; super + e
    st
```

Likewise for key release:

>  If @ is added at the beginning of the keysym, the command will be run on key release events, otherwise on key press events.

Example sxhkd configuration:
```java
super + @p
    st
```

As for key modes it looks like it has support for that as well.

> The colon character can be used instead of the semicolon to indicate that the chord chain shall not be aborted when the chain tail is reached.

That is a bit cryptic, but the configuration goes like this:
```java
super + v : bracket{left,right}
    {st,gnome-terminal}
```

In the above example the user presses super + v and we enter this mode where the user can press \[ to launch st or \] to launch gnome-terminal and the user can keep spawning terminals like this using \[ or \] until they press escape to exit this mode.

It is a silly example, you can add many bindings to individual modes like this.

**Comment by usdogu** [comment]
Thanks a lot I understand, I will look sxhkd, Closing this
