### ISSUE TITLE
Pertag2?

### ISSUE THREAD

**Issue by explosion-mental** [bakkeby/dwm-flexipatch#163]
I'm back at ricing dwm and i forgot to ask this. Back then I spend a lot of time searching everywhere for a patch that made layout **X** start on tag **Y**. Then found jokerboy-dwm, but it was not 6.2 and also found this other repo, which isn't 6.2 as well. I'm just wondering if you didn't know about it or it is incompatible with dwm-6.2

### [Pertag2](https://github.com/w0ng/jokerboy-dwm/blob/master/01-dwm-6.0-pertag2.diff)
_Basically pertag2 offers [this](https://github.com/w0ng/jokerboy-dwm/blob/fbe7df41c89daac83897a8ef3b3413b0a537bbbe/config.h#L55-L63):_
```/* tagging */
    static const Tag tags[] = {
	    /* name       layout           mfact    nmaster */
	    { "main",     &layouts[4],     -1,      -1 },
	    { "term",     &layouts[4],     -1,      -1 },
	    { "web",      &layouts[1],     -1,      -1 },
	    { "im",       &layouts[5],     0.83,    -1 },
	    { "dld",      &layouts[4],     -1,      -1 },
	    { "misc",     &layouts[4],     -1,      -1 },
    };
```

_Which, for me, is a  **lot** of customization (kinda like vanitygaps)_

### The other option
https://github.com/mjheagle8/dwm/commit/5b8cdf64ff583bdfed0b4aa35cfe3510c15d29eb

[This](https://github.com/mjheagle8/dwm/blob/5b8cdf64ff583bdfed0b4aa35cfe3510c15d29eb/config.h#L23-L25) in the other hand is just what I was searching for done in a hacky way. 
```/* tagging */
static const char *tags[] = { "web", "media", "msg", "4", "5"};
static const int taglayouts[] = {2, 2, 0, 0, 0};
```

**Comment by bakkeby** [comment]
Both are pretty simplistic and are (as most approaches) made with a single monitor in mind, but are fine to use if they work for you.

I ended up with [monitorrules](https://github.com/bakkeby/patches/wiki/monitorrules) for this kind of customisation as I use have a dual monitor setup where the adjacent one is vertical - so I use different layouts there than on my horizontal monitor.

**Comment by explosion-mental** [comment]
That means you can have the monitor with '-1' value and it would "work" as pertag2? Also it would be nice to add gaps in there (since now you can have gaps on a pertag basis) which is a bit overkill but nice.

**Comment by explosion-mental** [comment]
update:
I doubt more people are interested but after playing with monitorrules patch and pertag 2... I got nothing lol. But I found a [patch],(https://github.com/dgreid/HomeDir/blob/master/build/dwm.layout-per-tag-init.diff) which was too obvious to me.

On modern dwm and pertag builds:
```diff
--- a/config.def.h
+++ b/config.def.h
/* tagging */
@@ -20 +21 @@ static const char *tags[] = { "1", "2", "3", "4", "5", "6", "7", "8", "9" };
+static const int taglayouts[] = {    0,   1,    0,   0,    0,    0,    0,    0,    0 };

static const Rule rules[] = {
	/* xprop(1):
	 *	WM_CLASS(STRING) = instance, class
	 *	WM_NAME(STRING) = title
	 */
--- a/dwm.c
+++ b/dwm.c
@@ -705,6 +706,23 @@ createmon(void)
			/* init mfacts */
			m->pertag->mfacts[i] = m->mfact;

			/* init layouts */
-			m->pertag->ltidxs[i][0] = m->lt[0];
+			m->pertag->ltidxs[i][0] = m->lt[taglayouts[i - 1]];
			m->pertag->ltidxs[i][1] = m->lt[1];
			m->pertag->sellts[i] = m->sellt;
```
