### ISSUE TITLE
Shiftview with scrachtpad

### ISSUE THREAD

**Issue by explosion-mental** [bakkeby/dwm-flexipatch#164]
This [patch](https://github.com/bakkeby/dwm-flexipatch/blob/master/patch/shiftview.c)

```void
shiftview(const Arg *arg)
{
	Arg shifted;
	#if SCRATCHPADS_PATCH
	unsigned int seltagset = selmon->tagset[selmon->seltags] & ~SPTAGMASK;
	#else
	unsigned int seltagset = selmon->tagset[selmon->seltags];
	#endif // SCRATCHPADS_PATCH
	if (arg->i > 0) // left circular shift
		shifted.ui = (seltagset << arg->i)
		   | (seltagset >> (NUMTAGS - arg->i));
	else // right circular shift
		shifted.ui = seltagset >> -arg->i
		   | seltagset << (NUMTAGS + arg->i);

	view(&shifted);
}
```

Shoud be
_(from the shiftviewclient)_

```void
shiftview(const Arg *arg)
{
	Arg shifted;
	#if SCRATCHPADS_PATCH
	unsigned int seltagset = selmon->tagset[selmon->seltags] & ~SPTAGMASK;
	#else
	unsigned int seltagset = selmon->tagset[selmon->seltags];
	#endif // SCRATCHPADS_PATCH
	if (arg->i > 0) // left circular shift
		shifted.ui = (seltagset << arg->i)
		   | (seltagset >> (LENGTH(tags) - arg->i));
	else // right circular shift
		shifted.ui = seltagset >> -arg->i
		   | seltagset << (LENGTH(tags) + arg->i);

	view(&shifted);
}
```

With **NUMTAGS** dwm crashes when trying to 'cycle' tags (Go to tag 1 to tag 9 or the other way with the `shiftview` binding).
What works is using LENGTH(tags).

_Din't know this patch existed I was using the while loops on shiftviewclient before, which wasn't necesary from what I'm looking._
_P.D.:_ Can you change the comments from `//` to `/* */` please, lol.
_P.D.2_: Is it possible to make the `tagtoright` and `tagtoleft` functions (possibly even merge them into one) from patch [focusadjacenttag](https://dwm.suckless.org/patches/focusadjacenttag/) to behabe like `shiftviewclients` one; meaning send the client to the left ( -1) or right (+1) tag that has one or more clients, if none just move them to the side, next tag.

**Comment by explosion-mental** [comment]
Ok. This is **not** related to the bug. Manage to make the focusadjacentag like [this](https://github.com/explosion-mental/Dwm/commit/ccce7485524bf1cb2de56a6fcd679762658022f5):
```void
shiftag(const Arg *arg) {

	Arg shiftag;
	unsigned int seltagset = selmon->tagset[selmon->seltags] & ~SPTAGMASK;

	if (arg->i > 0) /* tag to right */
	shiftag.ui = (seltagset << arg->i)
	    | (seltagset >> (LENGTH(tags) - arg->i));
	else 	/* tag to left */
	shiftag.ui = (seltagset >> -arg->i)
            | (seltagset << (LENGTH(tags) + arg->i));
        tag(&shiftag);
}
```

Yes is basically shiftview but for tags. Idk if `tag()` is necesary but it has an if statement which im guessing is looking for something (maybe just directly put `selmon->sel->tags` ? it would need the focusnull and the arrange thingy). If you have the time can you check it and after, consider changing it for the focusadjancent one since less is more(?.

**Comment by bakkeby** [comment]
I'm not sure how `LENGTH(tags)` would work in dwm-flexipatch as the `tags` variable does not exist.

If I were to guess then I would say that you are trying to copy files from dwm-flexipath's patch/ directory into your own custom build of dwm?

As for changing focusadjacenttag, the feature is a representation of this patch:
   - https://dwm.suckless.org/patches/focusadjacenttag/

The idea is that people can try out this patch through dwm-flexipatch before deciding whether or not they want to try and integrate it into their own build. Giving people a totally different experience would defeat the purpose of this build.

You can of course clone or fork and hack about as you want in a custom build of coruse.

**Comment by explosion-mental** [comment]
> If I were to guess then I would say that you are trying to copy files from dwm-flexipath's patch/ directory into your own custom build of dwm?
Yep. To be sure I cloned the repo and yes in fact, theres no bug!.

**Comment by explosion-mental** [comment]
>As for changing focusadjacenttag, the feature is a representation of this patch:
>
>    https://dwm.suckless.org/patches/focusadjacenttag/
>
>The idea is that people can try out this patch through dwm-flexipatch before deciding whether or not they want to try and integrate >it into their own build. Giving people a totally different experience would defeat the purpose of this build.
>
>You can of course clone or fork and hack about as you want in a custom build of coruse.

I see. Made a [patch](https://github.com/explosion-mental/Dwm/blob/main/Patches/dwm-shift-tools-6.2.diff) but only for scratchpad compatibility if interested.
