### ISSUE TITLE
errors while trying to compile with ipc patch

### ISSUE THREAD

**Issue by godspeedfw** [bakkeby/dwm-flexipatch#166]
```c
In file included from patch/include.c:154,
                 from dwm.c:789:
patch/ipc.c: In function ‘setupepoll’:
patch/ipc.c:67:22: error: ‘ipcsockpath’ undeclared (first use in this function)
   67 |         if (ipc_init(ipcsockpath, epoll_fd, ipccommands, LENGTH(ipccommands)) < 0)
      |                      ^~~~~~~~~~~
patch/ipc.c:67:22: note: each undeclared identifier is reported only once for each function it appears in
patch/ipc.c:67:45: error: ‘ipccommands’ undeclared (first use in this function); did you mean ‘IPCCommand’?
   67 |         if (ipc_init(ipcsockpath, epoll_fd, ipccommands, LENGTH(ipccommands)) < 0)
      |                                             ^~~~~~~~~~~
      |                                             IPCCommand
```
I am getting these errors on compiling after enabling ipc patch.

**Comment by bakkeby** [comment]
Did you just copy in your own config.h perhaps?

To get that error you'd have to be missing this block from the config file.

https://github.com/bakkeby/dwm-flexipatch/blob/59eb825b7ae47fcc501e3db1e55847492dd85c68/config.def.h#L1447-L1609

**Comment by godspeed-x** [comment]
does this have to be in config.h or just config.def.h too?

**Comment by bakkeby** [comment]
`config.def.h` as the name suggests is the _default_ configuration file.

In all suckless builds the default configuration file will be copied to `config.h` if it does not already exist. The build only relies on `config.h` in the end.

Not important but just for reference this is controlled by this bit in the Makefile:
https://github.com/bakkeby/dwm-flexipatch/blob/59eb825b7ae47fcc501e3db1e55847492dd85c68/Makefile#L28-L29

And the `config.h` is included in dwm.c here:
https://github.com/bakkeby/dwm-flexipatch/blob/59eb825b7ae47fcc501e3db1e55847492dd85c68/dwm.c#L786-L787
