### ISSUE TITLE
statuspadding patch conflicts with status2d

### ISSUE THREAD

**Issue by siduck76** [bakkeby/dwm-flexipatch#168]
Hi @bakkeby! Idk if its relevant here but can you tell me how did you patch statuspadding patch along with status2d? I cant make it work :/ . I wanted to try flexipatch's statuspadding or status2d patch but i dont want dwmblocks stuff.

My issue detailed here : 

https://www.reddit.com/r/suckless/comments/on80gv/dwm_statuspadding_patch_conflicts_with_status2d/

**Comment by bakkeby** [comment]
I had a drawstatusbar function that took the system tray width and status padding as arguments:
https://github.com/bakkeby/dwm-flexipatch/blob/ccb275b984b4346bc779c0f8a7f96d26ad676508/patch/status2d.c#L2

The barpadding patch would just set the padding:
https://github.com/bakkeby/dwm-flexipatch/blob/ccb275b984b4346bc779c0f8a7f96d26ad676508/dwm.c#L1609-L1611

The `stp` variable being passed to the function:
https://github.com/bakkeby/dwm-flexipatch/blob/ccb275b984b4346bc779c0f8a7f96d26ad676508/dwm.c#L1683-L1684

In your case (https://paste.sh/B1BPLrlU#nBN4kJz6v7UAxFsLQXZ8hsXZ) all of the adjustments are handled within the `drawstatusbar` function itself.

E.g. you already have code for the system tray width in there:
```c
x = m->ww - w - getsystraywidth();
```
All that the statuspadding patch is really doing is to remove the 2x right padding, which is set here in the statu2d code:
```c
	w += 2; /* 1px padding on both sides */
```
So I think all you really need to do is to change that from `2` to `lrpad` and to increment x with `lrpad / 2`.

**Comment by siduck76** [comment]
I have tried that , sadly no luck :/

![image](https://user-images.githubusercontent.com/59060246/126138223-23efad9d-0128-4cb4-b3ff-5a1025b8cc81.png)

**Comment by siduck76** [comment]
I think something like this might work https://www.reddit.com/r/suckless/comments/nw5rvy/how_to_apply_status2dstatuscmd_patches_alongside/ 

but idk how to implement it with statuspadding :l

**Comment by bakkeby** [comment]
So what exactly is not working for you? All the statuspadding patch is doing is to increase (adjust) the bar height and to increase (adjust) the left/right padding (lrpad) of text on the bar, i.e. increasing lrpad will increase the spacing between the tags as an example.

**Comment by siduck76** [comment]
> So what exactly is not working for you? All the statuspadding patch is doing is to increase (adjust) the bar height and to increase (adjust) the left/right padding (lrpad) of text on the bar, i.e. increasing lrpad will increase the spacing between the tags as an example.

I want the statuspadding around the rectangles created by status2d too , other stuffs getting padding but the rectangles drawn by status2d dont have any space around them 

look : 

![image](https://user-images.githubusercontent.com/59060246/126145981-e9187883-5f39-49f2-a848-0f42a849d9bb.png)

**Comment by siduck76** [comment]
like polybar has options to add margin around modules 

![image](https://user-images.githubusercontent.com/59060246/126146177-fbd4ce62-b03a-4b68-acb7-6cb0af5274a4.png)

**Comment by siduck76** [comment]
basically I just want some space between the bar and the rectangles drawn by status2d

**Comment by bakkeby** [comment]
Right, but that's not what the statuspadding patch does though. It is just meant to add space at the start of the status and at the end of the status - it is one string that is retrieved via the root name.

You can add the spacing via status2d markup, e.g. by moving the cursor forward by a few pixels.
```
^f4^
```
Alternatively if you want to do this within dwm then you have two places in the `drawstatusbar` function where it does this: 

```c
w = TEXTW(text) - lrpad;
drw_text(drw, x, 0, w, bh, 0, text, 0);
```

(that's within the main while loop and directly after if there is any leftover text)

you would change this to be:
```c
w = TEXTW(text);
drw_text(drw, x, 0, w, bh, lrpad / 2, text, 0);
```

If you do this though then you'll have to take these gaps into account when handling button clicks (if you also have the statuscmd patch).

**Comment by siduck76** [comment]
> ```c
> w = TEXTW(text);
> drw_text(drw, x, 0, w, bh, lrpad / 2, text, 0);
> ```

thanks for this but I wanted top/bottom  padding around the rectangles , not left/right. Is that even possible?

![image](https://user-images.githubusercontent.com/59060246/126148673-ff3cd8e4-808f-4e86-a217-3e0b7d56e296.png)

**Comment by siduck76** [comment]
like this 
![image](https://user-images.githubusercontent.com/59060246/126148916-772217ae-02b7-454c-aff2-c26777937974.png)

**Comment by bakkeby** [comment]
You can yes, it's the same as having a border around the bar, just that the border in this case is the same colour as the main background of the bar. It is similar to how borders are drawn around client windows.

I have that in dwm-flexipatch, but I don't have an example patch for a traditional bar.

The way you would do this is that you'd increase the bar height (bh) with 2 * the border size of the bar (which will look best if it is the same as for the client windows).

When drawing the bar you would colour the whole bar the colour of the border.

```c
        XSetForeground(drw->dpy, drw->gc, scheme[SchemeNorm][ColBorder].pixel);
        XFillRectangle(drw->dpy, drw->drawable, drw->gc, 0, 0, m->ww, bh);
```
when it comes to actually drawing the window you'd have to use a different height which is the bar height less the border pixels.

I don't remember if merely adding the x and y border padding when calling
```c
drw_map(drw, m->barwin, 0, 0, m->ww, bh);
```
is enough or not or if you need to take that into account when you draw text / rectangles.

All in all I think that it should be relatively easy to accomplish and fun to tinker with.

**Comment by siduck76** [comment]
> ```c
> XSetForeground(drw->dpy, drw->gc, scheme[SchemeNorm][ColBorder].pixel);
>         XFillRectangle(drw->dpy, drw->drawable, drw->gc, 0, 0, m->ww, bh);
> ```

cool! i just need an internal border ( same color as bar's bg so it would look like inner padding) but where do I add the code you sent?

**Comment by bakkeby** [comment]
I had it in the drawbar function, but probably because in my case the color needs to change depending on context. Potentially you could have this only in the updatebarpos function, it's all about tinkering to make it work. The calls in the updatesystray function is different as the systray is a separate window.

**Comment by fitrh** [comment]
> like this
> ![image](https://user-images.githubusercontent.com/59060246/126148916-772217ae-02b7-454c-aff2-c26777937974.png)

Just take a look to [this](https://codemadness.org/paste/dwm-border-bar.patch) patch, this the result with some modification to suit another patch (barpadding)
![20210719_203507_full](https://user-images.githubusercontent.com/55179750/126161507-e861cdfe-ddcc-4c1a-a12a-f3ec826273e8.jpg)

**Comment by bakkeby** [comment]
^ yes that patch looks good (on paper) to me

**Comment by siduck76** [comment]
> > like this
> > ![image](https://user-images.githubusercontent.com/59060246/126148916-772217ae-02b7-454c-aff2-c26777937974.png)
> 
> @siduck76 Just take a look at [this](https://codemadness.org/paste/dwm-border-bar.patch) patch, maybe thats what you want, this is my result with some modification to suit another patch (barpadding)
> ![20210719_203507_full](https://user-images.githubusercontent.com/55179750/126161507-e861cdfe-ddcc-4c1a-a12a-f3ec826273e8.jpg)
> ![20210719_205037_full](https://user-images.githubusercontent.com/55179750/126162999-486df9da-e7bc-49bf-8c44-2f5badd5a3fb.jpg)

yeah I got this already , but unable to patch it right :/ . I patched it but didnt see any results . My dwmbar has systray , barheight , status2d patches . It would be very helpful If you could patch it for me in your free time 

https://github.com/siduck76/chadwm

**Comment by siduck76** [comment]
nvm everything works now!

![2021-07-21-155501_1366x768_scrot](https://user-images.githubusercontent.com/59060246/126476657-a42a9467-19d1-4f84-9aef-308bad89ae2e.png)

someone here helped me!

https://www.reddit.com/r/suckless/comments/on80gv/dwm_statuspadding_patch_conflicts_with_status2d/
