### ISSUE TITLE
stacker patch request

### ISSUE THREAD

**Issue by kronikpillow** [bakkeby/dwm-flexipatch#17]
could you include the stacker patch? I got addicted to it, it's especially useful when using the centered floating master as the main layout :D

**Comment by bakkeby** [comment]
https://dwm.suckless.org/patches/stacker/
https://dwm.suckless.org/patches/stacker/dwm-stacker-6.0.diff

**Comment by kronikpillow** [comment]
u want me to try to make it? sure :D :)

**Comment by bakkeby** [comment]
:) no just adding links for my own reference

**Comment by bakkeby** [comment]
Hi @kronikpillow,

I have added this now. Note that I had to change the default keybindings listed on the patch page to j, k, w, e, a, s, and z due to the many conflicts with other patches. I'm sure you'd customize that to your own liking anyway, but just wanted to let you know.

\
Thanks,

-Stein

**Comment by kronikpillow** [comment]
thanks :D love it :D
