### ISSUE TITLE
Winicon patch

### ISSUE THREAD

**Issue by ashincoder** [bakkeby/dwm-flexipatch#170]
could you please leave the diff for winicon patch. Would love to try it on my build of dwm

**Comment by bakkeby** [comment]
I suppose you found https://dwm.suckless.org/patches/winicon/

**Comment by ashincoder** [comment]
yes i did. Such stupidity from me.
sorry

**Comment by bakkeby** [comment]
Well it must have been recently pushed, it wasn't up there two days ago. Didn't check yesterday.
