### ISSUE TITLE
ClkRootWin dragcfact does not work

### ISSUE THREAD

**Issue by der-zonk** [bakkeby/dwm-flexipatch#175]
```
	{ ClkRootWin,           0,                  Button1,        dragmfact,    {0} },
	{ ClkRootWin,           0,                  Button3,        dragcfact,    {0} },
```
dragmfact works flawlessly...
As always I have no clue about the topic and maybe you know what's up. =)
Do they work different? Does dragcfact need me to point ON the target? =(

**Comment by bakkeby** [comment]
The `dragmfact` allows the master stack factor of the layout to be dragged using the mouse. This of course has no bearing if you are on a monocle layout for example.

The `dragcfact` allows the user to change the size of a tiled client relative to other clients in the same area (master or stack), as such this must be used on a client window. This function has no bearing on layouts that do not support cfacts of course. I'd first check if the layout used supports cfacts or not.

**Comment by der-zonk** [comment]
I still don't see why it is clear that I can use dragmfact on root window but not dragcfact, and all layouts I use "support" dragcfact.
It works when I point ON a window and use the modkey+button method, but not on root window.. I have the patch that teleports the mouse to a window corner.. It works with dragmfact.. I can click anywhere on root window but the same does not apply to dragcfact, for which the mouse teleport also works when using modkey+button mode but not with root window click.

**Comment by bakkeby** [comment]
The only thing I can think of is that the `dragcfact` function requires that there is a selected client on the monitor. Don't remember if the selected client becomes unselected when you click on the root window or not.

**Comment by der-zonk** [comment]
At least the focused border border color doesn't change when clicking on root w
