### ISSUE TITLE
creating new tag

### ISSUE THREAD

**Issue by plasmoduck** [bakkeby/dwm-flexipatch#176]
how can I change tag 0 to be an extra useful tag instead of showing content of all tags?

**Comment by bakkeby** [comment]
To make it extra useful you can just change the keybinding. E.g.

```c
{ MODKEY, XK_0, quit, { 0 } },
```
As for dynamically creating new tags, you can't really.

In principle you could remove the const from the tags array in config.h and create a new list copying in all the existing tags and replace the tags reference with this new list, but you wouldn't have any keybindings associated with the new tag so at best you'd be forced to use the mouse to select it. 

For something like this it would be easier to predefine extra tags that are hidden by default (e.g. using hidevacanttags), that way you could have keybindings for them as well. 

If you only need one more tag then just make 0 refer to the tenth tag.

**Comment by plasmoduck** [comment]
okay so I made a tenth tag and it works I can use it, but when I switch to it everything on the other tags goes fullscreen and I loose my gaps, I can still see the bar.

**Comment by bakkeby** [comment]
Did you remove the keybinding for MOD+0 that calls view?

**Comment by plasmoduck** [comment]
Yes I commented it out.

**Comment by bakkeby** [comment]
Your build is based on flexipatch is it not? In that case you'd also need to update the `NUMTAGS` macro in dwm.c

**Comment by plasmoduck** [comment]
Yep 😊 Done that too, changed it to 10.

**Comment by bakkeby** [comment]
I don't know, can't replicate. It sounds like there must be some conflicting keyboard shortcuts. Do you have the right bindings in `config.h`?

**Comment by plasmoduck** [comment]
Thanks ill look into it. One more question, Im using the BAR_STATUSBUTTON_PATCH and have one button on the left of the tags before tag1, how can I add an extra button on the right after my statusbar?

**Comment by bakkeby** [comment]
The easiest would probably be to just add that extra button as part of the status.

As-is you would have to make a copy the bar rule as well as the module functions. If you use the same symbol then you would only need to copy the click function and add a new click enum in dwm.c, e.g. `ClkButton2`, so that you can add custom keybindings for it.

**Comment by plasmoduck** [comment]
What do you mean by add the extra button as part of the status? In my statusbar script?

**Comment by bakkeby** [comment]
Yes, it would just be a block that doesn't update.

**Comment by plasmoduck** [comment]
I don't use dwm-blocks though, just a simple shell script with trap.

**Comment by bakkeby** [comment]
I guess that's even easier then :)

**Comment by plasmoduck** [comment]
How would I do it? Sorry.

**Comment by bakkeby** [comment]
In your script you would just add another echo / printf for the new status button.

Your main problem will be that you do not have any click handling in your script, but you could add that with the https://dwm.suckless.org/patches/statuscmd/ patch (the nosignal one).

I guess this route has complications as well. Perhaps the path of least resistance is to make a copy of the statusbutton functions after all.

**Comment by plasmoduck** [comment]
How can I add click handling? Something like this?
 _shutdown=$(xdotool search --onlyvisible ~/bin/dmenu_shutdown behave %@ mouse-click getmouselocation)

^^ This doesnt work obviously

**Comment by plasmoduck** [comment]
The full snippet is actually:

shutdown (){
         _shutdown=$(xdotool search --onlyvisible ~/bin/dmenu_shutdown behave %@ mouse-click getmouselocation)
         _shutdownicon=
         printf ^c#FB4934^%s^c#D5C4A1^%s "$_shutdownicon" "$_shutdown"
}

**Comment by bakkeby** [comment]
If you are using the statuscmd patch then look at the "Without signals" section for examples.

It is easiest to just have these point to individual scripts.

**Comment by plasmoduck** [comment]
Thanks for the reply. One more question, I'm trying to add this FreeBSD support into 'patch/swallow.c' but when I compile I get this error:
./patch/swallow.c:100:28: warning: implicit declaration of function 'kinfo_getproc' is
      invalid in C99 [-Wimplicit-function-declaration]
        struct kinfo_proc *proc = kinfo_getproc(p);
                                  ^
./patch/swallow.c:100:21: warning: incompatible integer to pointer conversion initializing
      'struct kinfo_proc *' with an expression of type 'int' [-Wint-conversion]
        struct kinfo_proc *proc = kinfo_getproc(p);
                           ^      ~~~~~~~~~~~~~~~~
./patch/swallow.c:104:10: error: incomplete definition of type 'struct kinfo_proc'
        v = proc->ki_ppid;
            ~~~~^
./patch/swallow.c:100:9: note: forward declaration of 'struct kinfo_proc'
        struct kinfo_proc *proc = kinfo_getproc(p);
               ^

How and where do I define kinfo_proc ?

**Comment by bakkeby** [comment]
That sounds like a missing library.

Do you include `-lkvm` in your config.mk?

Check that you have the imports in place at the top of the file?

```c
#include <sys/sysctl.h>
#include <kvm.h>
```

**Comment by plasmoduck** [comment]
In config.mk I have KVMLIB = -lkvm

I just added 
include <sys/sysctl.h>
#include <kvm.h>

to dwm.c and now I have 10 errors lol

**Comment by bakkeby** [comment]
The compatibility thing was for OpenBSD, but I'd have thought that it would work for FreeBSD as well. At least I haven't heard anyone talking or complaining about this.

**Comment by plasmoduck** [comment]
Yeah I was never able to get the swallow patch to work, so I'm trying this
