### ISSUE TITLE
polybar not launching and normal bar is

### ISSUE THREAD

**Issue by Laar3** [bakkeby/dwm-flexipatch#177]
i added the polybar patch aswell as the ipc patch and enabled the relevant lines in config.mk and giving the path to the polybar launch script .however upon launching, dwm is only shows the normal bar.

i am using the `polybar-dwm-module` fork of polybar

**Comment by bakkeby** [comment]
Do you also use the [anybar](https://dwm.suckless.org/patches/anybar/) patch?

**Comment by Laar3** [comment]
Yep I also installed the anybar patch

**Comment by bakkeby** [comment]
That polybar is not launching you would have to check your polybar launch script, make sure that it is executable etc.

The anybar patch, if applied on a bare dwm, omits creating the bar completely. In dwm-flexipatch there is nothing stopping you from having both an internal bar and an external bar such as polybar. That is why the bar is still showing.

To disable the internal bar you can set the `barrules` array in config.h to:

```c
static const BarRule barrules[] = { { -2 } };
```
and disable the bar modules that are enabled by default:

```c
#define BAR_LTSYMBOL_PATCH 1
#define BAR_STATUS_PATCH 1
#define BAR_TAGS_PATCH 1
#define BAR_WINTITLE_PATCH 1
#define BAR_TITLE_LEFT_PAD_PATCH 1
```

There is more details about this in #118.

**Comment by Laar3** [comment]
thanks i hadnt set the bar rules properly, thats fixed it.
