### ISSUE TITLE
How do you add colors with statuscolors? 

### ISSUE THREAD

**Issue by jfab-123** [bakkeby/dwm-flexipatch#180]
I have enabled status colors package, however I don't quite understand the guide of the patch : https://dwm.suckless.org/patches/statuscolors/

It says that I should output to my scripts "\x01" and so on, as the colors are ordered in the array of the config.h. However when I do for example xsetroot -name (echo -e "\x01 hi") I get a blank square and the word hi in my bar.

**Comment by bakkeby** [comment]
Status colors is not that great of a patch, but have you tried colors other than the default?

E.g.
```sh
$ xsetroot -name $(echo -e "\x03 hello\x04 there\x05 how\x02 are\x06 you\x07 today?")
```

The status2d patch is more flexible when it comes to choosing colors, but has a more complicated markup syntax.

**Comment by bakkeby** [comment]
A blank square may suggest that the statuscolors patch is not actually being used, possibly this could be if you have enabled something else that might conflict.

**Comment by jfab-123** [comment]
```$ xsetroot -name $(echo -e "\x03 hello\x04 there\x05 how\x02 are\x06 you\x07 today?")```
Still outputs blank squares, but maybe I'll try the status2d package, thank you!!!

**Comment by jfab-123** [comment]
> A blank square may suggest that the statuscolors patch is not actually being used, possibly this could be if you have enabled something else that might conflict.

I just enabled the systray, focusmater, scratchpad, vanity gaps and centered master patches, but I still don't have any colors

**Comment by jfab-123** [comment]
Is ```config.h``` supposed to change based on the statuscolors package? I don't see any line with an if statement containing it's name

**Comment by bakkeby** [comment]
> Is config.h supposed to change based on the statuscolors package?

No it is not, it is supposed to use whatever colour schemes you have (or explicitly add yourself for this purpose).

I think the patch just no longer works, likely due to something that has gotten lost over time. I'll have a closer look to see if I can fix it.

**Comment by bakkeby** [comment]
Feel free to try the above if you are still keen.

I don't quite remember what the deal was with this, maybe I had planned to remove the statuscolors patch or it got lost in refactoring and I forgot to add it back in again.

**Comment by jfab-123** [comment]
I just changed to status2d, it's easier, thanks!
