### ISSUE TITLE
Please incorporate tag preview patch

### ISSUE THREAD

**Issue by SisyphusIsntHappy** [bakkeby/dwm-flexipatch#181]
Recently a new dwm patch for previewing tags was released. Please attach this patch into the dwm-flexipatch project.

Here it the link, to dwm page : https://dwm.suckless.org/patches/tag-previews/

**Comment by der-zonk** [comment]
How is this on performance?
I get a pretty significant performance drop with e.g. round corners and can't include this in my build because of that.

**Comment by bakkeby** [comment]
@der-zonk the way it works is that whenever you change tags it takes a screenshot of the tag you are on.

Naturally this will add a delay when changing view from one tag to another.

I did a test on my build performing 1000 tag switches. The performance will of course depend on many factors, but I believe that the relative performance impact will be similar for other setups.

|                         | Without preview | With preview |
| ----------------------- | --------------- |------------- |
| Total time              | 10.519s         | 1m 59.02s    |
| Time to switch tag      | 10.5ms          | 119ms        |
| Tag switches per second | 95              | 8.40         |

In my case the performance impact was an 11.3x increase in time to change tags. While it is still very quick and barely noticeable to the human eye you may feel that it is less snappy when it comes to changing tags.

As for presenting the previews when hovering the mouse cursor over the tags on the bar this is a perfectly smooth experience and you should not expect any performance impact with regards to this.

**Comment by bakkeby** [comment]
Integrating this patch into dwm-flexipatch is possible, but it would mean upgrading / changing barmodules to support on hover actions. This means that everyone upgrading dwm-flexipatch will have to also update their barmodules configuration.

Ultimately the patch won't be as-is as there are several changes needed to make it compatible with barmodules.

Overall I am not entirely sure if integrating this is worth the effort, but if there is enough interest then I might reconsider.

**Comment by 766F6964** [comment]
@bakkeby 
+1 from me for this patch. Would love to see it in cooperated in dwm-flexipatch.

**Comment by bakkeby** [comment]
I have added this patch on branch [tagpreview](https://github.com/bakkeby/dwm-flexipatch/tree/tagpreview) in case you guys want to have a look. It is quite invasive and will break existing configuration (wrt `barrules` in any case).

**Comment by N-R-K** [comment]
> and barely noticeable to the human eye

Just dropping by to say that this is a common misconception. 100ms sounds quite low but human eye can detect even [1ms vs 2ms of delay](https://doi.org/10.1145/2556288.2557037).

[A visual demonstration of what 1ms vs 10ms of delay looks like for comparison](https://youtu.be/vOvQCPLkPt4?t=80).

**Comment by SisyphusIsntHappy** [comment]
> I have added this patch on branch [tagpreview](https://github.com/bakkeby/dwm-flexipatch/tree/tagpreview) in case you guys want to have a look. It is quite invasive and will break existing configuration (wrt `barrules` in any case).

Great! and many thanks, will try. Although 100ms delay is very noticeable, you can see it by setting a fade delay of 100ms in picom.  Anyway, no one's goona have to switch tags 8 times a second.

**Comment by CSpencerND** [comment]
I tried the tagpreview patch and when I view a different tag on my second monitor (ie. go from tag 1 to 2) dwm bugs out. The bars disappear and keybinds stop working so I have to open a tty (if I don't already have a terminal open) `sudo pkill X` to get out.

I'm not getting any compiler errors. No idea what could be the issue.

**Comment by bakkeby** [comment]
> I tried the tagpreview patch and the preview doesn't pop up on tag hover.

As far as I remember the previews are only generated when you leave a tag, i.e. they won't be there upfront.

As for the error the way you describe it makes me think that dwm crashes leaving you with just X running. I shall see if I can reproduce this issue.

**Comment by bakkeby** [comment]
@CSpencerND I tried replicating this issue but tag switching on a secondary monitor worked just fine for me with this patch. Is this in combination with any other patches and if so could you list them? What I could try is to rebase this branch on top of the latest master.

**Comment by CSpencerND** [comment]
> @CSpencerND I tried replicating this issue but tag switching on a secondary monitor worked just fine for me with this patch. Is this in combination with any other patches and if so could you list them? What I could try is to rebase this branch on top of the latest master.

It happens even if it's the only patch applied on a freshly cloned repo.

**Comment by bakkeby** [comment]
@CSpencerND that is weird. Does it also happen with no changes to config.h?

**Comment by CSpencerND** [comment]
No changes to anything

**Comment by CSpencerND** [comment]
@bakkeby I just tried base dwm with the tag preview patch and the same thing happens, so it's got nothing to do with flexipatch.

**Comment by CSpencerND** [comment]
Exactly. It doesn't break if there aren't any clients. So, maybe something goes wrong when it tries to make the snapshot.

**Comment by CSpencerND** [comment]
Very interesting, I'll try this right away!

**Comment by CSpencerND** [comment]
> So if you have the HDMI monitor attached and you run the xrandr command before dwm starts (in ~/.xinitrc if you use startx or in your ~/.xsession if you use a login/display manager) then it should work.

That was it! Feels like I've been doing backwards this whole time.

**Comment by bakkeby** [comment]
> That was it! Feels like I've been doing it backwards this whole time.

Nah it is not your fault, it should work either way. I have rebased on top of latest master of dwm-flexipatch and added a fix for that particular issue.

@N-R-K I added a NULL check there, thanks.

**Comment by CSpencerND** [comment]
I noticed something. I don't know if this is the intended behavior, but the preview only shows if I'm on a tag without clients.

**Comment by bakkeby** [comment]
I suppose a call to raise the window is missing somewhere. Will have a look later or tomorrow.

**Comment by CSpencerND** [comment]
> I suppose a call to raise the window is missing somewhere. Will have a look later or tomorrow.

I don't know for sure if this was the right thing to do, but it works. 
```diff
 void showtagpreview(int tag, int x, int y)
 {
         Monitor *m = selmon;
         if (m->tagmap[tag])
         {
                 XSetWindowBackgroundPixmap(dpy, m->tagwin, m->tagmap[tag]);
                 XCopyArea(dpy, m->tagmap[tag], m->tagwin, drw->gc, 0, 0,
                           m->mw / scalepreview, m->mh / scalepreview, 0, 0);
                 XMoveWindow(dpy, m->tagwin, x, y);
                 XSync(dpy, False);
                 XMapWindow(dpy, m->tagwin);
+                XRaiseWindow(dpy, m->tagwin);
         }
         else
                 XUnmapWindow(dpy, m->tagwin);
 }

```

**Comment by bakkeby** [comment]
That looks like the right place to me.

**Comment by N-R-K** [comment]
Could just use `XMapRaised (3)` directly.

**Comment by CSpencerND** [comment]
> Could just use `XMapRaised (3)` directly.

This gave me compile errors

**Comment by bakkeby** [comment]
@CSpencerND that's two function calls to map and raise the window
```c
		XMapWindow(dpy, m->tagwin);
		XRaiseWindow(dpy, m->tagwin);
```
vs one function call that does both
```c
		XMapRaised(dpy, m->tagwin);
```

**Comment by CSpencerND** [comment]
Aaaah, ok cool.

**Comment by CSpencerND** [comment]
Hey, so I noticed that when clicking between tags, the snapshots get updated with the snapshot on the screen, so it creates a sort of "preview-ception". I was thinking, how to hide or remove the snapshot on the screen after the tag is clicked but before the new snapshot is created. If that even makes sense.

**Comment by N-R-K** [comment]
One possible way to deal with this could be getting rid of the preview "window" all together. Instead hacking into the cursor to show the preview.

One limitation of this approach is that cursors sizes above 255x255 seems to flicker badly.

I glanced over the patch sometime ago but didn't really look at how it worked. But it's probably a fair assumption that changing from a window to a cursor would be non-trivial amount of work.

Another alternative could be using the XComposite extension to grab the content below the preview window. But I think that's going to be even harder of a task.

**Comment by nakoo** [comment]
![2022-06-30-121757_1026x487_scrot](https://user-images.githubusercontent.com/4975021/176676187-c4145a40-e743-439b-bc14-cb542443c5f4.png)

Hi, I found out it doesn't work with barpadding patch. Can I know which part do I have to edit?

**Comment by bakkeby** [comment]
It should work just fine with barpadding. The position is calculated in patch/bar_tags.c - look for the `showtagpreview` call.

I'd be interested to know how you reproduce the above.

**Comment by nakoo** [comment]
> It should work just fine with barpadding. The position is calculated in patch/bar_tags.c - look for the `showtagpreview` call.
> 
> I'd be interested to know how you reproduce the above.

Yeah, you're right. I had to say first that I tried to use this patch in vanilla dwm.
https://dwm.suckless.org/patches/tag-previews/dwm-tag-preview-6.2.diff

It seems original patch isn't implemented this function yet. 
If you don't mind, can you update the original patch? 

Since heavy modification was involved during that time, I'm afraid that I can manage to fix this issue. Adding it to your patches repository helps me a lot.

**Comment by bakkeby** [comment]
Ah right, I was starting to suspect that you were referring to the original patch.

That patch has a static placement for the preview window and that is defined with this line in `updatepreview`:

```c
       m->tagwin = XCreateWindow(dpy, root, m->wx, m->by + bh, ...
```

In principle that should be fine for the barpadding patch as well.

I suspect that you are using the 6.2 patch for barpadding:
   - https://dwm.suckless.org/patches/barpadding/dwm-barpadding-6.2.diff

That one has a bug in it where in the `setup` function it sets the `sp` and `vp` variables _after_ the call to `updategeom` (which depends on the two variables to set the bar position).

Refer to this patch which moves the setting of those variables before the call to `updategeom`:
   - https://dwm.suckless.org/patches/barpadding/dwm-barpadding-20211020-a786211.diff

(that also gets rid of the redundant `updatebarpos(selmon);` call that was present in the original 6.2 patch)

**Comment by nakoo** [comment]
> 

![2022-07-01-123954_1137x801_scrot](https://user-images.githubusercontent.com/4975021/176896628-93c4ab05-b289-460d-89c2-8a666c917777.png)

Thank you so much. I can fix this issue by adding:

```diff
-               m->tagwin = XCreateWindow(dpy, root, m->wx, m->by + bh, m->mw / scalepreview, m->mh / scalepreview, 0,
+               m->tagwin = XCreateWindow(dpy, root, m->wx + sp, m->by + bh + vp + gappov / 2, m->mw / scalepreview, m->mh / scalepreview, 0,

```

I additionally added `gappov / 2` for incoporating vanitygaps.

**Comment by nakoo** [comment]
> Yes that looks good. Adding `vp` here should be unnecessary as `m->by` should include this (if the `vp` variable is set before the call to `updategeom` as outlined earlier).

I used [dwm-barpadding-20211020-a786211.diff](https://dwm.suckless.org/patches/barpadding/dwm-barpadding-20211020-a786211.diff), but without `vp`, it shows like this: 

![2022-07-01-130150_1034x689_scrot](https://user-images.githubusercontent.com/4975021/176900110-c2a68c60-7192-4e63-b430-c81be8d4e8a1.png)

I'm not sure it's because I used status2d patch, which moves related `drawbar` code to `drawstatusbar` function.

**Comment by bakkeby** [comment]
I had a look at that patch again, you are right about including the `vp` variable. I thought that it would add that in the `updatebarpos` function when setting `m->by` as as that would be the sensible thing to do, but instead it handles the difference in the `togglebar` function.

**Comment by bakkeby** [comment]
@nakoo just to show what I mean I think that the barpadding code would make more sense when using positional variables like `m->bx` and `m->bw`:
   - https://github.com/bakkeby/patches/blob/master/dwm/dwm-barpadding_new-6.3.diff

**Comment by nakoo** [comment]
> @nakoo just to show what I mean I think that the barpadding code would make more sense when using positional variables like `m->bx` and `m->bw`:
> 
> * https://github.com/bakkeby/patches/blob/master/dwm/dwm-barpadding_new-6.3.diff

Thank you so much. As beginner of C, dwm was hard to understand what's going on.

**Comment by SisyphusIsntHappy** [comment]
Hi, I'm happy that my suggestion was accepted. 

I have another suggestion related to this, what if we had an option to turn on and off the preview in the config.h ? 
I am not code but I guess since everything is modularised it should be fairly easy?

Regards

**Comment by bakkeby** [comment]
Shouldn't be particularly complicated to add. Could even make changes to use `scalepreview = 0` for this purpose.

You'd still have all the added dependencies etc. left in code though, and the [tag-previews](https://dwm.suckless.org/patches/tag-previews/) patch on the suckless repository does not offer a way to disable it. For dwm-flexipatch in particular you could just flip the one toggle to disable tag previews.

The latest patch also has a `previewbar` option, although implementation wise it seems to be doing the opposite of what it says that it does (or I am reading it wrong).
