### ISSUE TITLE
Add stackmfact patch

### ISSUE THREAD

**Issue by 766F6964** [bakkeby/dwm-flexipatch#183]
Is it possible to add support for the stackmfact patch? (https://dwm.suckless.org/patches/stackmfact/)
It essentially allows you to resize windows in the stack vertically.

**Comment by bakkeby** [comment]
I am not going to add the stackmfact patch as the feature it provides is restricted to the last client in the stack.

It is an old patch from 2013 that was later superseded by the [cfacts](https://dwm.suckless.org/patches/cfacts/) patch which allows for any client to be resized relative to other clients within the same area (master, stack or secondary stack).
