### ISSUE TITLE
ONLYQUITONEMPTY patch does not respect COOL_AUTOSTART

### ISSUE THREAD

**Issue by skrrt** [bakkeby/dwm-flexipatch#194]
Not sure if this is the right place to report this, but the first time I've noticed this behaviour was using Flexipatch rather than dwm patched from scratch. As such, I figured it might be worth starting here.

The ONLYQUITONEMPTY and COOL_AUTOSTART patches aren't exactly playing nice with each other at the moment. When both of these patches are enabled and some programs are started using the autostart array, ONLYQUITONEMPTY indeed will not shut down dwm entirely, but it will still kill every program started up via COOL_AUTOSTART before it reaches dwm itself and decides not to shut it down. A good way to test it, as I have it at the moment, is using a transparent terminal like st with the ALPHA patch and starting a compositor such as `picom` within the config for dwm.

I also notice that for whatever reason ONLYQUITONEMPTY breaks the SIGRESTART patch, since as soon as the former is invoked it is no longer possible to use MOD+Ctrl+Shift+Q to restart dwm along with any autostarted programs.

**Comment by skrrt** [comment]
Just tried out the new function you gave without XQueryTree and that seems to work perfectly with `quit_empty_window_count = 0` as one would expect. I guess that variable in general is a lot more intuitive now with this approach.

I have no complaints left whatsoever with this patch combination, so feel free to close this as you see fit.

**Comment by bakkeby** [comment]
Thanks for trying it out. I think I'll just include those changes as I like that better and I also find it more intuitive.

**Comment by bakkeby** [comment]
I'll mark this as closed, but feel free to reopen if you come across any issues.
