### ISSUE TITLE
add taglabels & underlinetags patch

### ISSUE THREAD

**Issue by wael444** [bakkeby/dwm-flexipatch#199]
https://dwm.suckless.org/patches/taglabels
https://dwm.suckless.org/patches/underlinetags/

**Comment by bakkeby** [comment]
You can have underline indicators for when a tag has clients. The underlinetags patch merely adds an underline on the selected tag(s), or alternatively all tags. What is the appeal for adding the underlinetags patch?

**Comment by bakkeby** [comment]
Looks like the author of the taglabels patch did not consider multi-monitor support.

**Comment by bakkeby** [comment]
I think the above should suffice, let me know if anything is amiss.
Remember to set `BAR_TAGS_PATCH` to 0 when enabling `BAR_TAGLABELS_PATCH` unless you want both for comparison :)

**Comment by wael444** [comment]
it works as intended. thanks for your time, sorry for getting back to you so late

> What is the appeal for adding the underlinetags patch?

uline { pad, stroke, voffset, all }

i had also found that activetagindicator didn't work well for me, as i preferred underlinetags.
