### ISSUE TITLE
Firefox does not fill the bottom part of the screen when in fullscreen

### ISSUE THREAD

**Issue by karimrir1** [bakkeby/dwm-flexipatch#200]
Hello there, This issue seems to be related to the bar height patch, Which I tried removing but no luck. I also tried all the fullscreen patches. I tried the fake one and the toggle able one.
Here's a screenshot of this happening
![image](https://user-images.githubusercontent.com/50053541/143556301-7cbfd29a-bdc2-4de5-9881-972784c3cc5c.png)
As you can see. The wallpaper is visible.
The patches that I am currently using are

1. Awesomebar
2. Powerline Tags
3. Systray
4. Window title and icon patch
5. Alpha patch
6. Color emoji and pango patch

**Comment by karimrir1** [comment]
This also seems to happen on games running on wine/proton

**Comment by wael444** [comment]
you said you fixed it?

**Comment by karimrir1** [comment]
> you said you fixed it?

Yes I did. Closing now

**Comment by bakkeby** [comment]
Out of interest what was the issue and how did you fix it?

**Comment by wael444** [comment]
from what i heard from him he said that the culprit was rounded corners patch.
