### ISSUE TITLE
add centretitle patch

### ISSUE THREAD

**Issue by wael444** [bakkeby/dwm-flexipatch#201]
centeredwindowname doesn't actuallly center the title, it only positions it in the middle of wintitle

https://dwm.suckless.org/patches/centretitle/ on the other hand actually centers in the middle of the whole bar.
though it is entirely optional and you can ignore it as i prefer it non-centered anyway.

**Comment by bakkeby** [comment]
I believe that I forgot to follow up on this one, sorry for the delay.

Yes I don't think that I would add that as a patch / option. It is trivial to do this via configuration if one would like this feature though.

In config.h somewhere above the `barrules` array add the following function:

```c
int
width_centered_wintitle(Bar *bar, BarArg *a)
{
	if (!selmon->sel)
		return 0;

	return TEXTW(selmon->sel->name);
}
```

then in the `barrules` config change the wintitle rule to use the new `width_centered_wintitle` function and change the bar alignment from none to center.

```diff
	#elif BAR_WINTITLE_PATCH
-	{ -1,        0,     BAR_ALIGN_NONE,   width_wintitle,          draw_wintitle,          click_wintitle,          "wintitle" },
+	{ -1,        0,     BAR_ALIGN_CENTER, width_centered_wintitle, draw_wintitle,          click_wintitle,          "wintitle" },
	#endif // BAR_TABGROUPS_PATCH | BAR_AWESOMEBAR_PATCH | BAR_FANCYBAR_PATCH | BAR_WINTITLE_PATCH
```

Compile and restart and you should now have a centered window title
![image](https://user-images.githubusercontent.com/1438008/150373472-bac590ef-a032-4a87-832f-71177ba04dd6.png)
