### ISSUE TITLE
/usr/bin/ld: dwm.o: undefined reference to symbol 'XRenderFindVisualForm

### ISSUE THREAD

**Issue by pauljamesharper** [bakkeby/dwm-flexipatch#202]
I am getting the above error. How can I troubleshoot it?

I am on Debian 11. 

`libxrender-dev is already the newest version (1:0.9.10-1).
libxrender-dev set to manually installed.
libxrender1 is already the newest version (1:0.9.10-1).
libxrender1 set to manually installed.`

The full error:
`cc -o dwm drw.o dwm.o util.o -L/usr/X11R6/lib -lX11 -lXinerama -lfontconfig -lXft         
/usr/bin/ld: dwm.o: undefined reference to symbol 'XRenderFindVisualFormat'
/usr/bin/ld: /lib/x86_64-linux-gnu/libXrender.so.1: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make: *** [Makefile:35: dwm] Error 1`

**Comment by pauljamesharper** [comment]
I found a solution. In the config.mk:

`# includes and libs
INCS = -I${X11INC} -I${FREETYPEINC}
LIBS = -L${X11LIB} -lX11 ${XINERAMALIBS} ${FREETYPELIBS} -lXrender`

Now it compiles on Debian 11.

**Comment by bakkeby** [comment]
Yes this is documented under #138
