### ISSUE TITLE
Bar's text array size not enough

### ISSUE THREAD

**Issue by Vinschers** [bakkeby/dwm-flexipatch#203]
When using status2d patch, the length of the status bar text may increase substantially, making the limit of 1024 characters defined in `rawstext` and `stext` not enough. This ends up truncating the status.

I am not sure if there is a way to use a dynamic allocation to fix this issue, but that would be ideal.

**Comment by bakkeby** [comment]
Well have you in practice ever exceeded 1024 characters for your status?

You can just double the values if need be. 1024 should be enough for most people I'd think.

Although dynamic allocation might be a nice to have it would not be something that you would get if you apply the status2d patch.

I find the whole status mechanism with having one long status string updated via the x root name to be suboptimal. Especially if you want click support as well.

**Comment by Vinschers** [comment]
Yeah, I was testing dwmblocks with 10+ modules and ran into this problem. But no worries, I'll increase the limit to 2048 in my build. Thank you.

**Comment by bakkeby** [comment]
Note that you'll also have to update dwmblocks in this respect.
