### ISSUE TITLE
switch focus in monocle mode

### ISSUE THREAD

**Issue by der-zonk** [bakkeby/dwm-flexipatch#214]
I'm using a couple patches including flextile.. when I switch to monocle mode, the window that gets in front is always the window that was created last, no matter in what position the client has in the stack.
And I can't switch to an other window, like if I have 3 windows open and Nr.2 is on top, I can not switch to Nr.1 or 3..
I tried focusdir, zoom, viewtoleft/right, rotatestack.. Is this behavior expected? And if yes, what's the point of monocle if you can't decide what client is on top of the stack?
I would expect the client in position 1 of the master stack to get the focus in monocle or even better the client that has focus at the time of layout switch..

**Comment by bakkeby** [comment]
This sounds like something I have already fixed... somewhere. I'll get back to you.

**Comment by der-zonk** [comment]
If upgrading fixes it I'm going to try that first. I'll get back here.

**Comment by bakkeby** [comment]
I couldn't replicate this now, so maybe I already fixed it in dwm-flexipatch? Let me know if upgrading fixed anything for you.

**Comment by der-zonk** [comment]
nah.. I pulled fresh yesterday, applied all the patches I want ( 2-3 more than last time), finalized, set up all my configs.. aaaand.. it's the same.. not even inplacerotate does anything in monocle mode.

**Comment by bakkeby** [comment]
I think most probably I must have been using rotatestack when trying to replicate this. The inplacerotate patch would not have made any difference if nmaster is 1, as then it would be trying to cycle through clients in the master area in which there is only one client. 

I'll see what I can do.

**Comment by bakkeby** [comment]
@der-zonk can you try with this function as a drop-in replacement for the existing one and see if this works better for you?

```c
static void
arrange_monocle(Monitor *m, int x, int y, int h, int w, int ih, int iv, int n, int an, int ai)
{
	int i, stackno, minstackno = 0xFFFFFF;
	Client *c, *s, *f = NULL;
	XEvent ev;
	XWindowChanges wc;

	for (i = 0, c = nexttiled(m->clients); c && i < (ai + an); c = nexttiled(c->next), i++) {
		if (i < ai)
			continue;

		for (stackno = 0, s = m->stack; s && s != c; s = s->snext, ++stackno);
		if (stackno < minstackno) {
			f = s;
			minstackno = stackno;
		}
	}

	if (!f)
		return;

	XMoveWindow(dpy, f->win, x, y);
	resize(f, x, y, w - (2 * f->bw), h - (2 * f->bw), 0);
	wc.stack_mode = Below;
	wc.sibling = f->win;

	for (i = 0, c = nexttiled(m->clients); c && i < (ai + an); c = nexttiled(c->next), i++) {
		if (i < ai)
			continue;

		if (c != f) {
			XConfigureWindow(dpy, c->win, CWSibling|CWStackMode, &wc);
			wc.sibling = c->win;
			XMoveWindow(dpy, c->win, x, y);
			resize(c, x, y, w - (2 * c->bw), h - (2 * c->bw), 0);
		}
	}

	while (XCheckMaskEvent(dpy, EnterWindowMask, &ev)); // skip any new EnterNotify events
}
```

**Comment by der-zonk** [comment]
If you tell me what I'm supposed to replace this with, I'd be glad to try it. :D
There is no monocle function in dwm.c, not in my build and not in the flexipatch build that I pulled last time.
At least nothing that can be found with /monocle.
I'm dumb so, help me out please.
There is
```
static void arrange(Monitor *m);
static void arrangemon(Monitor *m);
void
arrange(Monitor *m)
{
	if (m)
		showhide(m->stack);
	else for (m = mons; m; m = m->next)
		showhide(m->stack);
	if (m) {
		arrangemon(m);
		restack(m);
	} else for (m = mons; m; m = m->next)
		arrangemon(m);
}

void
arrangemon(Monitor *m)
{
	strncpy(m->ltsymbol, m->lt[m->sellt]->symbol, sizeof m->ltsymbol);
	if (m->lt[m->sellt]->arrange)
		m->lt[m->sellt]->arrange(m);
}

```

Is it "arrangemon"(ocle)? I'm playing guess here..

**Comment by der-zonk** [comment]
wait.. I've never heard the term drop-in replacement..but it seems like it means I can just "drop it in" without further configuration required from what I found online xD
Will test

**Comment by bakkeby** [comment]
I mean that you would replace the existing `arrange_monocle` function in `patch/layout_flextile-deluxe.c` with the above function.

**Comment by der-zonk** [comment]
Ok so with this the window that gets moved to the front is the one following the previously focused one in each direction, but the focus stays on the window with initial focus which forces one to set focus manually again to the new front window..

**Comment by bakkeby** [comment]
Yes I see, now when using `rotatestack` the previous window is always above the others.

I had a look again at the original function and comparing to the original monocle layout (which you can of course also enable) and they should both work the same - so I am not sure why you are having trouble with this.

By default when using the `focusstack` function what brings the focused window to the top is the call to the `restack` function so not entirely sure why it does not work for you.

So I had to have a closer look at your particular build and I see that you do not have a bar, which happens to be the reason why the monocle layout does not work properly for you. In dwm the bar window is used as a reference where floating windows are placed above the bar and tiled windows are placed below the bar.

Since you do not have a bar I was thinking of using the selected client as a reference, but that causes issues if you have floating windows as well, so the only feasible alternative I could think of was to use the last focused tiled client as a reference.

So roll back to the previous version of the `arrange_monocle` function (commit 4e7e747132c81845638774145bbc909310e3265e) and replace your existing `restack` function (in dwm.c) with this:

```c
void
restack(Monitor *m)
{
	Client *c, *f;
	XEvent ev;
	XWindowChanges wc;

	drawbar(m);
	if (!m->sel)
		return;
	if (m->sel->isfloating || !m->lt[m->sellt]->arrange)
		XRaiseWindow(dpy, m->sel->win);
	if (m->lt[m->sellt]->arrange) {
		wc.stack_mode = Below;
		for (f = m->stack; f && (f->isfloating || !ISVISIBLE(f)); f = f->snext); // find first tiled stack client
		if (f) {
			wc.sibling = f->win;
			for (c = m->stack; c; c = c->snext) {
				if (!c->isfloating && ISVISIBLE(c) && c != f) {
					XConfigureWindow(dpy, c->win, CWSibling|CWStackMode, &wc);
					wc.sibling = c->win;
				}
			}
		}
	}
	XSync(dpy, False);
	while (XCheckMaskEvent(dpy, EnterWindowMask, &ev));
}
```

**Comment by der-zonk** [comment]
Oohh... now I can also use focus dir, that's so nice.. Is that a too edgy case for building it into flexipatch?
Thx by the way for your great work, will buy you another beer when I get money.

**Comment by bakkeby** [comment]
It is quite an edge case yes.

Adding this to dwm-flexipatch might look like this:

```diff
diff --git a/dwm.c b/dwm.c
index c27f65c..3e52255 100644
--- a/dwm.c
+++ b/dwm.c
@@ -3000,7 +3000,7 @@ resizemouse(const Arg *arg)
 void
 restack(Monitor *m)
 {
-       Client *c;
+       Client *c, *f = NULL;
        XEvent ev;
        XWindowChanges wc;
        #if WARP_PATCH && FLEXTILE_DELUXE_LAYOUT
@@ -3015,11 +3015,17 @@ restack(Monitor *m)
                return;
        if (m->sel->isfloating || !m->lt[m->sellt]->arrange)
                XRaiseWindow(dpy, m->sel->win);
-       if (m->lt[m->sellt]->arrange && m->bar) {
+       if (m->lt[m->sellt]->arrange) {
                wc.stack_mode = Below;
-               wc.sibling = m->bar->win;
+               if (m->bar) {
+                       wc.sibling = m->bar->win;
+               } else {
+                       for (f = m->stack; f && (f->isfloating || !ISVISIBLE(f)); f = f->snext); // find first tiled stack client
+                       if (f)
+                               wc.sibling = f->win;
+               }
                for (c = m->stack; c; c = c->snext)
-                       if (!c->isfloating && ISVISIBLE(c)) {
+                       if (!c->isfloating && ISVISIBLE(c) && c != f) {
                                XConfigureWindow(dpy, c->win, CWSibling|CWStackMode, &wc);
                                wc.sibling = c->win;
                        }
```

I'll consider it.
