### ISSUE TITLE
Tag bar clicks offset by padding

### ISSUE THREAD

**Issue by UtkarshVerma** [bakkeby/dwm-flexipatch#215]
The tag bar has a subtle bug where the clicks are handled incorrectly.
The expected behaviour would be that clicking in the area within padding around the tag should switch to the tag.
However, this isn't the case as demonstrated in the video below:

https://user-images.githubusercontent.com/31820255/149568524-78c95d83-896d-4f99-9194-e9698ae98971.mp4

**Comment by UtkarshVerma** [comment]
Bug seems to arise from this line: https://github.com/bakkeby/dwm-flexipatch/blob/master/patch/bar_tags.c#L73

Setting `x = 0` seems to be the fix for my case, but I don't know if it will be the general solution.

**Comment by bakkeby** [comment]
I think that should probably be x = a->x (as in the draw function).

**Comment by bakkeby** [comment]
Ah no, a->x represents the click position relative to the module position, setting it to 0 should be the right solution.

**Comment by UtkarshVerma** [comment]
Thanks.
