### ISSUE TITLE
Wintitle is not padded appropriately when text-width is slightly less than wintitle width

### ISSUE THREAD

**Issue by UtkarshVerma** [bakkeby/dwm-flexipatch#216]
The window title is padded appropriately when ellipsed. However, when it isn't ellipsed the text touches the boundary.

![image](https://user-images.githubusercontent.com/31820255/149583848-82e9f4e1-53e9-4313-aa58-4a9cdfe199e2.png)

![image](https://user-images.githubusercontent.com/31820255/149583974-e46d11e1-3850-44a0-b986-5abc73503231.png)

Ideally, an `lrpad / 2` padding should be at the end of wintitle.

An easy way to test/debug this is open a terminal and update its title using:
```sh
echo -ne "\033]0;This is a really long title-----------------------------\007"
```

**Comment by bakkeby** [comment]
This is specifically related to how the winicon patch handles the padding for the title text.

This seems to work but I am not entirely convinced that it is the best way to do it.

```diff
diff --git a/patch/bar_wintitle.c b/patch/bar_wintitle.c
index d2241d2..c0b6de1 100644
--- a/patch/bar_wintitle.c
+++ b/patch/bar_wintitle.c
@@ -26,18 +26,26 @@ draw_wintitle(Bar *bar, BarArg *a)
                return 0;
        }

+       #if BAR_WINICON_PATCH
+       int ipad = c->icon ? c->icon->width + ICONSPACING : 0;
+       #endif // BAR_WINICON_PATCH
        drw_setscheme(drw, scheme[m == selmon ? SchemeTitleSel : SchemeTitleNorm]);
        #if BAR_IGNORE_XFT_ERRORS_WHEN_DRAWING_TEXT_PATCH
        XSetErrorHandler(xerrordummy);
        #endif // BAR_IGNORE_XFT_ERRORS_WHEN_DRAWING_TEXT_PATCH
-       #if BAR_CENTEREDWINDOWNAME_PATCH
+       #if BAR_WINICON_PATCH && BAR_CENTEREDWINDOWNAME_PATCH
+       if (TEXTW(c->name) + ipad < w)
+               pad = (w - TEXTW(c->name) - ipad + lrpad) / 2;
+       #elif BAR_CENTEREDWINDOWNAME_PATCH
        if (TEXTW(c->name) < w)
                pad = (w - TEXTW(c->name) + lrpad) / 2;
        #endif // BAR_CENTEREDWINDOWNAME_PATCH

        #if BAR_WINICON_PATCH
-       drw_text(drw, x, a->y, w, a->h, pad + (c->icon ? c->icon->width + ICONSPACING : 0), c->name, 0, False);
-       if (c->icon)
+       XSetForeground(drw->dpy, drw->gc, drw->scheme[ColBg].pixel);
+       XFillRectangle(drw->dpy, drw->drawable, drw->gc, x, a->y, w, a->h);
+       drw_text(drw, x + ipad, a->y, w - ipad - pad, a->h, pad, c->name, 0, False);
+       if (ipad)
                drw_img(drw, x + pad, a->y + (a->h - c->icon->height) / 2, c->icon, tmpicon);
        #else
        drw_text(drw, x, a->y, w, a->h, pad, c->name, 0, False);
```

I'll need to have a play around some more.

**Comment by bakkeby** [comment]
The above is what I ended up with.

**Comment by UtkarshVerma** [comment]
Thanks, I'll test these out and update here.

**Comment by UtkarshVerma** [comment]
Thanks a lot for your work. I tested on my config and it works as it should.
However, there's a minor detail which I think could be addressed. When the title's too long, an ellipsis ("... ") is added. As we are already padding the title bar, I guess the trailing space could be removed from the ellipsis, as it makes the title-bar look asymmetric.

![image](https://user-images.githubusercontent.com/31820255/149999080-9829598d-abd6-43d5-b7f0-de4c24eb5b47.png)

**Comment by bakkeby** [comment]
Yes this is a bit of an odd one and has to do with how dwm adds the ellipsis in drw_text in drw.c. I believe that you should find this behaviour in a bare dwm.

Testing with hyphens I have found that it goes back five characters then adding three punctuation marks. Perhaps it has something to do with varying character widths in non-monospaced fonts, not sure. 

I'll have another look to try and work out why / how it ends up calculating position of the ellipsis so far back.

**Comment by bakkeby** [comment]
You can try with the above. Seems to work better.

**Comment by UtkarshVerma** [comment]
Thanks a lot for the fix, it is behaving as expected now.
