### ISSUE TITLE
Incorporate single tagset patch

### ISSUE THREAD

**Issue by AnonymusRaccoon** [bakkeby/dwm-flexipatch#218]
Hello,

I would like to use the [single tagset](https://dwm.suckless.org/patches/single_tagset/) patch, but it introduces many changes where I am not really sure how others patches interact with it. It changes the ISVISIBLE to take a monitor as parameter, moves clients from a field in monitors to a common global, etc. Could you please incorporate this patch into dwm-flexipatch?

Thanks

**Comment by bakkeby** [comment]
The single tagset patch conflicts with the vast majority of patches out there that concerns window management so it is not feasible to integrate into dwm-flexipatch. You may also want to refer to the answer in #150.

**Comment by AnonymusRaccoon** [comment]
Oh sorry, I didn't see it. Thanks for the anwser.
