### ISSUE TITLE
Update patches which updated for dwm 6.3

### ISSUE THREAD

**Issue by NextAlone** [bakkeby/dwm-flexipatch#220]

**Comment by bakkeby** [comment]
dwm-flexipatch is already on 6.3 and thus all related patches as well. Do you have any example patch that is not updated, or do I not understand what you are after?

**Comment by NextAlone** [comment]
> dwm-flexipatch is already on 6.3 and thus all related patches as well. Do you have any example patch that is not updated, or do I not understand what you are after?

Sorry for this, cuz i dont notice the related commit to patches. thanks for your work.

**Comment by bakkeby** [comment]
You are right about the commits, this is because dwm-flexipatch has been kept up-to-date with the latest from the dwm master branch rather than staying strictly on 6.2.
