### ISSUE TITLE
dwm.c:2021 lockfullscreen undeclared

### ISSUE THREAD

**Issue by andbenn** [bakkeby/dwm-flexipatch#221]
Did a fresh clone today, then a make.

...
```
dwm.c: In function ‘focusstack’:
dwm.c:2021:59: error: ‘lockfullscreen’ undeclared (first use in this function); did you mean ‘setfullscreen’?
 2021 |         if (!selmon->sel || (selmon->sel->isfullscreen && lockfullscreen))
      |                                                           ^~~~~~~~~~~~~~
      |                                                           setfullscreen
dwm.c:2021:59: note: each undeclared identifier is reported only once for each function it appears in
make: *** [Makefile:24: dwm.o] Error 1

```

**Comment by bakkeby** [comment]
Are you sure that you didn't just do a git pull?

Do you have this line in your config.h file?

https://github.com/bakkeby/dwm-flexipatch/blob/4366f72390545fdc7ade62f4b002b5471913d0e5/config.def.h#L570

**Comment by andbenn** [comment]
Good catch.  I might have done a pull looking at my shell history.  Now in a new fresh directory, a new clone and it's building.  I'm back in business.  Thanks - oh, and this project is waaaaayyyyy cool - thanks for pulling it together.
