### ISSUE TITLE
patch request: Per-window keyboard layout

### ISSUE THREAD

**Issue by krackout** [bakkeby/dwm-flexipatch#224]
Can you add Per-window keyboard layout please?
[https://dwm.suckless.org/patches/pwkl](url)

It's very helpful for people who use different keyboard layouts. It's quite common to need to write in different languages/layouts on different windows/apps.

**Comment by bakkeby** [comment]
From a quick look this patch is small and seems like it should be possible to integrate. Is this in any way functionally different from the xkb patch?

**Comment by krackout** [comment]
To be honest I haven't ever noticed `xkb` patch. If anybody has tried both could enlighten us perhaps. I'll try to find some time to make a dwm build with it instead of `pwkl` to test.

**Comment by krackout** [comment]
I've compiled dwm with xkb patch. It works as pwkl, plus it includes functionality to show the current keyboard layout (which can be different per window) in the status bar. I had to make a separate program for this feature, using pwkl. So xkb it is!
Thank you very much for the info and all the work on flexipatch, I'll close the issue.
