### ISSUE TITLE
patch request

### ISSUE THREAD

**Issue by kronikpillow** [bakkeby/dwm-flexipatch#23]
https://dwm.suckless.org/patches/statuscmd/

**Comment by bakkeby** [comment]
I have seen this patch. I haven't taken this yet as it's going to conflict with a few patches, systray and barpadding at least. I'll have a look at some point.

**Comment by kronikpillow** [comment]
yes i tried applying it manually, it's conflicting with systray, althou on luke's dwm build it seems to be working with bar padding ... its a good patch that allows you to actually have a clickable systray

**Comment by bakkeby** [comment]
Also conflicts with extrabar and awesomebar.

**Comment by bakkeby** [comment]
I think it works. Have a go.

**Comment by bakkeby** [comment]
@kronikpillow in other news I've just been sent a multiple scratchpads patch, something you've asked about before. I'll add it at the earliest convenience.

**Comment by kronikpillow** [comment]
thank you bakkeby :) I have noticed, sorry for the slow replies lately, I'v been busy in RL :) In my spare time I'v been trying to port this patch to flexipatch [statuscdm patch with dwmblocks](https://gist.github.com/danbyl/54f7c1d57fc6507242a95b71c3d8fdea) which allows a clickable dwmblocks statusbar, but so far I have been unsuccessful :-/

**Comment by bakkeby** [comment]
I'm assuming the idea would be to use this in combination with https://github.com/torrinfail/dwmblocks

**Comment by kronikpillow** [comment]
yes, dwmblocks with that patch on top of dmwblocks and dwm, allows a user to have a fully functional clickable statusbar that can use i3block modules in it

**Comment by kronikpillow** [comment]
you can see a fully functional preview of the patch by installing [LukeSmithxyz dwm](https://github.com/LukeSmithxyz/dwm) & [LukeSmithxyz dwmblocks](https://github.com/LukeSmithxyz/dwmblocks) ... but you would have to put his [statusbar scripts](https://github.com/LukeSmithxyz/voidrice/tree/master/.local/bin/statusbar) to test it out :) ... it's just a example thou, I find it very useful, and I do use dwmblocks myself :)

**Comment by kronikpillow** [comment]
![pic-full-200430-2013-25](https://user-images.githubusercontent.com/48420193/80745135-1e318e80-8b20-11ea-92c6-34b3c3492573.png)
![pic-full-200430-2013-29](https://user-images.githubusercontent.com/48420193/80745137-1eca2500-8b20-11ea-8585-2a9b3ed5dafa.png)
![pic-full-200430-2013-34](https://user-images.githubusercontent.com/48420193/80745138-1f62bb80-8b20-11ea-9749-b4eb4a68f57a.png)
![pic-full-200430-2013-52](https://user-images.githubusercontent.com/48420193/80745140-1ffb5200-8b20-11ea-8eb5-ce549cd84184.png)

or some examples like this, when I click the date module, it gives me a calcurse calendar notification with appointments, when I click on the email module it actually opens neomutt etc

**Comment by kronikpillow** [comment]
maybe a dwmblocks flexipatch? and an option in dmw-flexipatch that you can use both in conjunction with each other :dagger: then, we could have a vanitygaps + multiple scratchpad + dwmblocks full functionality from i3 with gaps, statusbar and i3block modules, and scratchpad :D

**Comment by kronikpillow** [comment]
the submited patch is a patch both for dwm and dwmblocks, plus there are additional dwmblocks patches like one that removes icons from the modules.h and allows a user to use icons in the scripts instead, etc etc etc, and I'm sure you could think of many other things you could do with that statusbar, it's lightweight, and fast, my favorite option regarding statusbars in dwm

**Comment by bakkeby** [comment]
I have added the patch now, but I couldn't quite get the actions to trigger when I click on the relevant text in the status bar - wondering if it might be something the patch diff is missing.

Since you have it working on your system could you give it a go to see if it works for you?

**Comment by kronikpillow** [comment]
I dunno what to say except thank you very much :) I will test it out now, and give you more feedback and possibly some suggestions

**Comment by kronikpillow** [comment]
works nicely :) but if you compare the original patch, the original patch removes 

```
/* commands spawned when clicking statusbar, the mouse button pressed is exported as BUTTON */
static const char *statuscmds[] = { "notify-send Mouse$BUTTON" };
static char *statuscmd[] = { "/bin/sh", "-c", NULL, NULL };
```

```
static int statuscmdn;
static int lastbutton;
```

from statuscmd because the button functions are bound in the statusbar scripts

**Comment by kronikpillow** [comment]
also another suggestion

IF DWMBLOCKS & AUTOSTART
autostart
`	ret = system("killall -q dwmblocks; dwmblocks &");`

**Comment by bakkeby** [comment]
Yes you are right, those variables, as well as the additional code in `spawn`, are redundant when dwmblocks is enabled. Removed them.

As for the latter, that sounds more like something you may want to put in the autostart.sh script (if you use that). It doesn't sound like a good idea to hardcode something like that into a patch (the executable may go by a different name, or may not necessarily be in the path).

**Comment by kronikpillow** [comment]
true, I still hardcoded it :D :) 

anyways i think you missed static const char statusexport[] = "export BUTTON=-;"; from statuscmd.c to remove it from dwmblocks+statuscmd patch

**Comment by kronikpillow** [comment]
the updated scratchpad patch is missing some examples of how to setup scratchpad rules ... example

`	{ NULL,       NULL,       "spterm",   NULL,         SPTAG(0),    1,           1,           1,          0,         -1 },
	{ NULL,       NULL,       "spcalc",   NULL,         SPTAG(1),    0,           1,           1,          0,         -1 },
`

**Comment by kronikpillow** [comment]
another suggestion for swallow patch: [option to not swallow floating windows](https://github.com/LukeSmithxyz/dwm/commit/8f4d5e03d379527d87d3a6d844f0f39e231d73f3)

**Comment by bakkeby** [comment]
> anyways i think you missed static const char statusexport[] = "export BUTTON=-;"; from statuscmd.c to remove it from dwmblocks+statuscmd patch

You are right, fixed that.

> the updated scratchpad patch is missing some examples of how to setup scratchpad rules ... example

There is an example when you don't have any other patches, ref. [config.def.h#L433](https://github.com/bakkeby/dwm-flexipatch/blob/master/config.def.h#L433-L437). I have no plans for adding such an example for every possible rules combination patch :)

I may look at different ways to set rules so that I can add more patches, e.g. floatrules.

> another suggestion for swallow patch: option to not swallow floating windows

Yeees, at first I thought I got it, but thinking about it I find that it doesn't make much sense. In order for a window to be floating you have already set up a rule to mark that client as `isfloating`, so if you don't want that client to be swallowed then you'd also just set `noswallow` to 1. Anything I'm missing here?

Another thought, if your terminal window is floating - would you expect to swallow a floating window or not?

**Comment by kronikpillow** [comment]
depends on what is in the terminal, but you are probably right :)

**Comment by kronikpillow** [comment]
hey @bakkeby what happened with the dwmblocks patch? it got removed ?

**Comment by bakkeby** [comment]
No it's still there.

**Comment by kronikpillow** [comment]
yeah I figgured it out after I posted the message :D needed more coffee :D :) 

I see you made it compatible with statuspadding and awesomebar patch, can you make it compatible with systray as well ? :)

**Comment by bakkeby** [comment]
It should already be compatible with systray.

**Comment by kronikpillow** [comment]
nice!

**Comment by bakkeby** [comment]
I'll just mark this as closed now :)

**Comment by serhanekmekci** [comment]
Making bar-padding and statusmcd compatible is fairly easy.

Check: https://github.com/LukeSmithxyz/dwmblocks/issues/7
