### ISSUE TITLE
How to use xrdb terminal colors globally for configuring dwm?

### ISSUE THREAD

**Issue by UtkarshVerma** [bakkeby/dwm-flexipatch#234]
I was testing pywal and noticed how I could have dwm dynamically themed if it just fetches the terminal colors from `xrdb`. I found a hacky way to do this by having the following  in `config.h`:

```c
#if XRDB_PATCH && XRDB_TERMCOLORS_PATCH
// Monokai palette
static char termcol0[]  = "#333333"; /* black   */
static char termcol1[]  = "#f92672"; /* red     */
static char termcol2[]  = "#a6e22e"; /* green   */
static char termcol3[]  = "#e2e22e"; /* yellow  */
static char termcol4[]  = "#819aff"; /* blue    */
static char termcol5[]  = "#ae81ff"; /* magenta */
static char termcol6[]  = "#66d9ef"; /* cyan    */
static char termcol7[]  = "#f8f8f2"; /* white   */
static char termcol8[]  = "#666666"; /* black   */
static char termcol9[]  = "#f92672"; /* red     */
static char termcol10[] = "#a6e22e"; /* green   */
static char termcol11[] = "#e2e22e"; /* yellow  */
static char termcol12[] = "#819aff"; /* blue    */
static char termcol13[] = "#ae81ff"; /* magenta */
static char termcol14[] = "#66d9ef"; /* cyan    */
static char termcol15[] = "#f8f8f2"; /* white   */
static char *termcolor[] = {
	termcol0, termcol1, termcol2, termcol3, termcol4, termcol5, termcol6, termcol7,
	termcol8, termcol9, termcol10, termcol11, termcol12, termcol13, termcol14, termcol15,
};
#endif
```

and I then have the following in `xrdb.c`:
```c
				#if XRDB_PATCH && XRDB_TERMCOLORS_PATCH
				XRDB_LOAD_COLOR("color0", termcol0);
				XRDB_LOAD_COLOR("color1", termcol1);
				XRDB_LOAD_COLOR("color2", termcol2);
				XRDB_LOAD_COLOR("color3", termcol3);
				XRDB_LOAD_COLOR("color4", termcol4);
				XRDB_LOAD_COLOR("color5", termcol5);
				XRDB_LOAD_COLOR("color6", termcol6);
				XRDB_LOAD_COLOR("color7", termcol7);
				XRDB_LOAD_COLOR("color8", termcol8);
				XRDB_LOAD_COLOR("color9", termcol9);
				XRDB_LOAD_COLOR("color10", termcol10);
				XRDB_LOAD_COLOR("color11", termcol11);
				XRDB_LOAD_COLOR("color12", termcol12);
				XRDB_LOAD_COLOR("color13", termcol13);
				XRDB_LOAD_COLOR("color14", termcol14);
				XRDB_LOAD_COLOR("color15", termcol15);
				#endif
```

I then define the `colors` variable directly using terminal colors.
```
	[SchemeNorm]         = { termcol7,		   termcol0,      	 termcol2,      	   termcol2 },
```

This works well for me till now but I feel this is somewhat hacky and it would be hard to easily disable/enable this feature using macros. Could you please suggest me on some improvements regarding this?

**Comment by bakkeby** [comment]
I suppose this might be similar to the [vtcolors](https://dwm.suckless.org/patches/vtcolors/) patch, but I kind of doubt pywal updates that.

I think your approach is fine as-is. 

You could also have done something like:
```c
                XRDB_LOAD_COLOR("color7", normfgcolor);
                XRDB_LOAD_COLOR("color10", normbgcolor);
                XRDB_LOAD_COLOR("color2", normbordercolor);
```

which means that you wouldn't have to change the colour scheme references and it would make it easier to enable/disable this using macros. On the other hand it may be less intuitive if you want to swap colours around (which hopefully should not be the case).

I can see this working OK-ish for pywal generated colour schemes based on an image, but it will probably be a hit or miss for predefined colour schemes as there is generally no clear pattern to them.

**Comment by UtkarshVerma** [comment]
The problem with `XRDB_LOAD_COLOR` would be that I would need to modify the `xrdb.c` file, which will lead to conflicts in the future when I pull from your project.

I think, like `vtcolors`, this will be a cool addition as a patch. I'll keep this issue open until we, or someone else, figures how to do this in a way which builds upon the current architecture of `dwm-flexipatch`.

**Comment by bakkeby** [comment]
I believe you can also configure pywal to output custom xresources that is application specific, never looked into it though.

**Comment by UtkarshVerma** [comment]
Yeah, I found out that we can use [User Template Files](https://github.com/dylanaraps/pywal/wiki/User-Template-Files). Thanks for helping out.
