### ISSUE TITLE
fewer tags causes out of range crash

### ISSUE THREAD

**Issue by rteats** [bakkeby/dwm-flexipatch#236]
I reduced the amount of tags by decreasing the number of `NUMTAGS` to `4` in `dwm.c` and editing the `config.h` file like so, while following the commented instructions:
```c
static char *tagicons[][NUMTAGS] = {
        [DEFAULT_TAGS]        = { "dev", "web", "art", "aud" },
        /* [DEFAULT_TAGS]        = { "1", "2", "3", "4", "5", "6", "7", "8", "9" }, */
        [ALTERNATIVE_TAGS]    = { "A", "B", "C", "D", "E", "F", "G", "H", "I" },
        [ALT_TAGS_DECORATION] = { "<1>", "<2>", "<3>", "<4>", "<5>", "<6>", "<7>", "<8>", "<9>" },
};
```

The following problem occurs: if I switch to the tags 5-9 in any way then dwm would crash. I have a one monitor setup. No patches related to tags are applied. To my mind I also should change the tag switching keybindings on the bottom of `keys[]` array in `config.h`. How to approach this problem?

**Comment by bakkeby** [comment]
What is it that you are actually wanting to achieve, to only have 4 tags?

If so then yes you should also get rid of the keybindings that refer to tag 5 and above.

https://github.com/bakkeby/dwm-flexipatch/blob/96820b2d51b7e1bca5ccdd9ce289e9fd278aa767/config.def.h#L1201-L1209

More so for the `ALTERNATIVE_TAGS` and `ALT_TAGS_DECORATION` you should also reduce these to only have values for four tags.

You may find it more convenient to only show four tags and have the rest as spares should you need them (see the [hide vacant tags](https://dwm.suckless.org/patches/hide_vacant_tags/) patch).

To do so within dwm-flexipatch you would just leave NUMTAGS as 9 and have empty strings as the default tags.

```c
        [DEFAULT_TAGS]        = { "dev", "web", "art", "aud", "", "", "", "", "" },
```

**Comment by rteats** [comment]
That _almost_ solves the issue, but what I'm trying to achieve is a) yes, only 4 tags and b) being able to cycle through those tags using `FOCUSADJACENTTAG` patch, where you can't really limit the amount of tags you're able to cycle through only by editing the keybindings.

**Comment by bakkeby** [comment]
The `FOCUSADJACENTTAG` patch is not a problem in this respect. I believe the issue is the `SCRATCHPADS_PATCH` which messes with `TAGMASK`. In hindsight the named scratchpads patch is a better implementation.

**Comment by rteats** [comment]
Yep, that works like a charm, thank you!
