### ISSUE TITLE
Please update winicon patch

### ISSUE THREAD

**Issue by AdamYuan** [bakkeby/dwm-flexipatch#238]
Hi! I'm the author of winicon patch and I'm glad that you put my patch into the collection.
I find the winicon patch in your repository is still mainly in its early version, which uses XImage and slow CPU-side blending.

My new version (v2.1, https://github.com/AdamYuan/dwm-winicon/releases/tag/6.3-v2.1) has already switched to the XRenderPicture+XRenderComposite approach (on most machines it uses GPU as backend) and according to my test it is about 3 times faster on rendering.
As for icon creation, the new version directly uses XRender's bilinear filter (also GPU powered) instead of imlib2 under some conditions, leading to a performance boost in most circumstances.

Please update the patch for better performance :D

**Comment by bakkeby** [comment]
I have upgraded the patch now, thanks again for your great work.
