### ISSUE TITLE
Systray + holdbar patch bug

### ISSUE THREAD

**Issue by Vinschers** [bakkeby/dwm-flexipatch#239]
When you have the holdbar and systray patches both enabled, the systray won't disappear when releasing the HOLDKEY.

**Comment by Vinschers** [comment]
Thanks, that solved it!

I am not sure if this is also an issue, but when I bind HOLDKEY to a modkey, like super key, the dwmblocks' clicks stop working. I believe that dwm misses the click because the Modkey is being pressed. This also affects some systrays, but not all (flameshot works fine, but discord's systray won't register the click).

**Comment by bakkeby** [comment]
Yes I believe that would be because you are doing Super+left click instead of left click.

https://github.com/bakkeby/dwm-flexipatch/blob/da5e69c4a7b322683f70f2677309017650c0c79d/config.def.h#L1261-L1263

Try duplicating those, but instead of having 0 as the event mask use Mod4Mask. See if that makes mouse clicks register when holding down the super key.

**Comment by Vinschers** [comment]
Thanks, the bar does register the clicks correctly now, but the discord's systray still won't work. Is there anything that can be done on the dwm's scope to "clean" the modmask from the click event before the handler on the systray triggers? From what I know, even if the `state` field in the `XButtonPressedEvent` is changed, that applies only inside dwm and the systray wouldn't have a different behavior.

**Comment by bakkeby** [comment]
No I don't think there is much that can be done in this scenario.

Technically each systray icon is a separate window, and the discord icon/window is controlled by discord. 

So when you click on that icon the mouse click event goes straight from the X server to the window itself and the handling is application specific (hence the menus and everything are often different from icon to icon).

The "systray" is merely a simple window and when systay icons/clients/windows register those windows are reparented into the systray window. Beyond positioning those icons/windows the systray does not have much control. 

While it is possible to use the primary modifier key (e.g. super) as the hold key for this patch, and it works rather well mind you, I have found that it is more distracting than practical - this will become more apparent when you start to notice the bar flickering in and out of view when you are using basic keybindings to move around and whatnot. On the other hand using a dedicated key as the hold key is fine provided that you actually have a key to spare on your keyboard.
