### ISSUE TITLE
[Question]: Will there be a surf-flexipatch?

### ISSUE THREAD

**Issue by Moncheeta** [bakkeby/dwm-flexipatch#241]
I'm just wondering because it would make patching the surf web browser easier.

**Comment by bakkeby** [comment]
I was considering this a few years ago, but a lot of the patches were merely configuration so I didn't find much merit in it.

**Comment by nhkintact** [comment]
@bakkeby i'm assuming this is due to the fact that Surf isn't very well-maintained or modified for the modern web?

**Comment by bakkeby** [comment]
It was more that there were not that many patches for surf, and the majority of those merely tinkered with configuration. There are clearly more patches now that change the actual code of surf, so perhaps there may be some merit to a flexipatch version.

There is of course the time, effort, commitment and maintenance to take into account as well for something like this, but for surf it is probably not that big a deal.

I like the idea of surf, but I consider it more of a toy project. If you are remotely concerned about memory usage and has the need to open more than one web page at the time then there are better solutions.

**Comment by bakkeby** [comment]
@nhkintact right so _most_ of the patches for surf are between 10 to 15 years old, and a lot of them are also for older webkit versions with deprecations everywhere. It is quite a mess to be honest and a lot more challenging to get started compared to e.g. dwm when it comes to patching.

I started a flexipatch build here: https://github.com/bakkeby/surf-flexipatch

I have sanity tested the individual patches along the way, but there may very well be bugs or issues that I have missed.
