### ISSUE TITLE
remember tags patch

### ISSUE THREAD

**Issue by wael444** [bakkeby/dwm-flexipatch#245]
https://codeberg.org/explosion-mental/Dwm/src/branch/main/Patches/dwm-6.0-remember-tags.diff

this is especially useful when trying to hot reload dwm.

**Comment by bakkeby** [comment]
Yes, but it is also a bit uninspired I guess. I use something similar to have seamless restarts (order of clients, what layout is used where, nmaster, is the client floating etc.).

**Comment by wael444** [comment]
> Yes, but it is also a bit uninspired I guess. I use something similar to have seamless restarts (order of clients, what layout is used where, nmaster, is the client floating etc.).

What is it?

**Comment by bakkeby** [comment]
Just implementation. I use this in my dawn and dusk builds. This is far into the bloat side of course and I don't have any standalone patch to refer to.

**Comment by bakkeby** [comment]
I ported the seamless restart feature from my other build into dwm-flexipatch, should cover the remembering of client tags and more. Going to mark this as closed, but do let me know if you run into any bugs or issues.

**Comment by wael444** [comment]
thank you so much for porting this into `dwm-flexipatch`, but i do not use that project as i like to suffer with manual patching,

is it okay if you make this into a seperate patches in your repository [patches/](https://github.com/bakkeby/patches) ?

**Comment by bakkeby** [comment]
To be honest it wouldn't make that much sense to release this as a standalone patch due to the limited features that are present in a bare dwm. I suspect that it would just make it more complicated to integrate other patches.

The https://lists.suckless.org/hackers/2205/18344.html patch would be less invasive in this context.

**Comment by wael444** [comment]
>  https://lists.suckless.org/hackers/2205/18344.html


thanks! will try.
