### ISSUE TITLE
systray not shown on other monitors

### ISSUE THREAD

**Issue by UtkarshVerma** [bakkeby/dwm-flexipatch#247]
The patch https://dwm.suckless.org/patches/systray mentions that the systray should follow the current monitor, but it is only shown on one monitor for me all the time, although the status works as expected.

**Comment by bakkeby** [comment]
Yes this is because the `monitor` value for the bar rule is set to 0, that would be the first value here:

https://github.com/bakkeby/dwm-flexipatch/blob/49fc922f0df673527d5779ce5cafa1f51832cdcc/config.def.h#L500

You can set this to `'A'` to make the systray follow the active monitor.

**Comment by UtkarshVerma** [comment]
Thanks for the quick response. It works now!
