### ISSUE TITLE
patch request moveresize

### ISSUE THREAD

**Issue by axpira** [bakkeby/dwm-flexipatch#25]
Please include the https://dwm.suckless.org/patches/moveresize/ patch

Thanks

**Comment by bakkeby** [comment]
Yes that was fun. The instructions on that page is totally misleading and is not compatible with any of the patches listed :D 

I think I may need to update that so that others don't waste time with it. Also you may want to have a look at the `exresize` patch.

**Comment by axpira** [comment]
I'm using de exresize but how can I move window like moveresize? 
I want to move windows in pixels

**Comment by bakkeby** [comment]
Ah yes, you are right. I was thinking of explace which does the same as the moveplace patch (actually moveplace was lifted from explace). I added moveplace as well now merely for completeness.

Just to confirm I have added the moveresize patch now.
