### ISSUE TITLE
Gaps appear even when off

### ISSUE THREAD

**Issue by par4m** [bakkeby/dwm-flexipatch#257]
Haven't included any gaps patch in my build for flexipatch but still very small outer and inner gaps appear not sure why
![image](https://user-images.githubusercontent.com/68808783/171784660-189ac086-e619-4bc5-9843-0550df2f2f2c.png)

[Even changing resizehints to 0 or 1 doesn't do anything](https://www.reddit.com/r/suckless/comments/h7gtbd/comment/ful0dp7/?utm_source=share&utm_medium=web2x&context=3)

**Comment by bakkeby** [comment]
From the screenshot it looks like it might be the window border that is fully transparent. This can happen when using a compositor. This can be addressed by either using the alpha patch or by applying the fixborders patch ref. https://dwm.suckless.org/patches/alpha/dwm-fixborders-6.2.diff.

In dwm-flexipatch the latter is enabled via the NO_TRANSPARENT_BORDERS_PATCH toggle.

**Comment by par4m** [comment]
Thanks that fixed it. Also, I'm experiencing a lot more screen tearing with dwm, is that related to it or is it just my compositor ?

**Comment by bakkeby** [comment]
I know that screen tearing is not so uncommon in X, but I don't have that much experience with it myself. Usually a compositor should help with screen tearing though. Might also depend on what backend is used (if using picom as the compositor).
