### ISSUE TITLE
Pertag vanitygaps patch

### ISSUE THREAD

**Issue by luravoid** [bakkeby/dwm-flexipatch#258]
Resizing gaps works as intented and size of gaps is remained on specific tag and monitor but If I togglegaps then visible tags on all monitors will togglegaps.

**Comment by bakkeby** [comment]
Ah right, it is this line in getgaps that is causing it. Should be using m, not selmon. 
https://github.com/bakkeby/dwm-flexipatch/blob/c553f93b528449ed2e7d4b424f063ef3c1d3d8f6/patch/vanitygaps.c#L191
