### ISSUE TITLE
fatal error: X11/Xft/Xft.h: No such file or directory

### ISSUE THREAD

**Issue by Eccomi21** [bakkeby/dwm-flexipatch#259]
I cloned dwm-flexipatch right after installing arch today using the archinstall script with the xorg configuration.

I installed it the same way in the past without any issues. However today it decided to tell me Xft.h doesn't exist despite the fact that

pacman -F Xft.h 

Puts out the following:

extra/libxft 2.3.4-1
    usr/include/X11/Xft/Xft.h

I then tried to change the path from X11/Xft/Xft.h to usr/include/X11/Xft/Xft.h which did not work either. 

Even more weird is that when I try to look for the thing with Ranger I cannot find it either, but pacman insists that it is there.

Nevermind I'm stupid. It just tells me where to install the library from.

**Comment by bakkeby** [comment]
Have you tried `pacman -S extra/libxft`?

The `-F` is used to find what package the given file exists in so that you know what package to install, it doesn't only list packages that are installed.

**Comment by Eccomi21** [comment]
> Have you tried `pacman -S extra/libxft`?
> 
> The `-F` is used to find what package the given file exists in so that you know what package to install, it doesn't only list packages that are installed. 

Yeah seems like I closed it after you commented and didn't see the reply.

At some point I figured out myself that -F only tells me where to get it from. After I downloaded the library it worked like a charm...

Linux is fun :D
