### ISSUE TITLE
lemonbar in dwm anybar

### ISSUE THREAD

**Issue by DiarrheaMcgee** [bakkeby/dwm-flexipatch#266]
it wont spawn in lemonbar (i can spawn it in manually but dwm doesnt treat it as its own bar)
i enabled the anybar patch set the executable path and also set the class for the altbar and it still wont work

**Comment by DiarrheaMcgee** [comment]
sorry if it very detailed i was in a hurry because i had stuff to do
do i comment out all the rules in barrules and insert a { -2 }

```
static const BarRule barrules[] = {
	/* monitor   bar    alignment         widthfunc                drawfunc                clickfunc                name */
  { -2 }
  /*#if BAR_STATUSBUTTON_PATCH
	{ -1,        0,     BAR_ALIGN_LEFT,   width_stbutton,          draw_stbutton,          click_stbutton,          "statusbutton" },
	#endif // BAR_STATUSBUTTON_PATCH
	#if BAR_POWERLINE_TAGS_PATCH
	{  0,        0,     BAR_ALIGN_LEFT,   width_pwrl_tags,         draw_pwrl_tags,         click_pwrl_tags,         "powerline_tags" },
	#endif // BAR_POWERLINE_TAGS_PATCH
	#if BAR_TAGS_PATCH
	{ -1,        0,     BAR_ALIGN_LEFT,   width_tags,              draw_tags,              click_tags,              "tags" },
	#endif // BAR_TAGS_PATCH
	#if BAR_TAGLABELS_PATCH
	{ -1,        0,     BAR_ALIGN_LEFT,   width_taglabels,         draw_taglabels,         click_taglabels,         "taglabels" },
	#endif // BAR_TAGLABELS_PATCH
	#if BAR_TAGGRID_PATCH
	{ -1,        0,     BAR_ALIGN_LEFT,   width_taggrid,           draw_taggrid,           click_taggrid,           "taggrid" },
	#endif // BAR_TAGGRID_PATCH
	#if BAR_SYSTRAY_PATCH
	{  0,        0,     BAR_ALIGN_RIGHT,  width_systray,           draw_systray,           click_systray,           "systray" },
	#endif // BAR_SYSTRAY_PATCH
	#if BAR_LTSYMBOL_PATCH
	{ -1,        0,     BAR_ALIGN_LEFT,   width_ltsymbol,          draw_ltsymbol,          click_ltsymbol,          "layout" },
	#endif // BAR_LTSYMBOL_PATCH
	#if BAR_STATUSCOLORS_PATCH && BAR_STATUSCMD_PATCH
	{ statusmon, 0,     BAR_ALIGN_RIGHT,  width_statuscolors,      draw_statuscolors,      click_statuscmd,         "statuscolors" },
	#elif BAR_STATUSCOLORS_PATCH
	{ statusmon, 0,     BAR_ALIGN_RIGHT,  width_statuscolors,      draw_statuscolors,      click_statuscolors,      "statuscolors" },
	#elif BAR_STATUS2D_PATCH && BAR_STATUSCMD_PATCH
	{ statusmon, 0,     BAR_ALIGN_RIGHT,  width_status2d,          draw_status2d,          click_statuscmd,         "status2d" },
	#elif BAR_STATUS2D_PATCH
	{ statusmon, 0,     BAR_ALIGN_RIGHT,  width_status2d,          draw_status2d,          click_status2d,          "status2d" },
	#elif BAR_POWERLINE_STATUS_PATCH
	{ statusmon, 0,     BAR_ALIGN_RIGHT,  width_pwrl_status,       draw_pwrl_status,       click_pwrl_status,       "powerline_status" },
	#elif BAR_STATUS_PATCH && BAR_STATUSCMD_PATCH
	{ statusmon, 0,     BAR_ALIGN_RIGHT,  width_status,            draw_status,            click_statuscmd,         "status" },
	#elif BAR_STATUS_PATCH
	{ statusmon, 0,     BAR_ALIGN_RIGHT,  width_status,            draw_status,            click_status,            "status" },
	#endif // BAR_STATUS2D_PATCH | BAR_STATUSCMD_PATCH
	#if XKB_PATCH
	{  0,        0,     BAR_ALIGN_RIGHT,  width_xkb,               draw_xkb,               click_xkb,               "xkb" },
	#endif // XKB_PATCH
	#if BAR_FLEXWINTITLE_PATCH
	{ -1,        0,     BAR_ALIGN_NONE,   width_flexwintitle,      draw_flexwintitle,      click_flexwintitle,      "flexwintitle" },
	#elif BAR_TABGROUPS_PATCH
	{ -1,        0,     BAR_ALIGN_NONE,   width_bartabgroups,      draw_bartabgroups,      click_bartabgroups,      "bartabgroups" },
	#elif BAR_AWESOMEBAR_PATCH
	{ -1,        0,     BAR_ALIGN_NONE,   width_awesomebar,        draw_awesomebar,        click_awesomebar,        "awesomebar" },
	#elif BAR_FANCYBAR_PATCH
	{ -1,        0,     BAR_ALIGN_NONE,   width_fancybar,          draw_fancybar,          click_fancybar,          "fancybar" },
	#elif BAR_WINTITLE_PATCH
	{ -1,        0,     BAR_ALIGN_NONE,   width_wintitle,          draw_wintitle,          click_wintitle,          "wintitle" },
	#endif // BAR_TABGROUPS_PATCH | BAR_AWESOMEBAR_PATCH | BAR_FANCYBAR_PATCH | BAR_WINTITLE_PATCH
	#if BAR_EXTRASTATUS_PATCH
	#if BAR_STATUSCOLORS_PATCH && BAR_STATUSCMD_PATCH
	{ statusmon, 1,     BAR_ALIGN_CENTER, width_statuscolors_es,   draw_statuscolors_es,   click_statuscmd_es,      "statuscolors_es" },
	#elif BAR_STATUSCOLORS_PATCH
	{ statusmon, 1,     BAR_ALIGN_CENTER, width_statuscolors_es,   draw_statuscolors_es,   click_statuscolors,      "statuscolors_es" },
	#elif BAR_STATUS2D_PATCH && BAR_STATUSCMD_PATCH
	{ statusmon, 1,     BAR_ALIGN_CENTER, width_status2d_es,       draw_status2d_es,       click_statuscmd_es,      "status2d_es" },
	#elif BAR_STATUS2D_PATCH
	{ statusmon, 1,     BAR_ALIGN_CENTER, width_status2d_es,       draw_status2d_es,       click_status2d,          "status2d_es" },
	#elif BAR_POWERLINE_STATUS_PATCH
	{ statusmon, 1,     BAR_ALIGN_RIGHT,  width_pwrl_status_es,    draw_pwrl_status_es,    click_pwrl_status,       "powerline_status" },
	#elif BAR_STATUSCMD_PATCH && BAR_STATUS_PATCH
	{ statusmon, 1,     BAR_ALIGN_CENTER, width_status_es,         draw_status_es,         click_statuscmd_es,      "status_es" },
	#elif BAR_STATUS_PATCH
	{ statusmon, 1,     BAR_ALIGN_CENTER, width_status_es,         draw_status_es,         click_status,            "status_es" },
	#endif // BAR_STATUS2D_PATCH | BAR_STATUSCMD_PATCH
	#endif // BAR_EXTRASTATUS_PATCH
	#if BAR_FLEXWINTITLE_PATCH
	#if BAR_WINTITLE_HIDDEN_PATCH
	{ -1,        1,  BAR_ALIGN_RIGHT_RIGHT, width_wintitle_hidden, draw_wintitle_hidden,   click_wintitle_hidden,   "wintitle_hidden" },
	#endif
	#if BAR_WINTITLE_FLOATING_PATCH
	{ -1,        1,     BAR_ALIGN_LEFT,   width_wintitle_floating, draw_wintitle_floating, click_wintitle_floating, "wintitle_floating" },
	#endif // BAR_WINTITLE_FLOATING_PATCH
	#endif // BAR_FLEXWINTITLE_PATCH
  */
};
```
and does it matter if the configurations are in the def.h files or do they have to be in the .h files

**Comment by bakkeby** [comment]
You don't need to comment anything out, you can just delete / replace with the above. All configuration changes goes into your (personal) config.h file, not the default configuration file (config.def.h). Same with patches.h for that matter.

Should you later want to play around with the built-in bar then that is easy enough to restore based on the default configuration.

**Comment by DiarrheaMcgee** [comment]
thanks but i think i did somthing wrong
its giving this error
```
config.h:506:35: warning: ISO C forbids empty initializer braces [-Wpedantic]
  506 | static const BarRule barrules[] = {
      |                                   ^
config.h:506:22: error: zero or negative size array ‘barrules’
  506 | static const BarRule barrules[] = {
```

my barrule thing looks like this

```
static const BarRule barrules[] = {
        { -2 }
};
```

**Comment by DiarrheaMcgee** [comment]
wait the error went away for some reason

**Comment by DiarrheaMcgee** [comment]
ok dwmbar is gone but lemonbar wont start

**Comment by bakkeby** [comment]
What is your command to start lemonbar?

**Comment by DiarrheaMcgee** [comment]
in the config file its
```
static const int usealtbar               = 1;        /* 1 means use non-dwm status bar */
static const char *altbarclass           = "Bar"; /* Alternate bar class name */
static const char *altbarcmd             = "$HOME/.config/lemonbar/bar.sh"; /* Alternate bar launch command */
```
and the actual lemonbar executable is

bar.conf:
```
#!/bin/bash
totalMemory=$(expr $(cat /proc/meminfo | grep MemTotal | tr -dc '0-9') / 1024)
ethVal=$(ticker eth)
temparture=$(echo $(curl -s https://wttr.in | head -n 4) | sed 's/^.*+/+/' | cut -f1 -d "(")
kernelName=$(uname --kernel-release)

trap 'Update' 5
backround="#2D2D2D"

Format() {
	echo "%{+u}%{B$backround} $1 %{B}%{-u}"
}


Workspaces() {
	desktops=$(bspc query -D --names)
	focused=$(bspc query -D --names -d focused)

	for desktop in $desktops; do
		desktop=$(echo "$desktop")
		nodes=$(bspc query -N -d $desktop)
		
		if [ ! -z "$nodes" ]; then
			desktops=$(echo $desktops | sed "s/$desktop/%{F#ff0000}desktop%{F-}/")
		fi

	done
	desktop=$(echo $desktops | sed "s/$focused/%{B$backround}%{+u}_$focused\_%{-u}%{B-}/")

	echo $desktops | sed "s/_/ g"
}


Crypto() {

	Format "ETH: $ethVal"



}

Cpu() {
	cpuBackround="$backround"

	cpuTemp=$(sensors | grep CPU: | grep ° | tr -dc '0-9.')
	cpuUsage=$(top -bn1 | grep "Cpu(s)" | \
           sed "s/.*, *\([0-9.]*\)%* id.*/\1/" | \
           awk '{print 100 - $1"%"}')


	cpuFormat() {
		echo "%{+u}%{B$cpuBackround} $1 %{B}%{-u}"
	}




	if [[ $(expr $(echo $cpuTemp | tr -dc '0-9') / 10) > 51 ]]; then
		cpuColor="#dd0703"
	elif [[ $(expr $(echo $cpuTemp | tr -dc '0-9') / 10) > 40 ]]; then
		cpuColor="#dada00"
	elif [[ $(expr $(echo $cpuTemp | tr -dc '0-9') / 10) < 40 ]]; then
		 cpuColor="#04daab"
	else
		cpuBackround="$backround"
	fi

	echo "%{A:kitty bpytop:}$(cpuFormat "%{$cpuColor}$(echo -e "\uf2db") $cpuUsage $cpuTemp°C%{F-}")%{A}"
}
	
Clock() {
	DATE=$(date "+%d/%m/%y")
	TIME=$(date "+%I:%M:%S")
	echo "%{A:xdg-open www.todaysdate.com:}$(Format "${DATE} ${TIME}")%{A}"
}

ActiveWindow() {
	activeWindow=$(xdotool getwindowfocus getwindowname)
	if [[ $activeWindow == *"YouTube"* ]]; then
		activeWindow=$(echo $activeWindow | cut -c 6-)
	fi
	printf " $activeWindow"
}

Packages() {
	
  Format " $(expr $(expr $(flatpak list | grep -c '^') - 1) + $(pacman -Q | grep -c '^'))"
}

Weather() {
	Format "$(echo $(echo $(echo $temparture) | tr -dc '0-9') | rev | cut -c 2- | rev)°F"
}

Uptime() {
	totalUptime=$(uptime -p | tr -d ',' | cut -c 4-)
  Format "Uptime: $totalUptime"
}

Memory() {
	freeMemory=$(expr $(cat /proc/meminfo | grep MemAvailable | tr -dc '0-9') / 1024) 
	usedMemory=$(expr $totalMemory - $freeMemory)
	echo "%{A:kitty bpytop:}$(Format "Used: $usedMemory MiB ($(echo $(( $usedMemory*100/$totalMemory )) )%)")%{A}"
}

Kernel() {
  Format "%{F#00FFFF}$(echo -e "\uf17c") $(uname -r)%{F#FFFFFF}"
}

CheckUpdates() {
  if test "$(checkupdates | wc -l)" != 0; then
    updateNotification="%{F#00FFFF}   %{F#FFFFFF}"
  else
    updateNotification="%{F#00FF00}   %{F#FFFFFF}"
  fi
  #fi
  echo "%{A:kitty sudo pacman -Syu:}$(Format "$updateNotification")%{A}"
}


Update() {
  echo -e " %{l} $(Workspaces) $(ActiveWindow) %{r} $(Kernel) $(Weather) $(Crypto) $(CheckUpdates) $(Packages) $(Memory) $(Cpu) $(Uptime) $(Clock)"
}

while true; do
	Update
	sleep 1s &
	wait
done
```
bar.sh:
```
#!/bin/bash
killall -q lemonbar
killall -q bar.conf

~/.config/lemonbar/bar.conf | lemonbar -d -p -g 2560x32+0+0 -F "#FFFFFFFF" -B "#FF222222" -U "#268bd2" -f "FontAwesome" -u 3 -o 4 -f "JetBrains Mono Medium"-10 | $SHELL
```

**Comment by DiarrheaMcgee** [comment]
it open and works if i open it manually but then dwm doesnt recognize it as its own

**Comment by bakkeby** [comment]
Does bar.sh have execute permissions?

If so then you may want to add logging to see if it falls over at some point in the script when executed through dwm.

From what you are describing it sounds like dwm starts up without a bar and you can still spawn a terminal etc.

**Comment by DiarrheaMcgee** [comment]
it does have execute permissions and that is a good description of what happens
the log says

cat dwm.log
[174 15:18:46.320770] Ignoring invalid config line: narrow_symbols
[174 15:18:46.320833] Ignoring invalid config line: font_features
[174 15:18:46.321276] Ignoring invalid config line: url_excluded_characters
[174 15:18:46.322407] Ignoring invalid config line: background_image
[174 15:18:46.322722] Ignoring invalid config line: env
[174 15:18:46.322744] Ignoring invalid config line: watcher
[174 15:18:46.322760] Ignoring invalid config line: exe_search_path
[174 15:18:46.322836] Ignoring invalid config line: file_transfer_confirmation_bypass
[174 15:18:46.323113] Ignoring invalid config line: action_alias
[174 15:18:46.323139] Ignoring invalid config line: kitten_alias
[1520454:1520525:0623/151853.077650:ERROR:object_proxy.cc(623)] Failed to call method: org.freedesktop.DBus.StartServiceByName: object_path= /org/freedesktop/DBus: org.freedesktop.DBus.Error.NoReply: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.
[1520454:1520454:0623/151853.590218:ERROR:sharing_service.cc(222)] Device registration failed with fatal error
[174 15:19:12.505413] [PARSE ERROR] Unrecognized DCS code: 0x7a
[174 15:19:12.505431] [PARSE ERROR] Unknown CSI code: 'm' with start_modifier: '' and end_modifier: '%' and parameters: '0'
[174 15:19:26.003345] [PARSE ERROR] Unrecognized DCS code: 0x7a
[174 15:19:26.003562] [PARSE ERROR] Unknown CSI code: 'm' with start_modifier: '' and end_modifier: '%' and parameters: '0'
[174 15:35:09.203581] [PARSE ERROR] Unrecognized DCS code: 0x7a
[174 15:35:09.203709] [PARSE ERROR] Unknown CSI code: 'm' with start_modifier: '' and end_modifier: '%' and parameters: '0'
[174 15:35:52.283819] Ignoring invalid config line: narrow_symbols
[174 15:35:52.283877] Ignoring invalid config line: font_features
[174 15:35:52.284332] Ignoring invalid config line: url_excluded_characters
[174 15:35:52.285489] Ignoring invalid config line: background_image
[174 15:35:52.285819] Ignoring invalid config line: env
[174 15:35:52.285842] Ignoring invalid config line: watcher
[174 15:35:52.285858] Ignoring invalid config line: exe_search_path
[174 15:35:52.285936] Ignoring invalid config line: file_transfer_confirmation_bypass
[174 15:35:52.286217] Ignoring invalid config line: action_alias
[174 15:35:52.286243] Ignoring invalid config line: kitten_alias
[174 15:38:43.873799] [PARSE ERROR] Unrecognized DCS code: 0x7a
[174 15:38:43.873814] [PARSE ERROR] Unknown CSI code: 'm' with start_modifier: '' and end_modifier: '%' and parameters: '0'

and then the last 100 or so lines are all just from the browser

also the way i have it output to the log is exec dwm 2> ~/.dwm/dwm.log

**Comment by bakkeby** [comment]
Are those logs at all related to lemonbar?

I was thinking of adding set -x to the bar.sh script or having temporary echo statements that you redirect to a log file to sanity check that it makes it all the way to the end when run by dwm.

**Comment by DiarrheaMcgee** [comment]
ah

**Comment by bakkeby** [comment]
Is lemonbar guaranteed to be in your path when run like this? Could try with absolute path to sanity check. Alternatively redirect stdout and stderr from that command to a file like ~/lemon.out in case it falls over with an error.

Also are you sure that you need the -d flag for the command?

**Comment by DiarrheaMcgee** [comment]
il try disabling the -d flag and ive been using the absolute path but i do have it in $PATH

**Comment by bakkeby** [comment]
Ok so if you run the bar.sh script in your terminal then it I'd presume that it doesn't return, that it waits for the lemonbar process to finish.

The same goes for dwm in this case - it is waiting for the script to finish and that is the reason why you can't use any keybindings etc.

Try adding a & to the lemonbar command in the script to have it run in the background.

**Comment by DiarrheaMcgee** [comment]
i forgot to set it to a subshell
now it works nearly perfectly but is there a way to add a gap to the top of the screen so the windows dont overlap

**Comment by bakkeby** [comment]
Hmm, the height of the bar is retrieved via the window attributes of the bar when it first starts, would have thought that this is enough. Alternatively there is also the insets patch which reserves space for the bar, but will look odd when toggling the bar away. The bar height patch also does not apply for external bars.

**Comment by DiarrheaMcgee** [comment]
thanks now it works perfectly
