### ISSUE TITLE
barmodules center alignment isn't accurate & others

### ISSUE THREAD

**Issue by wael444** [bakkeby/dwm-flexipatch#267]
![image](https://user-images.githubusercontent.com/47404953/175539072-3b9c5f99-eaaf-40b0-ab3f-83484e77ff54.png)
status is set to a long `foo` for example.

one of the only patches i know that can center is [centretitle]( https://dwm.suckless.org/patches/centretitle/dwm-centretitle-20200907-61bb8b2.diff)

2 other issues i have is that when the configuration has all the bars on only monitor 0, when a window is created on monitor 1, dwm crashes:
```c
static const BarRule barrules[] = {
	/* monitor  bar    alignment         widthfunc              drawfunc              clickfunc           name */
	{ 0,      0,     BAR_ALIGN_RIGHT,  width_systray,         draw_systray,         click_systray,      "systray" },
	{ 0,      0,     BAR_ALIGN_RIGHT,  width_status,          draw_status,          click_status,       "status" },
	{ 0,      0,     BAR_ALIGN_CENTER,   width_tags,            draw_tags,            click_tags,         "tags" },
	{ 0,      0,     BAR_ALIGN_LEFT,   width_ltsymbol,        draw_ltsymbol,        click_ltsymbol,     "layout" },
	{ 0,      0,     BAR_ALIGN_NONE,   width_wintitle,        draw_wintitle,        click_wintitle,     "wintitle" },
};
```

also some weird unnessesary padding on systray:
![image](https://user-images.githubusercontent.com/47404953/175540272-d4be3509-184b-4efc-86a4-7d8f331aa10d.png)

**Comment by bakkeby** [comment]
I did not notice that it was raised in the wrong repository, moved it over now.
