### ISSUE TITLE
Visual glitch when using systray and barpadding patch

### ISSUE THREAD

**Issue by forte97** [bakkeby/dwm-flexipatch#268]
Hello, there's this weird visual glitch where there's a line of pixels that shows up next to the top bar when nothing is on the system tray. When an app is in the system tray, it goes away.

**Comment by bakkeby** [comment]
Could you add a screenshot for reference, an does the line also show when killing the compositor?

**Comment by forte97** [comment]
This line still shows when the compositor is closed.
![icon off](https://user-images.githubusercontent.com/106557541/175877213-fa28a8a9-6502-4b7d-a94e-da5bcf1588dd.png)
![icon on](https://user-images.githubusercontent.com/106557541/175877221-c5f57a87-463a-49b5-b489-cd6dd5837fbb.png)

**Comment by bakkeby** [comment]
Thanks for that. I'll push a fix in a bit.

**Comment by bakkeby** [comment]
Should be fixed with the above, but let me know if you spot any issues.
