### ISSUE TITLE
no swallow settings not being respected

### ISSUE THREAD

**Issue by kronikpillow** [bakkeby/dwm-flexipatch#27]
for some reason the no swallow settings are not being respected when using xorg-xev to checkout my key press symbols, it gets swallowed, I'm unable to figure out why, but on Luke's dwm it doesn't get swallowed with the same settings

[my config.h](https://github.com/kronikpillow/dwm-flexipatch/blob/build/config.h)
[my build](https://github.com/kronikpillow/dwm-flexipatch/tree/build)

**Comment by bakkeby** [comment]
I don't know. I also just have "Event Tester" as the title for this to match.

**Comment by kronikpillow** [comment]
i figgured it out, i was missing a comma after 1 on the noswallow option :))
