### ISSUE TITLE
Can I use renamed scratchpad by matching only the scratchkey?

### ISSUE THREAD

**Issue by UtkarshVerma** [bakkeby/dwm-flexipatch#273]
In my config, I defined two scratchpads:
```c
static const char *spterm[] = {"~", "st", "-g", "80x23", NULL};
static const char *spnotes[] = {"n", "st", "-g", "80x26", "-e", "nvim", "-c", "VimwikiIndex", NULL};
```

I also have a rule for these windows:
```c
    RULE(.scratchkey = '~', .isfloating = 1, .iscentered = 1)
    RULE(.scratchkey = 'n', .isfloating = 1, .iscentered = 1)
```

Below is how, I have bound it:
```c
    { MODKEY,                       XK_grave,      togglescratch,          {.v = spterm } },
    { MODKEY,                       XK_n,          togglescratch,          {.v = spnotes } },
```

However, using this config is leading to undefined behaviour. `Mod+n` works properly but `Mod+grave` creates a new instance every time. Sometimes, it even sends all windows to the scratchpad. If I use `st -n spterm` and then match the instance in `RULE`, then everything works fine. This leads me to the question, is `scratchkey` not sufficient alone?

**Comment by bakkeby** [comment]
When it comes to client rules there are two categories of fields:
   - **filters**, allowing you to match on class, instance, title, etc. and
   - **rule options**, to make the window floating, which tag to place the window on, etc.

The rule scratchkey value of "~" here falls under the latter category. 

The general principle of scratchpads (regardless of patch) is that you run a command after which the window manager has no control until the application asks for the window to be mapped. This means that triggering the command and the window popping up is asynchronous. 

As such we need to have a client rule in place that identifies the window as a scratchpad and sets the scratchkey for the client accordingly in order for the client to be found the next time we hit that keybinding.

The lack of filters for these example rules means that they will apply to all windows.

**Comment by UtkarshVerma** [comment]
Thanks for the explanation. It makes sense now.
