### ISSUE TITLE
dwm doesn't use the resize cursor from the XCURSOR theme

### ISSUE THREAD

**Issue by UtkarshVerma** [bakkeby/dwm-flexipatch#274]
I use Capitaine cursor theme and all cursors are shown appropriately. However, when resizing windows in DWM, it uses a different cursor. Could you please let me know how this can be fixed?

https://user-images.githubusercontent.com/31820255/177911168-b9792b20-12bc-494d-9a30-9e1e962d99cc.mp4

**Comment by bakkeby** [comment]
The video looks scrambled to me but dwm specifies the cursor to use when resizing in the setup function. 

https://github.com/bakkeby/dwm-flexipatch/blob/5f7df0b0dc78ae00f21d5bbe892456c450506b9b/dwm.c#L3705

**Comment by UtkarshVerma** [comment]
Thanks, I modified the line and got the expected behaviour. Don't you think `XC_bottom_right_corner` should be a better choice for this cursor?

This is how it looks:
![image](https://user-images.githubusercontent.com/31820255/177945419-f294367b-09c9-42f5-807d-932ad4a63daa.png)

**Comment by bakkeby** [comment]
Not for me to judge, XC_sizing is what is used in the upstream dwm.

`XC_bottom_right_corner is used` for the resize corners and resizepoint patches.

**Comment by bakkeby** [comment]
I'll mark this as closed. The general idea for this project is still to give a more or less genuine dwm experience so I'll keep the cursor as-is unless it changes upstream.
