### ISSUE TITLE
Has scroll been removed from statuscmd patch?

### ISSUE THREAD

**Issue by UtkarshVerma** [bakkeby/dwm-flexipatch#277]
I just noticed that scroll functionality was not working for my statusbar while click was. I use [`dwmblocks-async`](https://github.com/UtkarshVerma/dwmblocks-async) and am pretty sure everything is fine there.

I also checked emitted signals using `strace -e 'trace=!all' ./dwmblocks` and I could only see signals being sent for click events.

**Comment by bakkeby** [comment]
What does the statuscmd patch have to do with status scrolling? The scrolling aspect would be handled entirely by the external program.

**Comment by UtkarshVerma** [comment]
As I mentioned, scroll events are not being signalled by dwm to the scrolling application. Could you please verify this once?

**Comment by UtkarshVerma** [comment]
I figured it out. I had to define bindings for `Button4` and `Button5` in `config.h`.
https://github.com/bakkeby/dwm-flexipatch/blob/5f7df0b0dc78ae00f21d5bbe892456c450506b9b/config.def.h#L1308

Sorry for the trouble.

**Comment by bakkeby** [comment]
Oh right, I misunderstood what you meant. This is related to using the mouse scroll wheel for sending click signals to dwmblocks.

By scroll I though you were referring to status scrolling similar to how marquee was a popular internet site feature back in 1996.
