### ISSUE TITLE
cfacts

### ISSUE THREAD

**Issue by kronikpillow** [bakkeby/dwm-flexipatch#28]
did something about cfacts change? it's behaving unexpectedly with me, I don't remember it being like this ... what i mean is ... windows in the stack, for example, if i have 2 windows in the stack, and MOD+SHIFT+L on the first window and expand that window, when I try to return it with MOD+SHIFT+R it wont do it, and the other way around as well, the only way I can do it, is if I actually focus the 2nd window in the stack, and then move it in the counter direction ... i remember being able to change cfacts in both directions on the same window

**Comment by bakkeby** [comment]
Nothing has changed.

It's likely just that you have changed the MOD+SHIFT+L to be MOD+L (same as to change mfact).
https://github.com/kronikpillow/dwm-flexipatch/blob/master/config.h#L193

**Comment by kronikpillow** [comment]
ahhh true :D what noob moves sorry :D
