### ISSUE TITLE
Need Monacle layout with VanityGaps and Bar and without VanityGaps and Bar

### ISSUE THREAD

**Issue by Randomguy-8** [bakkeby/dwm-flexipatch#283]
Actually i need a keybinding or a function though which if i press `MODKEY + m` it just toggle **Monocle Layout** with VanityGaps and bar enabled but when i press `MODKEY | ShiftMask + m` it toggles **Monocle Layout** but also disable VanityGaps and Bar. Then When i Change My Layout(to tile or null) it enable VanityGaps and Bar.

I tried this:
```
 	{ MODKEY,                       XK_t,          setlayout,              {.v = &layouts[0]} },
	{ MODKEY,                       XK_f,          setlayout,              {.v = &layouts[1]} },
	{ MODKEY,                       XK_m,          setlayout,              {.v = &layouts[2]} },
	
	{ MODKEY,                       XK_n,          setlayout,              {.v = &layouts[2]} },
	{ MODKEY|ShiftMask,             XK_n,          togglebar,              {0} },
	{ MODKEY|ShiftMask,             XK_n,          togglegaps,             {0} },

	{ MODKEY,                       XK_t,          togglegaps,             {0} },
	{ MODKEY,                       XK_t,          defaultgaps,            {0} },
	
	{ MODKEY,                       XK_f,          togglegaps,             {0} },
	{ MODKEY,                       XK_f,          defaultgaps,            {0} },

```

Buit using this Keybinding is kind of problematic. when i change layout from **tile** to **null** it disables VanityGaps or vice-versa.

Thx for any Help.

**Comment by bakkeby** [comment]
In this case you'd want separate functions to explicitly enable or disable the bar and to enable and disable gaps, rather than the toggle functions.

These would be very simple to write and you could just have them in your config.h file for that matter. 

What is the particular use case for this though? Seems pretty complicated compared to just triggering fullscreen for the window.

**Comment by Randomguy-8** [comment]
Alright, Here is three scenarios 

1st scenario: My simple(beautiful) DWM with `tile layout`
![2022-07-30_20-33](https://user-images.githubusercontent.com/89891346/181920515-39232f98-3087-4d65-b46c-0d616090d5f5.png)

2nd Scenario: DWM again but with `Monocle Layout` (htop window hide behinds the alsa
![2022-07-30_20-32](https://user-images.githubusercontent.com/89891346/181920616-9ea2e4c3-96dc-4dd7-8fcd-2bccebeea7e4.png)
 window)

3rd Scenario: `Monocle Layout` but VanityGaps and Bar is hidden(in other words FULLSCREEN _but not every application support fullscreen with F11_
![2022-07-30_20-35](https://user-images.githubusercontent.com/89891346/181921185-39c17827-0c40-4f5f-92de-b301b05c4cef.png)


Now Here is a Thing: I Want `Monocle Layout` with VanityGaps and Bar and also without VanityGaps and Bar. I do prefer `ModKey + ShiftMask + m` as keybinding for **FullscreenMonocleLayout**.

MoreImportantly: I am yet learning **c**(Big Time Noob) and i dont know anything about **X11**(Xserver, Xinit). I do urge to learn it _ Hence i can write my own DWM _ but I Dont know Where to start(and find tutorials). Anyways Thx.

**Comment by bakkeby** [comment]
The third scenario is practical if you aim to run multiple windows in fullscreen and switch between them. 

If that is not how you use it then using fullscreen is more practical, in my personal opinion of course. 

In my setup for example I have `Super+f` to toggle fullscreen for the given window, it is so convenient to be able to toggle fullscreen for any window using the same keybinding rather than having to check whether it is F11, Ctrl+Enter, Ctrl+f, f, etc. for the given window (and not all windows offer that, like terminals for example).

https://github.com/bakkeby/dwm-flexipatch/blob/d9f79bea73894e1fe1b2a0342dafcfc818d4c0ee/patches.def.h#L1212-L1215

I can show you how to create those separate enable/disable gaps/bar functions when I get to a computer.

**Comment by bakkeby** [comment]
Example functions. I think you should be able to read and work out what these do without any practical experience with C.

```c
static void
enablebar(const Arg *arg)
{
	if (!selmon->showbar)
		togglebar(arg);
}

static void
disablebar(const Arg *arg)
{
	if (selmon->showbar)
		togglebar(arg);
}

static void
hidegaps(const Arg *arg)
{
	#if PERTAG_VANITYGAPS_PATCH && PERTAG_PATCH
	if (selmon->pertag->enablegaps[selmon->pertag->curtag])
	#else
	if (enablegaps)
	#endif // PERTAG_VANITYGAPS_PATCH
		togglegaps(arg);
}

static void
showgaps(const Arg *arg)
{
	#if PERTAG_VANITYGAPS_PATCH && PERTAG_PATCH
	if (!selmon->pertag->enablegaps[selmon->pertag->curtag])
	#else
	if (!enablegaps)
	#endif // PERTAG_VANITYGAPS_PATCH
		togglegaps(arg);
}
```

**Comment by Randomguy-8** [comment]
Okay...

Well its kind of not working!
```
config.h:812:6: error: 'enablegaps' undeclared (first use in this function); did you mean 'enablebar'?
  812 |  if (enablegaps)
      |      ^~~~~~~~~~
      |      enablebar
config.h:812:6: note: each undeclared identifier is reported only once for each function it appears in
config.h: In function 'showgaps':
config.h:823:7: error: 'enablegaps' undeclared (first use in this function); did you mean 'enablebar'?
  823 |  if (!enablegaps)
      |       ^~~~~~~~~~
      |       enablebar
```

at first i thought `enablegaps` is typo so i replaced it with `togglegaps` and then it result this:
```
config.h: In function 'hidegaps':
config.h:812:6: warning: the address of 'togglegaps' will always evaluate as 'true' [-Waddress]
  812 |  if (togglegaps)
      |      ^~~~~~~~~~
config.h: In function 'showgaps':
config.h:823:6: warning: the address of 'togglegaps' will always evaluate as 'true' [-Waddress]
  823 |  if (!togglegaps)
      |      ^
```

**Comment by bakkeby** [comment]
Yes that error means that the variable enablegaps is used before it is defined. Would need to move it from vanitygaps.c into vanitygaps.h or into config.h.
