### ISSUE TITLE
how to pass floatpos to dwmc/fsignal?

### ISSUE THREAD

**Issue by pangume** [bakkeby/dwm-flexipatch#284]
so, as example say `xsetroot -name "fsignal:signame [<type> <value>]`, and i ran this `xsetroot -name "fsignal:floatpos v "-26x -26y"` but nothing happened. i've also tried added these from guessing through the example.
- dwmc
```shell
1) ....
2)
   case $1 in
   floatpos) ;& # I'm not sure what the args are ?
esac
```

- config.def.h
```c
static Signal signals[] = {
	{ "floatpos",                floatpos },
}
```

**Comment by bakkeby** [comment]
You can't because the fsignal patch does not support strings (text). You can do this with the IPC patch however.

**Comment by pangume** [comment]
Oh okay, i thought there will some workaround that. i just need some of floatpos moving window to work.
could i do that with switch case with predefined value of floatpos. so for instance something like this.
```c
switch (direction)
  case 1:
    // "-26x -26y" ↖

  case 2:
   //"  0x -26y"  ↑
  case 3:
   ...
```
so at the end i could call `xsetroot -name "fsignal:floatposex i <value>`. hope this make sense, but i'm not sure how to do that.

**Comment by bakkeby** [comment]
Turns out that it wasn't that complicated to add support for strings for this patch. This won't be in the original patch of course.

The floatpos string in this case would be without the quotes, e.g.

```sh
$ xsetroot -name "fsignal:floatpos v -26x -26y"
```

**Comment by bakkeby** [comment]
If you wanted to have predefined floatpos strings that are associated with values as in your example switch statement then you could do something like this.

```c
static void
floatposex(const Arg *arg)
{
	static const char *positions[] = {
		"-26x -26y",
		"  0x -26y",
		" 26x -26y",
		"-26x   0y",
		" 26x   0y",
		"-26x  26y",
		"  0x  26y",
		" 26x  26y"
	};

	if (arg->i < 0 || arg->i > LENGTH(positions))
		return;

	floatpos(&((Arg) { .v = positions[arg->i] }));
}
```

**Comment by pangume** [comment]
Wow that's quick. Thanks alot.
