### ISSUE TITLE
BAR_WINTITLEACTIONS_PATCH: no showhideclient for dwmc/fsignal

### ISSUE THREAD

**Issue by rteats** [bakkeby/dwm-flexipatch#287]
The command is present in `config.def.h`
https://github.com/bakkeby/dwm-flexipatch/blob/2d34596ad0a93860225b2b318d8f2d57e0e50f64/config.def.h#L1030-L1032
However, while using `DWMC_PATCH` I noticed that there's no `showhideclient` command in `patch/dwmc`
Is it going to be added?

**Comment by bakkeby** [comment]
If I recall my reasoning for not adding this function to the dwmc patch and the IPC patch configuration was that it is primarily intended for button bindings, i.e. that you can use the same mouse button to show or hide the window when clicking on the window title.

As a keybinding this in practice will only hide the selected client (unless there are no more visible clients in which it will show the last selected client).

That behaviour would be the same in dwmc and IPC. I don't have a problem adding it though.

**Comment by rteats** [comment]
> As a keybinding this in practice will only hide the selected client (unless there are no more visible clients in which it will show the last selected client).

IIRC it's possible to select the hidden client by running e.g. `dwmc focusstack 2` when scrolling through clients, I've looked it up in the Issues of this repository somewhere

> I don't have a problem adding it though.

That would be appreciated, since I don't have knowledge over the codebase yet.

**Comment by bakkeby** [comment]
It is pretty straightforward, refer to the above diff. You can add all kinds of hooks this way.

**Comment by rteats** [comment]
Thanks a lot!
That diff will be useful as a reference if I'll encounter anything else missing in my dwmc setup.
