### ISSUE TITLE
gaps in tatami patch

### ISSUE THREAD

**Issue by plasmoduck** [bakkeby/dwm-flexipatch#299]
Hi mate, I forked your projected a while ago and added in the tatami patch, what do I have to modify to get gaps in the tatami patch like the rest of the layouts? Here's the [source](https://github.com/plasmoduck/modwm)

**Comment by plasmoduck** [comment]
I followed this but there is still no gaps [link]{https://github.com/bakkeby/dwm-flexipatch/issues/244#issuecomment-1081507313}

**Comment by bakkeby** [comment]
It would be the same process as adding cfacts to a layout, you have to read and understand how the layout code arranges windows and make changes where necessary.

The flextile reference shows where to add the inner horizontal (`ih`) and inner vertical (`iv`) gaps. Outer gaps would just be a matter of adjusting the initial `nx`, `ny`, `nw`, and `nh` variables.
