### ISSUE TITLE
patch / feature requests? :)

### ISSUE THREAD

**Issue by kronikpillow** [bakkeby/dwm-flexipatch#3]
do you accept patch proposals on which to include in the flexipatch buid? and feature requests to add some minor functionality to those patches about a idea I have?

I'm not a C programmer, or a programmer at all, I'm just a good tinkerer, I managed to make some of the manual patches work, but some I just cant seem to get to, so ... I switched to flexipatch and love it ... just that ... would like to see some additional patches on the list, but neither of them are on the suckless website ...

for example the
[dwm-switchview](https://github.com/chau-bao-long/dotfiles/blob/master/suckless/dwm/shiftview.diff) (ill have to upload that ... in addition it needs keyboard bindings, for example on voidrice dwm where this patch is included, it is bound to mod+g and mod+semicolon I think, and to mod+page up and mod+page down, it basically cycles the view between tags in left and right direction similar like the default view function, but it isn't limited to between 2 tags, it cycles all the tags in 1 or the other direction...

[a different implementation of a scratchpad, that allows you to send any window to the scratch pad and to remove it from scratchpad with keybindings, and ofc show / hide the scratchpad](https://github.com/GasparVardanyan/dwm-scratchpad) 

what I would like to see in a  dwm scratchpad (regardless of if on one you already included or on this one 
 suggested) is that, you can spawn programs directly in to an scratchpad, so for example, when I press mod+A that it opens a bc calculator in the scratchpad, and that when I press mod+alt+t that it opens tmux in a scratchpad, and when I press mod+v that it opens vim in scratchpad, and to be able to define more of these ... maybe with awindow rule to always start a program in the scratchpad, something like "isscratchpad" or a custom command variable, or i dunno, I can do this on i3 ... what do you think?

I requested the feature on the author's github page, but he threw me off telling me to to do it my self and I don't know C :D [multiple scratchpads question](https://github.com/GasparVardanyan/dwm-scratchpad/issues/2)

or to include such functionality, in the original suckless scratchpad

I got a few other good patches that arent for some reason listed on suckless.org, but I wont burn time suggesting them, until I see that your open to including requested patches and extending the patch library :)

**Comment by bakkeby** [comment]
Yes I can't see why not (unless they cause conflicts or are way too invasive). What did you have in mind?

**Comment by kronikpillow** [comment]
I updated my first post to include what I had in mind, sorry, forgot to write it, then edited it :)

**Comment by kronikpillow** [comment]
2nd feature request is regarding the AWESOMEBAR_PATCH ... you made a keybinding at mod+z to hide active window, but ... there is no keybinding or function to unhide them, as the function that is bound to the keybinding is a function that was designed for the statusbar, you can only unhide hidden windows by clicking on the hidden window title on the statusbar ... would love to see full keyboard functionality regarding hiding/unhiding

**Comment by bakkeby** [comment]
Regarding the [shiftview](https://github.com/chau-bao-long/dotfiles/blob/master/suckless/dwm/shiftview.diff) patch you referred to, you might want to have a look at the [focusadjacenttag](https://dwm.suckless.org/patches/focusadjacenttag/) patch. Same functionality, but you can also move windows to the left or right. The only thing that doesn't have is being circular. I can still add shiftview if the circular aspect is that useful.

---

About scratchpad - to be honest I've never really understood the appeal. Is it just that you can hide running windows and show them again when you need them?

I think you wouldn't be able to do it with a isscratchpad window rule - simply because you'd have to define keyboard shortcuts for each specific scratchpad anyway - unless you just have one scratchpad with multiple windows that all show / hide together.

> _I requested the feature on the author's github page, but he threw me off telling me to to do it my self and I don't know C :D_

Well, he's not wrong you know. If you are not into learning C and tailor it to work exactly like you want it to work, then dwm is a bit of wasted time. You'd likely be better off using some of the more feature rich tiling window managers out there.

I can't promise anything, but I'll give it a think.

---

> _I got a few other good patches that arent for some reason listed on suckless.org, but I wont burn time suggesting them_

There are many reasons why patches, even good ones, may not be listed on suckless.org. I did get the impression that they preferred them being hosted elsewhere if possible.

I'd be happy to have a look, I'm generally interested in seeing what new features patches may provide.

---

> _2nd feature request is regarding the AWESOMEBAR_PATCH ... you made a keybinding at mod+z to hide active window, but ... there is no keybinding or function to unhide them, as the function that is bound to the keybinding is a function that was designed for the statusbar, you can only unhide hidden windows by clicking on the hidden window title on the statusbar ... would love to see full keyboard functionality regarding hiding/unhiding_

I guess that shouldn't be that complicated. You'd have to unhide all clients on the given monitor though.

**Comment by kronikpillow** [comment]
I'll check the focusadjacenttag but I'm not sure it gives what im looking for ...

regarding scratchpad, no it's not just to hide a window and bring it up when I need it, the scratchpad I requested to include gives users the ability to for example, send a browser in to the scratchpad, which can be very useful when for example, working on something, and having a guide/manual opened in a scratchpad, but yes also to be able to for example, spawn a calculator, and just hide it and pull it back up when I need it ... but with the awesomebar patch, that kinda actually does exactly that, only thing we need is a way to unhide them with a keyboard ..

so regarding the awesomebar patch, I was thinking that you dont need to unhide all windows on a different tag/monitor to be able to do so, what we need is a function that with a set of keybindings changes focus between windows on the statusbar ...

so for example .. I have a browser, Discord, and a text document opened on tag 1, and for example, I hide my browser and Discord, to pull back up Discord and the text document all I need to do is mouse click on the statusbar's placeholder for that window, something a function that moves selection left / right on the statusbar regardless of hidden or not hidden status, or a function that shifts selection between hidden windows on a tag, so that you / we can bring it back up to view with a simple mod+z ...

regarding learning C, I actually chose DWM as I want to learn C, it's on my todo list, and i figured dwm is the best way to do so as it gives me something to work on once I start learning, then I hit up flexipatch, and I was like damn, this is some good work :) I'm gonna spread the love about dwm-flexipatch as it really allows dwm noobs or people who don't know C, to actually use DWM and to make it functional with a simple flip on a config file :D

**Comment by kronikpillow** [comment]
ok so yeah, shiftview over focusadjascenttag definitely, it's just nice to have the ability to cycle through tags
default keybindings to maybe to MOD+Shift+Tab and Mod+Shift+backslash :)

**Comment by bakkeby** [comment]
I added the shiftview patch now. An alternative could be to make the focusadjascenttag also wrap around in a cyclic manner, but I'll leave it at that.

**Comment by kronikpillow** [comment]
thanks mate :) I will open new topics for other feature / patch requests :)
