### ISSUE TITLE
No alt-tab patch?

### ISSUE THREAD

**Issue by Scorpion2185** [bakkeby/dwm-flexipatch#303]
No alt-tab patch https://dwm.suckless.org/patches/alt-tab/ patch now?

**Comment by bakkeby** [comment]
It is not a particularly good nor useful patch. I'd be surprised if more than one person uses this. This could just as well have been a standalone task switcher rather than having it integrated into dwm.

That said it shouldn't conflict with anything else and should be trivial to add.

**Comment by Scorpion2185** [comment]
It is surely good and useful for me and the task switcher matches dwm color and style automatically.

Could you add it?

**Comment by bakkeby** [comment]
Added now.
