### ISSUE TITLE
Rounded corners patch breaks fullscreen

### ISSUE THREAD

**Issue by speediegq** [bakkeby/dwm-flexipatch#304]
I don't specifically use this build but it has been very useful in fixing patch conflicts so I thought I'd submit an issue here in return as I recently found an issue with the rounded corners patch and dwm-flexipatch also has the same problem.

I saw someone mention this issue in an old issue here, however the bug was never actually fixed. (#200)

If you attempt to fullscreen something (such as a window with the actualfullscreen patch) or with a web browser, the window completely breaks. 

I don't know exactly why this happens, but the rounded corners patch is definitely the cause. If the drawroundedcorners function is not called, full screening works as expected.

See the images. The more clients you spawn the more it breaks.
With multiple clients:
![image](https://user-images.githubusercontent.com/71722170/194910801-6b04f70b-9ca7-4613-bf4a-48ee38ecdc19.png)
With only one client:
![image](https://user-images.githubusercontent.com/71722170/194910910-710afcba-d35b-4fba-897b-65334d8f3488.png)

**Comment by bakkeby** [comment]
You are right, that is pretty obscure.

As far as I understand it the shape / mask that applies to the window is still there, obscuring the view making part of the window transparent. 

The shape library didn't have any functions to remove shapes applied to a window, stumbled upon how to do this via a snippet from dunst:
https://github.com/dunst-project/dunst/blob/1ef38e59cfbc985b2f7a8fdc229e7755cf3863a3/src/x11/x.c#L133-L144

The solution is basically applying a new shape which is the full size of the window.

The patch is intended to allow windows to have rounded corners without the use of a compositor. These days if someone wants rounded corners then the recommended way is to get that via a compositor like picom (which can also take the window border into account making it look more seamless).

**Comment by speediegq** [comment]
Glad the issue was fixed.

In general, the rounded corners patch seems pretty janky, and if you don't set borderpx to 0, it breaks completely, although someone did manage to add support for borders [here](https://github.com/igor37/dwm-rounded-corners/blob/master/dwm-rounded-gaps-fullscreen.diff).

Picom is really the best solution as it can also round the bar, which is nice if you use the barpadding patch.

**Comment by speediegq** [comment]
oops forgot to close

**Comment by speediegq** [comment]
@bakkeby I found another issue caused by the rounded corners patch.
For patches such as moveaspectratio or really any keybinds that change the size of clients, it breaks similar to the images I sent.

Repeating your commit for each of those functions seems to fix the problem, but just thought I'd mention it since I just noticed it (shows how rarely I use the floating layout).

![image](https://user-images.githubusercontent.com/71722170/195941918-350b4179-c46d-4ff1-a5dd-875ef7a58c12.png)

**Comment by bakkeby** [comment]
I was thinking that this would be a good reason for merely removing the old patch from this repository (as users are recommended to let a compositor handle this).

Looking at the original patch I think it is clear that the user only ever used floating layout as `drawroundedcorners` was applied once in the manage function (when the window is first mapped) and again in `resizemouse` when the size of the window changed.

This means that the code that makes this happen for tiled window will be something that I must have added back when I originally integrated this patch.

Looking at it now I think that it makes much more sense to place this logic in the `resizeclient` function instead which is incidentally how igor37 also did it in the patch you referred to. He also had a call to that in `restack` - not entirely sure why that would be necessary.

So I did a bit of refactoring and also added support for window borders.

**Comment by speediegq** [comment]
Awesome, If the rounded corners patch causes more issues it may not be worth maintaining though, especially considering how many users actually enable it. Either way probably safe to close this now!
