### ISSUE TITLE
actualfullscreen patch

### ISSUE THREAD

**Issue by wr4ckr** [bakkeby/dwm-flexipatch#307]
Add support of actualfullscreen patch - https://dwm.suckless.org/patches/actualfullscreen/

**Comment by bakkeby** [comment]
That is already there in form of this patch:
https://github.com/bakkeby/dwm-flexipatch/blob/b4ae62d21a38b475d34c8a1b3a051e41ccda92dd/patches.def.h#L1253-L1256
