### ISSUE TITLE
dwmblocks-statuscmd: mouse click results in multiple executions

### ISSUE THREAD

**Issue by rharmonson** [bakkeby/dwm-flexipatch#312]
On clicking a dwmblock, statuscmd (?) executes between 1 to 12 times. It is rarely once and rarely the same between clicks. Appears random. The behavior is consistent for all blocks with an associated script. It doesnt occur when using the mouse with other UI components.

dwmblocks: https://github.com/torrinfail/dwmblocks
statuscmd patch: https://dwm.suckless.org/patches/statuscmd/dwmblocks-statuscmd-20210402-96cbb45.diff

This did work at some point (a month ago?), but, unfortunately, I did not note the date of the first occurrence.

What have I done to troubleshoot:

1. Disable all patches except dwmblocks, statuscmd, and tiling and monocle layouts. Issue persists.
2. Swapped mice because I know someone going to ask. :) if it is a mouse issue. Issue persists.
3. Used `xev` to identify if I can *see* multiple clicks per click. Mouse clicks operated as expected via `xev`.
4. Install on a different computer. Issue persists.

My immediate assumption is I did this but I am at a loss where to begin and would love some guidance.

Thank you.

**Comment by rharmonson** [comment]
I do not understand the root cause but I have found a solution.

I upgraded kernels from 4.9 to 5.10 on both test laptops and the symptoms ceased. I hypothesized it was the older kernel, so reboot and select the 4.9 kernel and the symptoms resumed. Reboot, again, to the newer kernel and no further issue.

Closing and apologize for taking any of your time, @bakkeby.

**Comment by bakkeby** [comment]
Can't say that I have heard of anyone having similar issues. Don't know the answer to this one, but I suspect that this did not necessarily have anything to do with repeating mouse clicks. It may have had something to do with the real-time kill signals sent to the dwmblocks process to communicate that a mouse click was triggered.

**Comment by rharmonson** [comment]
I agree.

Using xev, I can demonstrate the each mouse click is only spawning a single event. Well a cycle of events but you get my meaning.

I've come to the same conclusion that it is probably buggy SIGRTMIN support for the 4.9 kernels. I installed the oldest and newest 4.9 kernels on two different computers and the symptom persists. Installed 5.10 and the symptom vanish.

Not conclusive, but.. 

Love dwm-flexipatch and have a wonderful weekend.
