### ISSUE TITLE
Feature request: restoreafterrestart

### ISSUE THREAD

**Issue by acid-bong** [bakkeby/dwm-flexipatch#313]
This patch is dependent on `restartsig`.

- Why `restoreafterrestart` over `preserveonrestart`? It keeps not only the windows on each tag, but the layout order and floating as well (i personally haven't tested it with any layouts other than default ones).
- Why a layout-preserving patch in general? It'll be pretty convenient even after you finished your active ricing phase (when you patch and restart dwm over and over), for example, when you wanna upgrade to the newer upstream commit or fix a minor thing somewhere and is still pedantic over your layouts (like i am).

Also, could you fix the [link](https://dwm.suckless.org/patches/preserveonrestart/) to the patch in the Coggle diagram? it leads to itself instead.

**Comment by bakkeby** [comment]
Have you looked at the seamless restart option?

**Comment by acid-bong** [comment]
God, i'm dumb. Thanks for pointing this one out
