### ISSUE TITLE
Scratchpad windows mispositioned after seamless restart

### ISSUE THREAD

**Issue by UtkarshVerma** [bakkeby/dwm-flexipatch#315]
This is a minor bug with the seamless restart patch. It appears that the `x` coordinate of the scratchpad windows are not restored properly after the restart.

Here's a video showing the bug:
https://user-images.githubusercontent.com/31820255/207599971-78c5aca9-acbc-444b-a3e6-2e33c26d75ce.mp4

**Comment by bakkeby** [comment]
Yes the scratchpad window would end up with a negative x position due to how client windows are hidden in dwm.

Added a fix which seems to work according to my testing. Assumes savefloats of course.

**Comment by UtkarshVerma** [comment]
Thanks, it works now.
