### ISSUE TITLE
Remap tag problem

### ISSUE THREAD

**Issue by spavlovich001** [bakkeby/dwm-flexipatch#321]
I'm remap tag 12345678 --> 123qweasd. Tag switch work fine, but MODKEY|ControlMask+w, MODKEY|ControlMask+s and MODKEY|Mod1Mask+s, MODKEY|Mod1Mask+w not working. MODKEY|ControlMask+{q, e, a, d}, MODKEY|ShiftMask+{q, e, a, d} - working. Why w,s not work?

dwm version == 6.4

```c
        TAGKEYS(                        XK_1,                                  0)
        TAGKEYS(                        XK_2,                                  1)
        TAGKEYS(                        XK_3,                                  2)
        TAGKEYS(                        XK_q,                                  3)
        TAGKEYS(                        XK_w,                                  4)
        TAGKEYS(                        XK_e,                                  5)
        TAGKEYS(                        XK_a,                                  6)
        TAGKEYS(                        XK_s,                                  7)
        TAGKEYS(                        XK_d,                                  8)
```

**Comment by bakkeby** [comment]
Do you happen to be on a laptop?

Laptops typically have a function (`Fn`) key to provide special features to increase or decrease brightness or volume, as well as other things. This isn't so much a separate modifier key, but is likely a combination of modifier keys. In any case when you hit `Fn`+\<key\> then this is sent through to an internal interpreter which will switch out the actual key combination with e.g. `XF86MonBrightnessDown`.

This translation of key presses can also affect other keys. For example on my laptop I can't use `Super`+`Ctrl`+3 as it comes through as some other `XF86` value instead. As far as I know there isn't that much you can do to work around this issue, other than using an external keyboard.

If you are not on a laptop then I'd think that it should work as you do not have any other `XK_w` or `XK_s` bindings in your config. The only thing I can think of that would interfere is if something else (like `sxkcd`) has already reserved those key combinations.

**Comment by spavlovich001** [comment]
> Do you happen to be on a laptop?

No, I do not have a laptop, but a desktop computer. I do not have sxkcd or other program, who intercepts these keys

**Comment by spavlovich001** [comment]
But my keyboard generate this keys(ControlMask|Mod1Mask + {q,w,e, a, s, d})
```
KeyRelease event, serial 32, synthetic NO, window 0x2e00001,
    root 0x25a, subw 0x140009f, time 30128072, (76,912), root:(1133,929),
    state 0x54, keycode 24 (keysym 0x71, q), same_screen YES,
    XLookupString gives 1 bytes: (11) ""
    XFilterEvent returns: False

KeyRelease event, serial 32, synthetic NO, window 0x2e00001,
    root 0x25a, subw 0x140009f, time 30128936, (76,912), root:(1133,929),
    state 0x54, keycode 133 (keysym 0xffeb, Super_L), same_screen YES,
    XLookupString gives 0 bytes:
    XFilterEvent returns: False

KeyPress event, serial 32, synthetic NO, window 0x2e00001,
    root 0x25a, subw 0x140009f, time 30130256, (76,912), root:(1133,929),
    state 0x54, keycode 26 (keysym 0x65, e), same_screen YES,
    XLookupString gives 1 bytes: (05) ""
    XmbLookupString gives 1 bytes: (05) ""
    XFilterEvent returns: False

KeyRelease event, serial 32, synthetic NO, window 0x2e00001,
    root 0x25a, subw 0x140009f, time 30131640, (76,912), root:(1133,929),
    state 0x54, keycode 38 (keysym 0x61, a), same_screen YES,
    XLookupString gives 1 bytes: (01) ""
    XFilterEvent returns: False

KeyRelease event, serial 32, synthetic NO, window 0x2e00001,
    root 0x25a, subw 0x140009f, time 30132048, (76,912), root:(1133,929),
    state 0x54, keycode 133 (keysym 0xffeb, Super_L), same_screen YES,
    XLookupString gives 0 bytes:
    XFilterEvent returns: False

KeyPress event, serial 32, synthetic NO, window 0x2e00001,
    root 0x25a, subw 0x140009f, time 30132616, (76,912), root:(1133,929),
    state 0x54, keycode 40 (keysym 0x64, d), same_screen YES,
    XLookupString gives 1 bytes: (04) ""
    XmbLookupString gives 1 bytes: (04) ""
    XFilterEvent returns: False
```

**Comment by spavlovich001** [comment]
I
