### ISSUE TITLE
Bug: The window border is always active (does not change color) when switching to another window

### ISSUE THREAD

**Issue by spavlovich001** [bakkeby/dwm-flexipatch#325]
The window border is always active (does not change color) when switching to another window. That is, there are two windows, I switch to another window and I have an active border on two windows. Appeared once. I don't know how to reproduce

**Comment by bakkeby** [comment]
Not sure what I can do without being able to reproduce the issue. Sounds like something that would be a fairly rare occurrence.

**Comment by spavlovich001** [comment]
Yes, what you are saying makes perfect sense. Maybe it's a xorg bug, not a dwm bug. But on dwm-6.2 this has not been observed since the release. But maybe I'm wrong:)
