### ISSUE TITLE
Question about using polybar in dwm

### ISSUE THREAD

**Issue by kimuxer** [bakkeby/dwm-flexipatch#331]
I'm not sure if it's a problem with dwm or a problem with polybar-dem-module.
So it's not a bug report.
patch:BAR_ANYBAR_PATCH,BAR_EWMHTAGS_PATCH,IPC_PATCH

When I use the mouse wheel to switch layouts, dwm crashes.
Has anyone encountered this before?Any solution would be greatly appreciated

**Comment by bakkeby** [comment]
Could be a bug. How is this configured? I mean specifically what is being called when you use the mouse wheel?

**Comment by fov95** [comment]
I have all those patches applied, I use polybar-dwm-module and I can't replicate the issue.
Scrolling on polybar to change layouts works fawless, even if I scroll like a maniac.

**Comment by fov95** [comment]
I think I found your issue.
I commented out the "NULL" layout in my build, that's why it doesn't crash for me.
I removed the comment and now dwm is also crashing when I hit the "NULL" layout.

So you can get rid of this by just commenting out the "NULL" layout:
`{ NULL, NULL, {0} },`

**Comment by bakkeby** [comment]
Presumably a conflict between the cyclelayouts patch and however the implementation for polybar via the IPC patch works?

It is possible to implement the cyclelayouts patch / logic without the need for the NULL layout.

**Comment by fov95** [comment]
```
error: module/dwm: Disconnected from socket: [dwmipcpp] Disconnected event socket: Cannot read/write
X connection to :1 broken (explicit kill or server shutdown).
notice: module/dwm: Attempting to reconnect to main socket
error: module/dwm: Failed to reconnect to socket: Failed to connect to dwm ipc socket
error: Invalid action string (action: #dwm.setlayoutsafe.94236125467968, reason: Failed to connect to dwm ipc socket)
```

**Comment by bakkeby** [comment]
The IPC patch naturally exposes that NULL layout through `get_layouts`.

**Comment by bakkeby** [comment]
I applied the above change. Requires that people manually change the NULL, NULL layout from their personal configs of course.

**Comment by kimuxer** [comment]
thanks for all the replies
I'm a newbie to dwm.
I just enable ANYBAR, EWMHTAGS, IPC and other patches in patches.def.h(List all other patches at the end)
Then compile config.mk, cancel the comments related to the IPC patch.
Edit config.def.h file, add { -2 }

`static const BarRule barrules[] = {
	{-2 }，
        ...
};`
build and install

`make && sudo make install`

polybar configuration file
`
enable-layout-scroll = true
`
other patch
`
ATTACHABOVE
AUTORESIZE
CENTER_TRANSIENT_WINDOWS_BY_PARENT
COMBO
COOL_AUTOSTART
CYCLELAYOUTS
DECORATION_HINTS
FAKEFULLSCREEN
FOCUSMASTER
FULLSCREEN
KILLUNSEL
LOSEFULLSCREEN
MOVEPLACE
NODMENU
NO_TRANSPARENT_BORDERS
ONLY_ONE_RULE_MATCH
PERTAG
PLACEMOUSE
RESIZEPOINT
RESTARTSIG
SCRATCHPADS
SEAMLESS_RESTART
SELFRESTART
SHIFTVIEW_CLIENTS
SWAPFOCUS
SWITCHTAG
TOGGLEFULLSCREEN
TOGGLELAYOUT
VANITYGAPS
VIEWONTAG
WARP
WINDOWROLERULE
XRDB
ZOOMFLOATING
FLEXTILE_DELUXE
`

**Comment by kimuxer** [comment]
I'll recompile with the latest commit later today
