### ISSUE TITLE
flextile delux patch - Misalignment

### ISSUE THREAD

**Issue by UserXGnu** [bakkeby/dwm-flexipatch#34]
Hi, Thank you for all the work you put on to build these amazing automation as well as some pretty good patches.

I've noticed however, that the Flextile delux patch, sometimes gets the layouts misaligned, for example:

![ev](https://user-images.githubusercontent.com/2071597/85933494-d9d02e00-b8d7-11ea-9d12-63d15001eeae.png)

I tryed understanding the patch but it is quite hard and as it doesn't have any comment, it becomes really complicated, do you envision refurbishing it in a near future?

Thank you once more.

**Comment by bakkeby** [comment]
Hi @UserXGnu,

the flextile deluxe layout _should_ be more or less pixel perfect, in your screenshot the sizes are a bit all over the place.

Are you sure that you don't just have `resizehints` as 1 in your build? It's enabled by default in dwm (for whatever reason).
```
static const int resizehints = 1;    /* 1 means respect size hints in tiled resizals */
```

\
Thanks,

-Stein

**Comment by UserXGnu** [comment]
Hi Stein, thank you.

However in my config.h, the resizehints variable is already set to 1. Should it then be set to zero?

**Comment by bakkeby** [comment]
Yes, set that to 0 and you should be good. It is also outlined in the (very small) [FAQ](https://dwm.suckless.org/faq/).

**Comment by UserXGnu** [comment]
Oh nice, thank you Bro. And thanks for the work, pretty good.
