### ISSUE TITLE
Compilation Erorr in Freebsd - error: use of undeclared identifier 'SA_NOCLDWAIT'

### ISSUE THREAD

**Issue by crunchymuffins** [bakkeby/dwm-flexipatch#340]
I receive this error message when I run `doas make install`, I am running the default build (only edited the config.mk and Makefile for FreeBsd support). Sorry if this issue is silly. 

```dwm build options:
CFLAGS   = -std=c99 -pedantic -Wall -Wno-unused-function -Wno-deprecated-declarations -Os -I/usr/local/include -I/usr/local/include/freetype2    -D_DEFAULT_SOURCE -D_BSD_SOURCE -D_POSIX_C_SOURCE=200809L -DVERSION="6.4" -DXINERAMA
LDFLAGS  = -L/usr/local/lib -lX11 -lXinerama -lfontconfig -lXft  -lXrender
CC       = cc
cc -c -std=c99 -pedantic -Wall -Wno-unused-function -Wno-deprecated-declarations -Os -I/usr/local/include -I/usr/local/include/freetype2    -D_DEFAULT_SOURCE -D_BSD_SOURCE -D_POSIX_C_SOURCE=200809L -DVERSION=\"6.4\" -DXINERAMA dwm.c
dwm.c:3661:31: error: use of undeclared identifier 'SA_NOCLDWAIT'
        sa.sa_flags = SA_NOCLDSTOP | SA_NOCLDWAIT | SA_RESTART;
                                     ^
dwm.c:3661:46: error: use of undeclared identifier 'SA_RESTART'
        sa.sa_flags = SA_NOCLDSTOP | SA_NOCLDWAIT | SA_RESTART;
                                                    ^
dwm.c:3675:2: warning: implicit declaration of function 'putenv' is invalid in C99 [-Wimplicit-function-declaration]
        putenv("_JAVA_AWT_WM_NONREPARENTING=1");
        ^
1 warning and 2 errors generated.
*** Error code 1

Stop.
make: stopped in /usr/home/anya/pro/dwm-flexipatch```

**Comment by bakkeby** [comment]
Sounds like a genuine issue following https://git.suckless.org/dwm/commit/712d6639ff8e863560328131bbb92b248dc9cde7.html, maybe there is a file that needs to be included on BSD to declare SA_NOCLDWAIT and SA_RESTART.

The `putenv` can probably be skipped for BSD.

**Comment by bakkeby** [comment]
```c
#include <signal.h>
```

That's what is needed for sigaction ref. https://man.freebsd.org/cgi/man.cgi?sigaction and

```c
#include <stdlib.h>
```

is needed for `putenv` ref. https://man.freebsd.org/cgi/man.cgi?query=putenv.

Both includes are there at the start of dwm.c.

**Comment by bakkeby** [comment]
Right, so if you add `-D__XSI_VISIBLE=1` to the `CPPFLAGS` in config.mk then it should compile fine.

`SA_NOCLDWAIT` and `SA_RESTART` are not exposed in `/usr/include/sys/signal.h` if that `__XSI_VISIBLE` is not set. An explanation for this can be seen here:
   - https://stackoverflow.com/questions/61697979/what-is-xsi-visible

**Comment by crunchymuffins** [comment]
c613917 solves this, also the patch from https://lists.suckless.org/dev/2302/35114.html seems to work just as well,

Thanks, Beastie <3
