### ISSUE TITLE
Is vanitygaps supposed to work on a per-monitor basis?

### ISSUE THREAD

**Issue by UtkarshVerma** [bakkeby/dwm-flexipatch#342]
I was just reading the documentation for the [PERTAG patch](https://github.com/bakkeby/dwm-flexipatch/blob/master/patches.def.h#L877), and it mentions that gaps are configured on a per monitor basis by default. This is not actually the case because of the following line.
https://github.com/bakkeby/dwm-flexipatch/blob/master/patch/vanitygaps.c#L87

Both statements are inconsistent with each other, which makes me wonder what the intended behaviour is by default.

**Comment by UtkarshVerma** [comment]
Based on how bars are toggled on a per-monitor basis, I believe it would make sense to have the same for vanitygaps as well. Do you want me to work up a PR for this?

**Comment by bakkeby** [comment]
You are right gaps are enabled globally, not on a per monitor basis. It doesn't make much sense to enable / disable gaps on a per monitor basis, but trivial for someone to add manually if they so desire.

**Comment by UtkarshVerma** [comment]
Thanks
