### ISSUE TITLE
Updating to the latest commit `st` opens as floating by default even on a non floating layout.

### ISSUE THREAD

**Issue by apoorv569** [bakkeby/dwm-flexipatch#344]
I just updated to the latest commit, added/removed some patches. Not sure how but for some reason my `st` terminal opens as floating or not tiled by default I have to force it to tile by the keybind. Here is the list of patches I used https://0x0.st/HsmR.txt

And here is my `config.def.h` file  https://git.sr.ht/~apoorv569/dwm/tree/master/item/config.def.h

I haven't change anything in my config header mostly just added patches, rest I copy paste from my older build keybinds, scratchpad and all.

It is only `st` rest of the programs opens normally.

**Comment by bakkeby** [comment]
I don't know. I'd have thought that it would have something to do with your client rules.

Don't spot anything obvious in your config though.

**Comment by apoorv569** [comment]
> I don't know. I'd have thought that it would have something to do with your client rules.
> 
> Don't spot anything obvious in your config though.

I installed the same build of `dwm` on another machine and have the same problem.

Well I also updated my `st` to the latest build the same day, on the this other machine I first updated `st` and checked if it is working as expected which it did, but then I updated `dwm` and the same problem occurs. You can try my build and see the problem (if you want to reproduce it).

**Comment by apoorv569** [comment]
OK.. I'm encountering other bugs as well like the `Steam` client if launched with `dmenu` does open the `Steam` client but shows a transparent window (I can just see the borders of window) labeled `Error` and also none of the games launches. But if I open it from terminal (`st`) it works fine.

Not sure if its related but my older `dwm` build works fine. I think there is some patch that is causing some issues I suppose. I'll try removing some new patch I added and see if the problem persists.

**Comment by bakkeby** [comment]
Looks like your st issue is because you have included the sizehints patch which makes dwm obey even soft sizehints for new clients. This means that if the program comes through suggesting a size for the window then it will be made floating.

https://dwm.suckless.org/patches/sizehints/

Should be easy enough to revert based on the original patch should you not want this:
https://dwm.suckless.org/patches/sizehints/dwm-sizehints-6.2.diff

**Comment by apoorv569** [comment]
> Looks like your st issue is because you have included the sizehints patch which makes dwm obey even soft sizehints for new clients. This means that if the program comes through suggesting a size for the window then it will be made floating.
> 
> https://dwm.suckless.org/patches/sizehints/
> 
> Should be easy enough to revert based on the original patch should you not want this: https://dwm.suckless.org/patches/sizehints/dwm-sizehints-6.2.diff

Yup, removed this patch, the size issue is now fixed.

**Comment by apoorv569** [comment]
Closing this because it is solved now.
