### ISSUE TITLE
Steam shows error on launch and none of the games work.

### ISSUE THREAD

**Issue by apoorv569** [bakkeby/dwm-flexipatch#345]
After updating to the latest commit, `Steam` shows a error to which if I click `OK` twice it launches but none of the games work as in pressing `Play` button does nothing or tries to launch then after couple of second its back to green for `Play`. Here is a video showing the issue, https://0x0.st/Hzd6.mp4

Sorry I could not show the `Steam` interface because of personal info like account user name and all, but it launches at the end of the video.

I also have `Openbox` installed and `Steam` works fine in that, so this is definitely something to do with `dwm` or some patch I used.

**Comment by bakkeby** [comment]
Besides the error message there isn't that much information to glean from that video.

What we can tell is:
- it is proton that crashes or exits unexpectedly
- it is trying to run d3ddriverquery64.exe
- the version of proton is Proton GE 7-49
- which released on the 6th of February, 2023 \[[ref](https://steamdeckhq.com/news/proton-ge-7-49-released/)\]
- the error dialog box is not visible until picom is killed

Some general debug questions:
- does the error on launch still show if you kill picom before starting steam?
- does the error on launch still show if you run steam via a terminal rather than dmenu?

I can't think of any obvious reason why steam would work in OpenBox and not in dwm.
If you think that it may be due to a patch then it would be very quick to check if this is still an issue in a bare unpatched dwm.

**Comment by apoorv569** [comment]
> Besides the error message there isn't that much information to glean from that video.
> 
> What we can tell is:
> 
>     * it is proton that crashes or exits unexpectedly
> 
>     * it is trying to run d3ddriverquery64.exe
> 
>     * the version of proton is Proton GE 7-49
> 
>     * which released on the 6th of February, 2023 [[ref](https://steamdeckhq.com/news/proton-ge-7-49-released/)]
> 
>     * the error dialog box is not visible until picom is killed

But if proton is crashing it should also crash in openbox as well.
 
> Some general debug questions:
> 
>     * does the error on launch still show if you kill picom before starting steam?
> 
>     * does the error on launch still show if you run steam via a terminal rather than dmenu?
> 
> 
> I can't think of any obvious reason why steam would work in OpenBox and not in dwm. If you think that it may be due to a patch then it would be very quick to check if this is still an issue in a bare unpatched dwm.

I will try these steps and get back to you.

**Comment by bakkeby** [comment]
Something to do with environment variables I'd presume. dmenu is spawned from dwm so it inherits the environment variables from dwm, and dwm in turn inherited the environment variables that were set when dwm started.

**Comment by apoorv569** [comment]
> Something to do with environment variables I'd presume. dmenu is spawned from dwm so it inherits the environment variables from dwm, and dwm in turn inherited the environment variables that were set when dwm started.

I see. I didn't change any thing that could impact stuff related to env vars. Does some patch uses/needs/changes env vars? Its very strange though.

**Comment by bakkeby** [comment]
I wouldn't imagine that you would have done anything specific.

How do you start dwm and openbox?

In openbox how do start dmenu? Preumably via sxhkd I'd imagine.

If it is related to environment variables then it wouldn't be that difficult to check.

Consider the following wrapper script.

```bash
$ cat run_steam.sh
#!/bin/sh

env > ~/the_environment_variables.txt
steam
```

If you run that via dmenu then you have the environment variables dumped to `~/the_environment_variables.txt`. Move this somewhere else then run the script again in openbox and compare the two files.

Are there any specific environment variables that stand out as being missing when you run this via dwm?

(you don't need to actually start steam)

**Comment by apoorv569** [comment]
> I wouldn't imagine that you would have done anything specific.
> 
> How do you start dwm and openbox?

I use `lightdm` with `lightdm-gtk-greeter`. Openbox creates a `.desktop` file itself under `/usr/share/xsessions` and I create one for `dwm`
```
[Desktop Entry]
Name=DWM
Icon=dwm
Exec=dwm
Type=Application
```

> In openbox how do start dmenu? Preumably via sxhkd I'd imagine.

in `rc.xml` I just have a keybind for `dmenu`,
```xml
    <keybind key="A-space">
      <action name="Execute">
        <command>dmenu_run -c -l 15 -p "RUN: "</command>
      </action>
    </keybind>
```

I autostart `steam` and some other stuff in both `openbox` and `dwm` using `~/.config/openbox/autostart.sh` and `~/.dwm/autostart.sh` respectively.

> If it is related to environment variables then it wouldn't be that difficult to check.
> 
> Consider the following wrapper script.
> 
> ```shell
> $ cat run_steam.sh
> #!/bin/sh
> 
> env > ~/the_environment_variables.txt
> steam
> ```
> 
> If you run that via dmenu then you have the environment variables dumped to `~/the_environment_variables.txt`. Move this somewhere else then run the script again in openbox and compare the two files.
> 
> Are there any specific environment variables that stand out as being missing when you run this via dwm?
> 
> (you don't need to actually start steam)

OK, so the result of the script doesn't seems like much of an issue.
```diff
  diff the_environment_variables1.txt the_environment_variables2.txt
2c2
< WINDOWID=33554438
---
> WINDOWID=6291462
7c7
< XDG_SESSION_PATH=/org/freedesktop/DisplayManager/Session5
---
> XDG_SESSION_PATH=/org/freedesktop/DisplayManager/Session4
19c19
< DESKTOP_SESSION=openbox
---
> DESKTOP_SESSION=dwm
24d23
< XDG_SESSION_DESKTOP=openbox
25a25
> XDG_SESSION_DESKTOP=dwm
40a41
> _JAVA_AWT_WM_NONREPARENTING=1
50c51
< STARSHIP_SESSION_KEY=2945212931785118
---
> STARSHIP_SESSION_KEY=2746523139140192
70c71
< XDG_SESSION_ID=17
---
> XDG_SESSION_ID=15
79c80
< GDMSESSION=openbox
---
> GDMSESSION=dwm
```

Doesn't look like any of these could cause some issue.

**Comment by bakkeby** [comment]
That is an odd one indeed. 

To summarise:
- both dwm and openbox launch the same way through light-dm
- dmenu_run is triggered directly by the window manager in both cases
- the environment variables available to dmenu when launched is practically identical in both cases
- when steam is started via dmenu then it starts fine through openbox but runs into errors when using dwm
- but starting steam from a terminal in dwm makes it launch fine

If it would have something to do with window reparenting then one would expect it to fail the same way when started via a terminal. 

Wonder if anyone else have had similar issues.

**Comment by bakkeby** [comment]
Does this still happen with an unpatched dwm? I.e. clone from the suckless site.

**Comment by knotu** [comment]
While looking for something completely unrelated, I saw this and wanted to mention that I also had this issue starting around a month ago. It seems to have corrected itself, likely through an update in Arch at some point.

Worth mentioning that I was not using your dwm-flexipatch. I was using dwm cloned from the suckless site. 

The issue was almost exactly as they described. If I started steam through dmenu, while using the bind in dwm, the games using proton wouldn't launch. They would exit immediately. 

While still in dwm, if I used xbindkeys or sxhkd to run dmenu, I could launch steam and had no issues with the games.

I wish i could be more helpful than that. I got busy and would just use sxhkd to run dmenu, instead of trying to fix it. Seeing this post made me check to see if the issue still persists, but as I said at the start, it's working again. I believe there is a post on the dwm subreddit where others have or had this issue.

**Comment by apoorv569** [comment]
> Does this still happen with an unpatched dwm? I.e. clone from the suckless site.

OK, I installed vanilla `dwm`, `dmenu` and `st`. First time I logged into `dwm` (vanilla) `steam` worked fine. After logging out and logging back again `dmenu` won't show anything (no binaries) just appears blank. Same in `openbox`. Is `dmenu` not able to `read` `$PATH` for some reason?

> While looking for something completely unrelated, I saw this and wanted to mention that I also had this issue starting around a month ago. It seems to have corrected itself, likely through an update in Arch at some point.
> 
> Worth mentioning that I was not using your dwm-flexipatch. I was using dwm cloned from the suckless site.
> 
> The issue was almost exactly as they described. If I started steam through dmenu, while using the bind in dwm, the games using proton wouldn't launch. They would exit immediately.
> 
> While still in dwm, if I used xbindkeys or sxhkd to run dmenu, I could launch steam and had no issues with the games.
> 
> I wish i could be more helpful than that. I got busy and would just use sxhkd to run dmenu, instead of trying to fix it. Seeing this post made me check to see if the issue still persists, but as I said at the start, it's working again. I believe there is a post on the dwm subreddit where others have or had this issue.

Thanks for sharing. Actually I use this exact same build for `dwm`, `dmenu` and `st` I have on my laptop as well and same distro as well (Arch) and it works fine. No issues with `steam` or anything. It is indeed strange.

**Comment by apoorv569** [comment]
> While looking for something completely unrelated, I saw this and wanted to mention that I also had this issue starting around a month ago. It seems to have corrected itself, likely through an update in Arch at some point.
> 
> Worth mentioning that I was not using your dwm-flexipatch. I was using dwm cloned from the suckless site.
> 
> The issue was almost exactly as they described. If I started steam through dmenu, while using the bind in dwm, the games using proton wouldn't launch. They would exit immediately.
> 
> While still in dwm, if I used xbindkeys or sxhkd to run dmenu, I could launch steam and had no issues with the games.
> 
> I wish i could be more helpful than that. I got busy and would just use sxhkd to run dmenu, instead of trying to fix it. Seeing this post made me check to see if the issue still persists, but as I said at the start, it's working again. I believe there is a post on the dwm subreddit where others have or had this issue.

Thanks for sharing. Actually I use this exact same build for `dwm`, `dmenu` and `st` I have on my laptop as well and same distro as well (Arch) and it works fine. No issues with `steam` or anything. It is indeed strange.

**Comment by bakkeby** [comment]
https://www.reddit.com/r/suckless/comments/129jda6/dwm_dmenu_steam_proton_not_working/ sounds pretty similar, there it was suggested that reverting commit [712d6639ff8e863560328131bbb92b248dc9cde7](https://git.suckless.org/dwm/commit/712d6639ff8e863560328131bbb92b248dc9cde7.html) solved the issue. That would be commit [91551329e93e794001b04459a4399c074f4cf7ae](https://github.com/bakkeby/dwm-flexipatch/commit/91551329e93e794001b04459a4399c074f4cf7ae) of dwm-flexipatch.

**Comment by bakkeby** [comment]
This issue should be fixed with this upstream commit:
https://git.suckless.org/dwm/commit/e81f17d4c196aaed6893fd4beed49991caa3e2a4.html

Commit comment:
> restore SIGCHLD sighandler to default before spawning a program
> 
> From sigaction(2):
> A child created via fork(2) inherits a copy of its parent's signal dispositions.
> During an execve(2), the dispositions of handled signals are reset to the default;
> the dispositions of ignored signals are left unchanged.
> 
> This refused to start directly some programs from configuring in config.h:
> 
> ```c
> static Key keys[] = {
> 	MODKEY,                       XK_o,      spawn,          {.v = cmd } },
> };
> ```
> 
> Some reported programs that didn't start were: mpv, anki, dmenu_extended.
> 
> Reported by pfx.
> Initial patch suggestion by Storkman.

Incorporated into dwm-flexipatch with commit:
https://github.com/bakkeby/dwm-flexipatch/commit/ace6f1cd88c4be23460415a815e0d29bfb7d7f07

**Comment by apoorv569** [comment]
> This issue should be fixed with this upstream commit: https://git.suckless.org/dwm/commit/e81f17d4c196aaed6893fd4beed49991caa3e2a4.html
> 
> Commit comment:
> 
> > restore SIGCHLD sighandler to default before spawning a program
> > From sigaction(2):
> > A child created via fork(2) inherits a copy of its parent's signal dispositions.
> > During an execve(2), the dispositions of handled signals are reset to the default;
> > the dispositions of ignored signals are left unchanged.
> > This refused to start directly some programs from configuring in config.h:
> > ```c
> > static Key keys[] = {
> > 	MODKEY,                       XK_o,      spawn,          {.v = cmd } },
> > };
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Some reported programs that didn't start were: mpv, anki, dmenu_extended.
> > Reported by pfx.
> > Initial patch suggestion by Storkman.
> 
> Incorporated into dwm-flexipatch with commit: [ace6f1c](https://github.com/bakkeby/dwm-flexipatch/commit/ace6f1cd88c4be23460415a815e0d29bfb7d7f07)

Hey, sorry I got busy. I just pulled the latest changes and re-built `dwm`. Doesn't look like it solved the issue.
