### ISSUE TITLE
Error compiling, without even patching anything?

### ISSUE THREAD

**Issue by Sincide** [bakkeby/dwm-flexipatch#347]
Hi, so I'm getting an error when compiling without even adding any extra patches, just a fresh git clone gives me errors:

`sudo make clean install
rm -f dwm drw.o dwm.o util.o dwm-6.4.tar.gz
rm -f dwm-msg
dwm build options:
CFLAGS   = -std=c99 -pedantic -Wall -Wno-unused-function -Wno-deprecated-declarations -Os -I/usr/X11R6/include -I/usr/include/freetype2    -D_DEFAULT_SOURCE -D_BSD_SOURCE -D__XSI_VISIBLE=1 -D_POSIX_C_SOURCE=200809L -DVERSION="6.4" -DXINERAMA
LDFLAGS  = -L/usr/X11R6/lib -lX11 -lXinerama -lfontconfig -lXft  -lXrender
CC       = cc
cc -c -std=c99 -pedantic -Wall -Wno-unused-function -Wno-deprecated-declarations -Os -I/usr/X11R6/include -I/usr/include/freetype2    -D_DEFAULT_SOURCE -D_BSD_SOURCE -D__XSI_VISIBLE=1 -D_POSIX_C_SOURCE=200809L -DVERSION=\"6.4\" -DXINERAMA drw.c
cc -c -std=c99 -pedantic -Wall -Wno-unused-function -Wno-deprecated-declarations -Os -I/usr/X11R6/include -I/usr/include/freetype2    -D_DEFAULT_SOURCE -D_BSD_SOURCE -D__XSI_VISIBLE=1 -D_POSIX_C_SOURCE=200809L -DVERSION=\"6.4\" -DXINERAMA dwm.c
cc -c -std=c99 -pedantic -Wall -Wno-unused-function -Wno-deprecated-declarations -Os -I/usr/X11R6/include -I/usr/include/freetype2    -D_DEFAULT_SOURCE -D_BSD_SOURCE -D__XSI_VISIBLE=1 -D_POSIX_C_SOURCE=200809L -DVERSION=\"6.4\" -DXINERAMA util.c
cc -o dwm drw.o dwm.o util.o -L/usr/X11R6/lib -lX11 -lXinerama -lfontconfig -lXft  -lXrender
mkdir -p /usr/local/bin
cp -f dwm /usr/local/bin
#cp -f patch/dwmc /usr/local/bin
chmod 755 /usr/local/bin/dwm
mkdir -p /usr/local/share/man/man1
sed "s/VERSION/6.4/g" < dwm.1 > /usr/local/share/man/man1/dwm.1
chmod 644 /usr/local/share/man/man1/dwm.1
mkdir -p /usr/local/share/xsessions
cp -n dwm.desktop /usr/local/share/xsessions
make: *** [Makefile:63: install] Error 1`

Any ideas?

I tried a fresh git clone of DWM from suckless as well, that does not give the makefile error.

BR,
M

**Comment by bakkeby** [comment]
You are using arch, btw.

Core utils were updated recently with one of the side effects being that `cp -n` (no-clobber, i.e. don't copy if the file already exists) now gives an error exit code if the file was not copied. So make now treats this as a critical failure.

It is the least step in the build process so it doesn't make any practical difference, but it sure is misleading.

You can add a hyphen before the command (`-cp -n`) which will allow make to ignore the error, but it will still report the error just adding the text "(ignored)" after it. 

I can work around the issue by using the command of `test -f <file> || cp dwm.desktop <path>`

Having to do it that way kind of defeats the purpose of the no-clobber option of course. I suspect that the change was not intentional.

**Comment by bakkeby** [comment]
The ignore error option:

```diff
diff --git a/Makefile b/Makefile
index 65c9b5a..4b42558 100644
--- a/Makefile
+++ b/Makefile
@@ -66,7 +66,7 @@ endif
        sed "s/VERSION/${VERSION}/g" < dwm.1 > ${DESTDIR}${MANPREFIX}/man1/dwm.1
        chmod 644 ${DESTDIR}${MANPREFIX}/man1/dwm.1
        mkdir -p ${DESTDIR}${PREFIX}/share/xsessions
-       cp -n dwm.desktop ${DESTDIR}${PREFIX}/share/xsessions
+       -cp -n dwm.desktop ${DESTDIR}${PREFIX}/share/xsessions
        chmod 644 ${DESTDIR}${PREFIX}/share/xsessions/dwm.desktop

 uninstall:
```

```sh
$ sudo make install
dwm build options:
CFLAGS   = -std=c99 -pedantic -Wall -Wno-unused-function -Wno-deprecated-declarations -Os -I/usr/X11R6/include -I/usr/include/freetype2    -D_DEFAULT_SOURCE -D_BSD_SOURCE -D__XSI_VISIBLE=1 -D_POSIX_C_SOURCE=200809L -DVERSION="6.4" -DXINERAMA
LDFLAGS  = -L/usr/X11R6/lib -lX11 -lXinerama -lfontconfig -lXft  -lXrender
CC       = cc
mkdir -p /usr/local/bin
cp -f dwm /usr/local/bin
#cp -f patch/dwmc /usr/local/bin
chmod 755 /usr/local/bin/dwm
mkdir -p /usr/local/share/man/man1
sed "s/VERSION/6.4/g" < dwm.1 > /usr/local/share/man/man1/dwm.1
chmod 644 /usr/local/share/man/man1/dwm.1
mkdir -p /usr/local/share/xsessions
cp -n dwm.desktop /usr/local/share/xsessions
make: [Makefile:63: install] Error 1 (ignored)
chmod 644 /usr/local/share/xsessions/dwm.desktop
```

The test option:

```diff
diff --git a/Makefile b/Makefile
index 65c9b5a..a4eb07e 100644
--- a/Makefile
+++ b/Makefile
@@ -66,7 +66,7 @@ endif
        sed "s/VERSION/${VERSION}/g" < dwm.1 > ${DESTDIR}${MANPREFIX}/man1/dwm.1
        chmod 644 ${DESTDIR}${MANPREFIX}/man1/dwm.1
        mkdir -p ${DESTDIR}${PREFIX}/share/xsessions
-       cp -n dwm.desktop ${DESTDIR}${PREFIX}/share/xsessions
+       test -f ${DESTDIR}${PREFIX}/share/xsessions/dwm.desktop || cp dwm.desktop ${DESTDIR}${PREFIX}/share/xsessions
        chmod 644 ${DESTDIR}${PREFIX}/share/xsessions/dwm.desktop

 uninstall:
```

```sh
$ sudo make install
dwm build options:
CFLAGS   = -std=c99 -pedantic -Wall -Wno-unused-function -Wno-deprecated-declarations -Os -I/usr/X11R6/include -I/usr/include/freetype2    -D_DEFAULT_SOURCE -D_BSD_SOURCE -D__XSI_VISIBLE=1 -D_POSIX_C_SOURCE=200809L -DVERSION="6.4" -DXINERAMA
LDFLAGS  = -L/usr/X11R6/lib -lX11 -lXinerama -lfontconfig -lXft  -lXrender
CC       = cc
mkdir -p /usr/local/bin
cp -f dwm /usr/local/bin
#cp -f patch/dwmc /usr/local/bin
chmod 755 /usr/local/bin/dwm
mkdir -p /usr/local/share/man/man1
sed "s/VERSION/6.4/g" < dwm.1 > /usr/local/share/man/man1/dwm.1
chmod 644 /usr/local/share/man/man1/dwm.1
mkdir -p /usr/local/share/xsessions
test -f /usr/local/share/xsessions/dwm.desktop || cp dwm.desktop /usr/local/share/xsessions
chmod 644 /usr/local/share/xsessions/dwm.desktop
```

**Comment by Sincide** [comment]
Thanks alot!
No errors now, using the "test" option.
