### ISSUE TITLE
`holdbar` only when bar is hidden using `togglebar`

### ISSUE THREAD

**Issue by chhajedji** [bakkeby/dwm-flexipatch#35]
Hello,

Can you help me to modify holdbar patch to get into effect only when I have used  `togglebar` to hide status bar and always show status bar when bar is visible using `togglebar`? Holdbar patch is very useful but sometimes I need to see details on status bar constantly and that time `togglebar` doesn't show status bar and it is too tedious to hold down a key constantly. 

By looking at this repo, I though you could be the right person. Please suggest something. Thanks in advance! :)

Extra information
I use a custom bar using `xsetroot`.

**Comment by bakkeby** [comment]
Can't you just do the default `MOD+b` shortcut to trigger `togglebar`?

As for having the bar show by default just keep the `showbar` config enabled.
```
static const int showbar                 = 1;   /* 0 means no bar */
```

Pressing and releasing the holdbar key hides the bar again. You can trigger `togglebar` to make the bar show constantly again.

That's at least how it works in my build. As far as I can see I haven't made any changes in this respect.

**Comment by chhajedji** [comment]
Thanks for the quick reply.

I tried to trigger `togglebar` again to show bar but it wasn't working for me. Once `togglebar` hides the bar, it is only shown when `MODKEY` key is pressed. [Here](https://github.com/chhajedji/dwm#patches) is a list of patches I have used. Could something be missing or misfiring in them?

**Comment by bakkeby** [comment]
Could it be because you have set the HOLDKEY as Super_L, same as MODKEY?
```
#define HOLDKEY 0xffeb
```

You can set the holdkey to something like `MOD+n` if you want.

**Comment by bakkeby** [comment]
Btw, I like your activetagindicatorbar showing at the bottom, might grab that.

**Comment by chhajedji** [comment]
> Could it be because you have set the HOLDKEY as Super_L, same as MODKEY?
> 
> ```
> #define HOLDKEY 0xffeb
> ```
> 
> You can set the holdkey to something like `MOD+n` if you want.

Oh yes, this was it.
 But if I change the `HOLDKEY` to something other than `Super_L` then I would defeat the purpose of having this patch! I wanted this patch so that I can hide bar most of the time and only see it when changing tags. And of course when I need to monitor something on the bar (that's where `togglebar` comes into play). Is there any other way or workaround other than mapping to something other than `MODKEY`?

**Comment by bakkeby** [comment]
In the `holdbar` function it starts like this:

```
void
holdbar(const Arg *arg)
{
    selmon->showbar = 1;
...
```

Try changing that to:
```
void
holdbar(const Arg *arg)
{
    if (selmon->showbar)
        return;
    selmon->showbar = 1;
```

**Comment by chhajedji** [comment]
Nope, didn't work :/

**Comment by bakkeby** [comment]
I _think_ it should prevent the bar from disappearing if it is already enabled (i.e. on startup), i.e. if it is shown in full you can do `MOD+4` to change tag and the bar should not disappear (unless I am missing something).

That said you may need a non-Super keybinding to toggle the bar on and off.

Actually one thing you may want to try as well is inside `keyrelease` you have:

```
...
    if (e->xkey.keycode == XKeysymToKeycode(dpy, HOLDKEY)) {
        selmon->showbar = 0;
...
```

I'm not 100% sure if this will work, but you could try changing it into:

```
...
    if (e->xkey.keycode == XKeysymToKeycode(dpy, HOLDKEY)) {
        selmon->showbar = !selmon->showbar;
...
```

Actually I'll try this myself and get back to you.

**Comment by bakkeby** [comment]
That actually works beautifully, just also change your `togglebar` function to be simply this:

```
void
togglebar(const Arg *arg)
{
	selmon->showbar = !selmon->showbar;
}
```

**Comment by chhajedji** [comment]
This is working somewhat how I wanted. Problems I am facing after these changes is when bar is visible and I press mod key to do any other thing, bar disappears. What can I do to avoid this? 😅

It looks like I am troubling you a lot even though you do not have to do anything with this patch! But I couldn't find any other better source for my queries. So thanks for the help you are providing. I actually had been following since quite some time and you also suggested me tagswapmon on reddit. So thought you could help with this patch also!


--

Regards,
Chinmay Chhajed
________________________________

**Comment by bakkeby** [comment]
No worries. I should have something for you soon.

**Comment by bakkeby** [comment]
OK, this looks like what you'll have to do:

In `holdbar` change this:

```
 void
 holdbar(const Arg *arg)
 {
-       selmon->showbar = 1;
+       if (selmon->showbar)
+               return;
+       selmon->showbar = 2;
        updateholdbarpos(selmon);
...
```

in `keyrelease` change this:

```
...
-       if (e->xkey.keycode == XKeysymToKeycode(dpy, HOLDKEY)) {
+       if (e->xkey.keycode == XKeysymToKeycode(dpy, HOLDKEY) && selmon->showbar == 2) {
...
```

in `togglebar` change this:

```
togglebar(const Arg *arg)
{
-       selmon->showbar = !selmon->showbar;
+       if (selmon->showbar == 2)
+               selmon->showbar = 1;
+       else
+               selmon->showbar = !selmon->showbar;
...
}
```

you don't, but if you were to have the pertagbar patch then it would still work - just that it would be very unpractical and unintuitive to use when combined with holdbar.

Another side effect of using holdbar worth noting is that if you use it with the super key, as in this case, then dwm will effectively block external applications such as `sxhkd` from using it.

**Comment by chhajedji** [comment]
Thanks a lot! These changes are working as expected. I also use  pertag patch and it is in sync without any error (known until now!).
Thanks again for the help. :smiley:

**Comment by chhajedji** [comment]
It would be great if you could add this at official dwm patches as many people would want this feature. It was a default behavior I expected after applying holdbar patch.

**Comment by bakkeby** [comment]
Yes that's an idea. I added that now, will likely be up on the site within a week.

**Comment by antoniomokuzai** [comment]
patch -p1 fails on this dwm-holdbar-modkey-6.2 patch, I had a quick look at it, it wasn't obvious why patch -p1 would fail, can you please have a look?

My system is gentoo, I put dwm patches in a local overlay that has higher priority than the official portage tree, which has been working great for all the dwm patches I have been using, until this one.

Thanks.

**Comment by bakkeby** [comment]
@antoniomokuzai you mean

```bash
$ git status
HEAD detached at 6.2
nothing to commit, working tree clean

$ git apply ~/path/to/dwm-holdbar-modkey-6.2.diff
$ git status
HEAD detached at 6.2
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   config.def.h
	modified:   dwm.c

no changes added to commit (use "git add" and/or "git commit -a")
```
vs
```bash
$ git status
HEAD detached at 6.2
nothing to commit, working tree clean

$ patch -p1 < ~/path/to/dwm-holdbar-modkey-6.2.diff
patching file config.def.h
patching file dwm.c
$ git status
HEAD detached at 6.2
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   config.def.h
	modified:   dwm.c

no changes added to commit (use "git add" and/or "git commit -a")
```

Both work fine, even on the latest master.

Most likely you have applied other patches which means that the patch can not be applied cleanly. In general I recommend applying patches manually by hand even if it takes a lot more time to do - you learn practically nothing from using `patch` or `git apply`.
