### ISSUE TITLE
Differences between vanilla dwm and flexipatch given the same patches

### ISSUE THREAD

**Issue by niels0n** [bakkeby/dwm-flexipatch#352]
Hi, sorry if this might be already answered somewhere but I'm trying to troubleshoot a problem I have and I can't understand it clearly.
So I have a flexipatch build, with only three patches enabled (besides the defaults, which I haven't touched) which are systray, autostart and actualfullscreen and it works without any problem.
I created an identical build of vanilla dwm applying the same patches, nothing more and nothing less, but there's a couple problems: strange behaviour of mpv windows, systray less polished, but the main issue is that while on flexipatch's build I can just start music with `playerctl play-pause`, on the vanilla build this command can't find any player. It works only if I run it with `exec dbus-launch --autolaunch=$(cat /var/lib/dbus/machine-id)` instead of `exec dbus-run-session`, but then it throws in other problems so it's not a solution.
So it seems like the vanilla one has something missing, and therefore flexipatch is doing...something more with dbus by default, but I really can't understand what. So can you help me understand what are the differences between the two, given obviously the same patches? What is flexipatch's build doing differently?

**Comment by bakkeby** [comment]
I saw your [reddit post](https://www.reddit.com/r/suckless/comments/137waqi/dbus_related_problem_only_with_dwm/) and thought it would be interesting if someone had some insight when it came to your specific problem.

In principle the window manager, be that dwm, dwm-flexipatch, bspwm, awesome, and so on, does not actually have anything to do with dbus. The main point is to have a dbus session for the current display. There are some differences between dwm and dwm-flexipatch, but nothing that should affect this.

If you are using a linux distribution that has systemd then the dbus session daemon will typically be started by systemd when you start your X session.

If you are on a distribution that does not have systemd, e.g. Artix Linux, then you need to start the dbus session daemon yourself should you need it.

There are two ways to do this; via [dbus-run-session](https://dbus.freedesktop.org/doc/dbus-run-session.1.html) and [dbus-launch](https://dbus.freedesktop.org/doc/dbus-launch.1.html). Both are worth a read through.

The line that I have seen most often is:
```sh
exec dbus-launch dwm
```
but I have also seen:
```sh
exec dbus-run-session dwm
```

Another method ref. [this reddit post](https://www.reddit.com/r/suckless/comments/xzih9l/comment/irnnkym/?utm_source=share&utm_medium=web2x&context=3):

> You have to start dbus before batterynotif and then import its environment. I'm on Debian so the scripts which ship with OS might be different, but I basically run `[ -z "$DBUS_SESSION_BUS_ADDRESS" ] && eval $(/usr/bin/dbus-launch --exit-with-session --sh-syntax)` and then just before wm: `dbus-update-activation-environment --verbose --all.` This last step might be different or even unnecessary for you; I'm not familiar with openrc and use systemd which adds its part to the complexity of my init setup.
> 
> Of course you then simply `exec dwm` instead of running it through that dbus script.

This superuser post also explains all of this well in my opinion:
- https://superuser.com/questions/1730756/running-standalone-window-manager-without-a-d-bus-session-in-linux

In my case dbus is started by systemd and I have never run my window manager through dbus-launch or dbus-run-session.

**Comment by niels0n** [comment]
Hey, thanks for the reply.
I'm on Void so I'm not using systemd. I launch dbus setting `exec dbus-run-session $@` in `/etc/lightdm/Xsession` since I'm using Lightdm, but I have tried simple `startx` putting the line in `.xinitrc` too and it's the same thing.

Now I'm not sure what's happening but the problem seems to be between vanilla dwm and playerctl: if I start the session using just `exec $@`, playerctl works correctly. Everything else doesn't though, so thunar, pipewire, and everything that needs dbus is broken, with playerctl being the only exception. Launching the session with `dbus-run-session $@` it's the other way around, so I might just find a hack for launching playerctl, but at this point I'd like to understand better what's happening, since bspwm and flexipatch's dwm works perfectly fine with `dbus-run-session $@`.

So it's like playerctl doesn't recognize the dbus launch, unless it's launched it a specific way that works for it but not for the other programs...I don't know, but it has to be something that vanilla dwm is doing differently. This is very odd.

I tried every line you suggested, but sadly none of them worked.

**Comment by niels0n** [comment]
Actually I just found out something: this is not vanilla dwm that can't start playerctl properly, as I was saying. I was trying to start `mpd`, which is in my autostart ad I always control with playerctl and it can't detect any player. But if I start playing something on firefox, or mpv, or anything else it works...

Starting mpd with other players it works fine...

So the problem is vanilla dwm with playerctl that can't detect mpd lol

Anyway I see that this maybe is becoming too much specific. Even if it is related to flexipatch in a way, because there's still something that it is doing differently from vanilla, if you want to close this I understand, since it's so specific that I don't even know where to ask and I'm not sure this is the proper place and flexipatch works perfectly, so it is not really a problem with it.

**Comment by niels0n** [comment]
Okay, the issue is that, even if I have it in my autostart, for some reason vanilla dwm doesn't actually launch `mpDris2`, while all the other wm do.
If I manually launch the command after login, it works. Now I just have to find out why and how to make it  actually launch it, but at least I found the problem.
Thank you very much and sorry to have bothered you.

**Comment by bakkeby** [comment]
So how do you actually autostart mpd then?

**Comment by niels0n** [comment]
I just put 
`mpd &`
`mpDris2 &`
in `~/.local/share/dwm/autostart` (or in `~/.xprofile` if using vanilla since there I removed the autostart patch and I autostart like this). Mpd is fine though, it's mpDris2 that on vanilla starts only if I launch it manually.

I'm pretty lost tbh, I'm just giving up on vanilla and using flexipatch, but if you have any idea I'd really appreciate it

**Comment by bakkeby** [comment]
> in ~/.local/share/dwm/autostart (or in ~/.xprofile if using vanilla since there I removed the autostart patch and I autostart like this). 

That might just be the issue then.

```sh
mpd &
mpDris2 &
```

The above starts mpd and mpDris2 as background processes. As you are including this in `~/.xprofile` (or `~/.xinitrc`) the programs may start before the dbus session has been set up and therefore keep running without registering.

Let's say that you have these commands in your `~/.local/share/dwm/autostart` file. When this is being run by dwm the dbus session has already been set up.

As an experiment you could try to add a `sleep 2` at the start of that autostart script and from your `~/.xprofile` you could start that script, e.g.

```sh
~/.local/share/dwm/autostart &
```

The idea being that dwm would start with the dbus session first and the mpd and mpDris2 being started after a delay of two secons. If this works then it is just a race condition between mpd / mpDris2 starting and the dbus session starting.

Alternatively you could also have a look at the [cool autostart](https://dwm.suckless.org/patches/cool_autostart/) patch for dwm.

**Comment by bakkeby** [comment]
No the source code just have to live somewhere, the IPC code as well as other patch code won't be included during compile time.

Given that the `sleep 10` didn't work then it may be related to environment variables that are not present when mpDris2 starts. Likely this environment variable in particular.

```sh
$ env | grep DBUS
DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus
```

I suppose that is what the `dbus-update-activation-environment --verbose --all` is setting in the example from the reddit post. If this is set before mpDris2 is started then I'd expect it to work.

**Comment by niels0n** [comment]
> As per the reddit suggestion you would have something like this in your ~/.xprofile or ~/.xinitrc:

Okay this time it worked perfectly!! I'm not sure what this command is actually doing and why it works, but it does so thank you!

Also, can I make a little donation to you? I'd happy to if you have a link, since flexipatch is so well done and it's been very important for me and your help here has been essential.

**Comment by bakkeby** [comment]
Don't worry about donation :)

>  I'm not sure what this command is actually doing and why it works

We can break it down to understand it better.

```sh
[ -z "$DBUS_SESSION_BUS_ADDRESS" ]
```
^ check that the environment variable DBUS_SESSION_BUS_ADDRESS does not exist or is an empty string

```sh
&&
```
^ if that is the case then

```sh
eval $(/usr/bin/dbus-launch --exit-with-session --sh-syntax)
```
^ run dbus-launch with the arguments:
- \-\-exit-with-session to make the dbus daemon exit when the X11 session exits and
- \-\-sh-syntax to make the dbus-launch output shell commands to set the environment variables

Example output:
```sh
$ /usr/bin/dbus-launch --exit-with-session --sh-syntax
DBUS_SESSION_BUS_ADDRESS='unix:path=/tmp/dbus-usoHAsmVur,guid=9d2c6c22c999c75b9651df3164560634';
export DBUS_SESSION_BUS_ADDRESS;
DBUS_SESSION_BUS_PID=1255973;
```

The `eval` is to evaluate the shell commands that dbus-launch outputs, making the environment variable DBUS_SESSION_BUS_ADDRESS set for the current process.

NB: the [dbus-launch](https://dbus.freedesktop.org/doc/dbus-launch.1.html) page recommends using \-\-exit-with-x11 over \-\-exit-with-session.

```sh
dbus-update-activation-environment --verbose --all
```
^ runs [dbus-update-activation-environment](https://dbus.freedesktop.org/doc/dbus-update-activation-environment.1.html) to update the list of environment variables used by the dbus daemon session. This includes more environment variables than what dbus-launch outputs as far as I understand.

```sh
mpd &
mpDris2 &
```
^ mpd and mpDris2 are started as background processes, inheriting the environment variables of the current process

```sh
exec dwm
```
^ replace the current process with the dwm binary

-----

Comparing to the other method:

```sh
mpd &
mpDris2 &
```
^ mpd and mpDris2 are started as background processes, inheriting the environment variables of the current process (DBUS_SESSION_BUS_ADDRESS and other environment variables have not been set yet)

```sh
exec dbus-launch dwm
```
^ replace the current process with the dbus-launch script; the dwm command is later executed as part of that script

**Comment by niels0n** [comment]
Thank you, now it's much more clear!
I have just two more questions:

1. since 

> the dbus-launch page recommends using --exit-with-x11 over --exit-with-session

should I replace it?

2. Do you know why this needs to be done only with vanilla dwm? On bspwm, flexipatch-dwm and other this is done automatically or there's another reason for it not being necessary?

**Comment by bakkeby** [comment]
Whether to replace it is entirely up to you. In this context it probably makes no difference. The difference between the two is just what happens if a connection with X11 can't be established, in which one bails while the other tries to monitor the parent process.

As for why this is needed for vanilla dwm I don't know. I'd assume this would be needed for any window manager if you start the processes before initialising the dbus session. If you autostart programs after the window manager starts then they will start after the dbus session has started.

**Comment by niels0n** [comment]
Got it, thank you so much again! :)
