### ISSUE TITLE
Enabling systray patch not displaying tray

### ISSUE THREAD

**Issue by FuriousGamer1356** [bakkeby/dwm-flexipatch#356]
Here's my steps to reproduce this:
1. Clone this repo
2. Enable `systray` patch in `patches.h`
3. Run `sudo make install`
4. Restart dwm

After I did those exact things, the tray does not appear in the bar. Am I missing something?

**Comment by bakkeby** [comment]
Are you missing programs that have systay icons perhaps? Does it appear if you run `nm-applet` for example?

**Comment by FuriousGamer1356** [comment]
That was it, I didn't have any programs running that created a system tray icon. Sorry for wasting your time!
