### ISSUE TITLE
dwmblocks commands issue

### ISSUE THREAD

**Issue by los95** [bakkeby/dwm-flexipatch#36]
Hi, I recently updated my dwm build with your files and noticed something odd. For some reason, the module that's at the far right can only be clicked while the other modules are ignored. I tried looking around for a solution but couldn't get it. This used to work on an earlier build of yours. I don't know if has to do with the barrules that is in the dwm.c file. Thanks for reading!

**Comment by los95** [comment]
*Update, I noticed that changing the update signal on a module gives it the clicking ability. The signal has a smaller value than the rest of the modules as well but for some reason ignores values 1 and 2.

**Comment by bakkeby** [comment]
Can you give a practical example? What does your dwmblocks config.h look like?

**Comment by los95** [comment]
For example, I have a volume and a date module on. If I open dwmblocks on a terminal and click on the volume module, it will read the date on instead. However, if I make volume's signal value lower than date, then it will work. Both modules appear on the bar but only one of them has clicking capabilities for some reason. 

There are a lot of patches I have on sorry in advance. I have dwmblocks, ltsymbol, bar status, statusbutton, statuscmd, systray, tags, wintitle, title left pad, title right pad, alpha, dmenuatchtop, ewmhtags, hidevacanttags, ignore xft errors, statuscolors, titlecolor, vtcolors, attatchaside, autostart, autoresize, cfacts, cmdcustomize, combo, cyclelayouts, dragcfact, dragmfact, dwmc, float_border_color, floatpos, fsignal, inplacerotate, killunsel, mpdcontrol, movesstack, noborder, nodmenu, push, resizecorners, restartsig, scratchpads, selfrestart, setborderpx, sticky, swaptags, togglefullscreen, urgentborder, vanitygaps, windowrolerule, xrdb, and zoom patches. I also have all the layouts on.

**Comment by los95** [comment]
This my config.h

//Modify this file to change what commands output to your statusbar, and recompile using the make command.
static const Block blocks[] = {
	/*Icon*/	/*Command*/		/*Update Interval*/	/*Update Signal*/
	//{"Mem:", "free -h | awk '/^Mem/ { print $3\"/\"$2 }' | sed s/i//g",	30,		0},

	//{"", "date '+%b %d (%a) %I:%M%p'",					5,		0},
	//{"",	"music.sh",								1,				11},
	//{"",	"memory",								10,				7},
	{"",	"clock",								30,				0},
	{"",	"volume",								1,				5},
};

//sets delimeter between status commands. NULL character ('\0') means no delimeter.
static char *delim = "|";
static unsigned int delimLen = 3;

**Comment by bakkeby** [comment]
OK, that is a bit weird.

You use signal 0 for the clock script, which means "do not use a signal for this script", so I'd expect to only see clicks for the volume coming through.

If no signal can be found in the status then the first script in the list will get the signal. I have played around, but I can't replicate this behaviour.

This may sound stupid, but are you sure that you don't have the same date click output in the volume script due to copy-paste? I once lost an hour debugging button clicks because I had the wrong text in a notify-send command :)

**Comment by los95** [comment]
That's interesting since I saw someone's config with 0 on their clock script but then again I don't know a lot on signals. 

The scripts are different from each other. Here are the volume and clock scripts.
[https://pastebin.com/8SSHDW8a](url)
[https://pastebin.com/YejPM2Uv](url)

**Comment by bakkeby** [comment]
Ah, I know what it is.

In your config.h there is the configuration for the bar, and you have the normal status enabled.

```
{ 'A',      0,     BAR_ALIGN_RIGHT,  width_status,          draw_status,          click_status,       "status" },
```

The click action is just the normal status click which triggers a ClkStatusText event. As no signal has been recorded dwmblocks end up just triggering the very first script.

If you change `click_status` to `click_statuscmd` then it should work as you'd expect, but you'll find that you won't trigger the date/time one as that has signal 0 (which dwmblocks ignores).

```
{ 'A',      0,     BAR_ALIGN_RIGHT,  width_status,          draw_status,          click_statuscmd,       "status" },
```

I'll add a change to the default configuration to include this if the statuscmd patch is enabled.

**Comment by los95** [comment]
That fixed it! Thank you for you time and hard work!
