### ISSUE TITLE
xrdb patch f5 keybinding not working

### ISSUE THREAD

**Issue by StoicIndividual** [bakkeby/dwm-flexipatch#371]
I've been trying to refresh the colorscheme using:
`{ MODKEY|ShiftMask,             XK_F5,         xrdb,                   {.v = NULL } },` 
after 
`xrdb ~/.config/x11/xresources & xrdbpid=$!`
and found it not working or doing anything. Doing `kill -HUP $(pidof dwm)` does refresh the colorscheme and so does restarting the session.
these are the currently enabled patches:

#define BAR_DWMBLOCKS_PATCH 1 
#define BAR_LTSYMBOL_PATCH 1 
#define BAR_STATUS_PATCH 1 
#define BAR_STATUSCMD_PATCH 1 
#define BAR_STATUS2D_PATCH 1 
#define BAR_STATUS2D_XRDB_TERMCOLORS_PATCH 1 
#define BAR_TAGS_PATCH 1 
#define BAR_UNDERLINETAGS_PATCH 1 
#define BAR_WINICON_PATCH 1 
#define BAR_WINTITLE_PATCH 1 
#define BAR_ALPHA_PATCH 1 
#define BAR_CENTEREDWINDOWNAME_PATCH 1 
#define BAR_HIDEVACANTTAGS_PATCH 1 
#define BAR_PADDING_VANITYGAPS_PATCH 1 
#define BAR_STATUSPADDING_PATCH 1 
#define NOBORDER_PATCH 1 
#define RESTARTSIG_PATCH 1 
#define SEAMLESS_RESTART_PATCH 1 
#define VANITYGAPS_PATCH 1 
#define XRDB_PATCH 1 
#define ZOOMFLOATING_PATCH 1 
#define TILE_LAYOUT 1 
#define MONOCLE_LAYOUT 1

**Comment by bakkeby** [comment]
```sh
xrdb ~/.config/x11/xresources & xrdbpid=$!
```

What are you actually trying to do here?

I'd try

```sh
xrdb ~/.config/x11/xresources
```

then hit the keybinding for xrdb.

**Comment by StoicIndividual** [comment]
after running `xrdb ~/.config/x11/xresources` the keybinding still doesn't work.
for extra information i changed the modkey to be the windows key, so i'm doing windowskey+shift+F5

**Comment by bakkeby** [comment]
Perhaps try to bind it to something very different (e.g. like Super+u) and see if that works?

It can be of course that Super+Shift+F5 does not work in your case. That is often an issue with laptops where they have a function (`fn`) key that acts as a special modifier, but actually behind the scenes it is just hooking into other key combinations and sending through a `XF86MonBrightnessUp` as an example instead.

In my case I can send a client to any tag using Super+Shift+1 through 9, except Super+Shift+3. Things like that can be quite annoying.

**Comment by StoicIndividual** [comment]
Ok it's working i was just a little confused the `xrdb ~/.config/x11/xresources & xrdbpid=$!` is part of luke smith's xprofile which also includes
 `# Ensure that xrdb has finished running before moving on to start the WM/DE.
[ -n "$xrdbpid" ] && wait "$xrdbpid"
`
i just thought that it was the same command as `xrdb ~/.config/x11/xresources` for some reason, and i also thought that the xrdb command in dwm also ran some form of  `xrdb ~/.config/x11/xresources` when it simply just refreshes dwm's colors. thanks for the help!

**Comment by bakkeby** [comment]
I'm not sure if I have it all right on this one, but my understanding is that when you run that `xrdb` command the `RESOURCE_MANAGER` property on the root window is updated.

```sh
xprop -root | grep RESOURCE_MANAGER
```

and when the resources are re-loaded that resource property is read.
