### ISSUE TITLE
Design: config.h (1200+) split up into sensible set or files

### ISSUE THREAD

**Issue by tami5** [bakkeby/dwm-flexipatch#38]
Hay there, I suggest splitting config.h to categorical-based files or modules such as keybinds, appearance, navigation ..... and perhaps, misc.

This will make it so much easier to access and edit . And if possible let the value of whether to include exclude a plugin be in the same file at the top. For example appearance.h has two sections one for related patches and the other for the logic.

**Comment by bakkeby** [comment]
I can see how that might work for a personal build, but I think that it would be very messy to maintain for a build like this that others might pick up - let alone confusing to someone not familiar with it.

I'd imagine that one would end up with six such categories (bar configuration, client appearance (border, gaps, corner radius, etc.), keybindings, signals, client rules, one for layout or misc. Then you'd have one .def.h file for each of these that would be copied during build time.

If I were to move all the options to enable patches within these files then that may work for some stuff, but I guess the majority of patches would depend on having certain things sourced or set up before config.h (and the rest) is included. While it may be more intuitive from an end user's perspective to be able to enable the alpha patch through barconf.h or appearance.h, it doesn't sound that feasible in practice.

**Comment by tami5** [comment]
You are right, thanks alot for thinking it through. Hopfully another simple feasible way would come up, to make choosing patches to include and its configuration less overwhelimng experience for the user. Perhaps an auto generation shell script or var file for defing variables, usually repated in other patches.

**Comment by bakkeby** [comment]
I think under _normal_ circumstances, unless you are a patch junkie, you wouldn't be integrating 150+ patches in your dwm build :)

dwm-flexipatch is, or at least was with [1.0](https://github.com/bakkeby/dwm-flexipatch/tree/dwm-flexipatch-1.0), intended as a means to "try before you buy" patches before you decide to try to include them in your own build. An addition to this was also more or less accurate integration hints, trying to keep both the existing and patched code side-by-side as a reference. I have had to relax this to open up for other developments lately.

My general recommendation for people new to dwm has been to forget about custom tweaks like colours and keybindings, and instead focus on what functionality / patches they want, and worry about the configuration when the behaviour is right. Then again I guess it's not always that easy to work out.

There are currently 175 patches on [https://dwm.suckless.org/patches/](https://dwm.suckless.org/patches/) - I suspect it is going to be an overwhelming experience no matter how you cut it.

One option could be to explicitly _hide_ configuration options, wysiwyg, that would likely make things less overwhelming at a first glance.
