### ISSUE TITLE
Why there are same statement in the if-else block? Is this correct or not? I'm not sure.

### ISSUE THREAD

**Issue by ysl2** [bakkeby/dwm-flexipatch#382]
```c
    #if SCRATCHPADS_PATCH && !RENAMED_SCRATCHPADS_PATCH
    shifted.ui = selmon->tagset[selmon->seltags];
    #else
    shifted.ui = selmon->tagset[selmon->seltags];
    #endif // SCRATCHPADS_PATCH
```

https://github.com/bakkeby/dwm-flexipatch/blob/d807d3da3e1bfed2e79fee5938a10e934be9b4b2/patch/shift.c#L8-L12

**Comment by bakkeby** [comment]
Good question.

Looking at the changes in https://github.com/bakkeby/dwm-flexipatch/commit/20692bea017353bcaf069625bcf3bda6eed4ad51 it seems that the `shiftboth`, `shiftswaptags` and `shifttag` functions had this code / issue, while `shifttagclients`, `shiftview` and `shiftviewclients` had this:

```c
	#if SCRATCHPADS_PATCH && !RENAMED_SCRATCHPADS_PATCH
	shifted.ui = selmon->tagset[selmon->seltags] & ~SPTAGMASK;
	#else
	shifted.ui = selmon->tagset[selmon->seltags];
	#endif // SCRATCHPADS_PATCH
``` 

So I think the first case should have that `& ~SPTAGMASK` added to it. I suppose it is a good example of how much fuzz it creates when one decides to add special tags to hold scratchpad clients (and why the named scratchpads patch causes a lot less conflicts).

**Comment by ysl2** [comment]
Thanks for your kind explain! You are really a patient person, and you have done excellent work for dwm community!! Thank you :-)
