### ISSUE TITLE
Systray icon not show. I have read the KNOWN_ISSUE part, but I think this is a bug in flexipatch. I can prove it

### ISSUE THREAD

**Issue by ysl2** [bakkeby/dwm-flexipatch#384]
## Problem introduce

I flip the alpha and systray's patch flag to 1 to enable them both in flexipatch. After that, I found the systray icon not show.

But this is weird. Beacuse I also have my self patched dwm, it can work correctly. 

I have read the KNOWN_ISSUE, but I think this is not the application's problem.

## Minimal test case

This is how I patched, from `0001` to `0003` in sequence, based on the newest dwm offical git repo commit. After the three patches, my systray icons show normally, and alpha patch also work.

[0001-Add-alpha-patch.patch.txt](https://github.com/bakkeby/dwm-flexipatch/files/13260156/0001-Add-alpha-patch.patch.txt)
[0002-Add-systray-patch.patch.txt](https://github.com/bakkeby/dwm-flexipatch/files/13260157/0002-Add-systray-patch.patch.txt)
[0003-Fix-two-patches-conflict.patch.txt](https://github.com/bakkeby/dwm-flexipatch/files/13260158/0003-Fix-two-patches-conflict.patch.txt)

These two below is what I based. They are the newest patch come from dwm offical site, and my dwm is also based on the newest git commit.

[dwm-alpha-20230401-348f655.diff.txt](https://github.com/bakkeby/dwm-flexipatch/files/13260159/dwm-alpha-20230401-348f655.diff.txt)
[dwm-systray-6.4.diff.txt](https://github.com/bakkeby/dwm-flexipatch/files/13260160/dwm-systray-6.4.diff.txt)

The explain of `0003` can be found here: 

https://www.reddit.com/r/dwm/comments/aqlicx/question_does_anyone_here_have_a_working_combined/

![image](https://github.com/bakkeby/dwm-flexipatch/assets/39717545/db5030b9-f197-41dc-bea8-e6ee450abb49)

**Comment by bakkeby** [comment]
Which systray icon are you talking about?

There is absolutely no information here about how to reproduce the issue you are experiencing.

**Comment by ysl2** [comment]
clash for windows. 

You can download and extract this tarball and run `cfw`. In normal case, a cat icon will show in systray area.

This program is for network proxy and it is safe. But beacuse the original author deleted this a few days ago, I uploaded a backup for my   self use.

https://github.com/ysl2/clash-glados/releases/download/v0.0.1/Clash.for.Windows-0.20.4-x64-linux.tar.gz

**Comment by ysl2** [comment]
Oh by the way, I tested them in monospace 13 size. When in default 10 size, both of them show icon correctly. Sorry I forgot this and not mentioned.

![image](https://github.com/bakkeby/dwm-flexipatch/assets/39717545/beb0bd99-43c5-456e-8a93-78a78a35c10c)

**Comment by ysl2** [comment]
For additional information, when I use monospace 13 size in flexipatch:

Optional 1: Open `BAR_HEIGHT_PATCH` and set the `bar_height` to `20`, the icon will show. 
Optional 2: Or I open `BAR_STATUSPADDING_PATCH` and set the `vertpadbar` to `-2`, the icon also will show.

**Comment by bakkeby** [comment]
That kind of sounds like #136 and this was reproducible using only a bare dwm + systray patch ref. this [reddit post](https://www.reddit.com/r/suckless/comments/mwb2lv/dwmsystray62diff_patch_sometimes_no_icons_in_tray/) three years ago.

For some reason this only happens to the first systray window opened and opening up a second systray window tends to resolve the issue as well.

It is not straightforward to replicate the issue as the actual size of the font depends on the font used (and "monospace" here is just an alias for a group of fonts).

I was able to replicate the issue using a pixelsize of 21 and running `cfw`.

```c
static const char *fonts[]               = { "monospace:pixelsize=21" };
```

The source code for the application was not available, but the binaries show that it has support for appindicator and it suggests that it is an electron app.

It is not clear to me why only specific systray sizes causes this issue.

**Comment by ysl2** [comment]
Thanks for your kind explain!

For people who might see this issue, my current monitor is `DELL D2720DS`, 27 inch. I don't know if this problem is related to monitor size.
