### ISSUE TITLE
Patch request: Awesomebar's newest patch for controlling hide and show by keyboard

### ISSUE THREAD

**Issue by ysl2** [bakkeby/dwm-flexipatch#386]
The newest awesomebar patch provides `focusstackvis`, `focusstackhid`  and `show`, `hide`, `showall` function to control the clients to hide and show, these functions can be bound to specific keymap. I think this might be useful? Beacuse for the tiling layouts, people might not want to use mouse to do this....

https://dwm.suckless.org/patches/awesomebar/dwm-awesomebar-20230431-6.4.diff

**Comment by bakkeby** [comment]
That is kind of a different patch; you have multiple people providing their own version of the patch.

`focusstack` already supports traversing visible and visible + hidden windows if passing +/-2. Adding a function that only traverses hidden windows is a better solution, but this is also something that could just be added in personal config.

**Comment by ysl2** [comment]
OK, I understand :-)

I didn't notice the `== 1` and `== -1` in focusstack, this is indeed an useful trick !
