### ISSUE TITLE
Is there a method to hide specific floating window's border by checking it's xprop and set it in rules?

### ISSUE THREAD

**Issue by ysl2** [bakkeby/dwm-flexipatch#392]
I don't want the float border shows in some application like the file manager, beacuse it renders incorrectly.
Is there a method that I can write the rule to skip it? for example, a `isborder` option like `issticky`, `isfloat`, etc.

![image](https://github.com/bakkeby/dwm-flexipatch/assets/39717545/07b74907-aef5-4bd1-8223-885e71c089ac)

**Comment by bakkeby** [comment]
Yes there is the decoration hints patch that may work:
https://dwm.suckless.org/patches/decoration_hints/

In this particular case it may also be an issue with the gtk theme, refer to:
https://www.reddit.com/r/dwm/s/Pfhm6Nk68c

**Comment by ysl2** [comment]
I would say it's sooo cool! I just flip the `DECORATION_HINTS_PATCH` to 1 then re-make, and things gets normal! Thank you!!!
