### ISSUE TITLE
Sometimes the shiftviewclients { .i = -1 } will no response, except I quit dwm and re-enter it.

### ISSUE THREAD

**Issue by ysl2** [bakkeby/dwm-flexipatch#399]
```
	{ MODKEY,                       XK_p,          shiftviewclients,       { .i = -1 } },
```

Sometimes `shiftviewclients { .i = -1 }` cannot response, press `MOD+p` and nothing happend, but `{ .i = +1 }` still works.

It happens occasionally, I cannot reproduce any time. But it indeed happens sometimes.

Here are my enabled patches:

```
#define BAR_AWESOMEBAR_PATCH 1
#define BAR_LTSYMBOL_PATCH 1
#define BAR_STATUS_PATCH 1
#define BAR_SYSTRAY_PATCH 1
#define BAR_TAGS_PATCH 1
#define BAR_WINTITLE_PATCH 1
#define BAR_ALPHA_PATCH 1
#define BAR_HIDEVACANTTAGS_PATCH 1
#define ALWAYSCENTER_PATCH 1
#define AUTOSTART_PATCH 1
#define CFACTS_PATCH 1
#define CYCLELAYOUTS_PATCH 1
#define DECORATION_HINTS_PATCH 1
#define FAKEFULLSCREEN_PATCH 1
#define FULLSCREEN_PATCH 1
#define INPLACEROTATE_PATCH 1
#define MOVESTACK_PATCH 1
#define NOBORDER_PATCH 1
#define ONLYQUITONEMPTY_PATCH 1
#define PERTAG_PATCH 1
#define PERTAGBAR_PATCH 1
#define RENAMED_SCRATCHPADS_PATCH 1
#define RENAMED_SCRATCHPADS_AUTO_HIDE_PATCH 1
#define SAVEFLOATS_PATCH 1
#define SHIFTBOTH_PATCH 1
#define SHIFTSWAPTAGS_PATCH 1
#define SHIFTVIEW_PATCH 1
#define SHIFTVIEW_CLIENTS_PATCH 1
#define STICKY_PATCH 1
#define SWALLOW_PATCH 1
#define SWAPTAGS_PATCH 1
#define TAPRESIZE_PATCH 1
#define VANITYGAPS_PATCH 1
#define VANITYGAPS_MONOCLE_PATCH 1
#define VIEWONTAG_PATCH 1
#define FLEXTILE_DELUXE_LAYOUT 1
#define GAPPLESSGRID_LAYOUT 1
#define GRIDMODE_LAYOUT 1
#define HORIZGRID_LAYOUT 1
#define NROWGRID_LAYOUT 1
#define MONOCLE_LAYOUT 1
```

**Comment by bakkeby** [comment]
Is this as in dwm stops responding and you have to kill the session to get back in?

Haven't been able to replicate.

Only thing I noticed is that if you have changed your `MODKEY` to be Mod4Mask (Super) then the default keybinding will be MOD+Tab.

```c
	{ MODKEY|Mod4Mask,              XK_Tab,        shiftviewclients,       { .i = -1 } },
```

which conflicts with

```c
	{ MODKEY,                       XK_Tab,        view,                   {0} },
```

**Comment by ysl2** [comment]
> Is this as in dwm stops responding and you have to kill the session to get back in?

No, dwm just works normal, except the `MOD+p` (I bind the `shiftviewclients { .i = -1 }` to `MOD+p`), press `MOD+p` and nothing happened, just like I didn't bind this. But `Mod+n` (I bind the `shiftviewclients { .i = +1 }` to `MOD+n`) works as normal, when I press `MOD+n`, it will jump to the next no-empty tag.

This is not just happened in dwm-flexipatch. I also have my fork from offical dwm git repo. After I patched the shift tools patch from official website, `MOD+p` also not work sometimes.

This is not occurs every time. And I'm wondering if the patch have some logical mistakes from the original patch author?

**Comment by ysl2** [comment]
Temporally close this, #401 might fix this issue.
