### ISSUE TITLE
pango patch bug

### ISSUE THREAD

**Issue by plasmoduck** [bakkeby/dwm-flexipatch#40]
Sorry to bug you again, but I've found a potential bug with the pango patch. First off there is no 'pango.c/h' file in the 'patch' directory if that could be it? But when enabled in patches.def.h and compiling I get this error:

ld: error: undefined symbol: pango_font_metrics_get_height
>>> referenced by drw.c
>>>               drw.o:(drw_font_create)

**Comment by bakkeby** [comment]
Did you remember to uncomment the relevant lines in `config.mk`?
```
./config.mk:29:# Uncomment for the pango patch / BAR_PANGO_PATCH
./config.mk:30:#PANGOINC = `pkg-config --cflags xft pango pangoxft`
./config.mk:31:#PANGOLIB = `pkg-config --libs xft pango pangoxft`
```

Note that you'll also have to have these libraries installed.

**Comment by plasmoduck** [comment]
Yes I uncommented those lines and I have those libs installed. I use FreeBSD so I changed X11INC and X11LIB to = /usr/local/include & /usr/local/lib.

Eveything else works, except for this.

**Comment by plasmoduck** [comment]
Do you use pangolin in your build? Does it compile for you? I'm thinking it could be down to me using FreeBSD and something else in config.mk needs tweaking.

**Comment by bakkeby** [comment]
I can confirm that it does compile and work with pango markup, but I don't use this in my personal setup. I use status2d for colours and drawing stuff in the bar.

It is quite likely a FreeBSD thing as you suggest. Perhaps check what version of the library you have, and whether the location of the pango.h does exist under /usr/local/include or /usr/local/lib.

Sometimes you need to install the dev variants of the same libraries to get the header files, but I don't remember that being the case for getting pango to work.

**Comment by plasmoduck** [comment]
Yeah I thought so. It doesn't matter so much. Reason I wanted it was cause apparently it can show application icons in the window title bar next to the application name. But I can live without it. I'm more interested in this dwm bar border patch if you can add it to the build that would be awesome! https://codemadness.org/paste/dwm-border-bar.patch

**Comment by bakkeby** [comment]
> apparently it can show application icons in the window title bar next to the application name

Can't say that I have seen anything like that. Afaik the markup is only used for the status text.

I saw your other request for the bar border patch. I have a few other buns in the oven at the moment, but I'll have a look in not too long I recon.

**Comment by plasmoduck** [comment]
I seen a screenshot from one of the guys in #suckless on OFTC and he said thats how he showed the icons apparently. Just thought it looked cool at the time but f*$k it. Anyways here is a screen shot of one of my old posts showing how the border bar patch can cool. I eagerly await you including it :) https://www.reddit.com/r/unixporn/comments/gnvnb0/dwm_nordic/
