### ISSUE TITLE
How to automatically reset to default layout for a tag once it is empty?

### ISSUE THREAD

**Issue by ysl2** [bakkeby/dwm-flexipatch#401]
I have searched on internet, https://www.reddit.com/r/suckless/comments/s2ch3f/dwm_how_to_reset_to_tiled_layout_when_all_windows/

```diff
diff --git a/dwm.c b/dwm.c
index a96f33c..787cd2a 100644
--- a/dwm.c
+++ b/dwm.c
@@ -189,6 +189,7 @@ static void pop(Client *);
 static void propertynotify(XEvent *e);
 static void quit(const Arg *arg);
 static Monitor *recttomon(int x, int y, int w, int h);
+static void resetlayout(const Arg *arg);
 static void resize(Client *c, int x, int y, int w, int h, int interact);
 static void resizeclient(Client *c, int x, int y, int w, int h);
 static void resizemouse(const Arg *arg);
@@ -1269,6 +1270,16 @@ recttomon(int x, int y, int w, int h)
    return r;
 }
 
+void
+resetlayout(const Arg *arg)
+{
+   Arg default_layout = {.v = &layouts[0]};
+   Arg default_mfact = {.f = mfact + 1};
+
+   setlayout(&default_layout);
+   setmfact(&default_mfact);
+}
+
 void
 resize(Client *c, int x, int y, int w, int h, int interact)
 {
@@ -1788,6 +1799,8 @@ unmanage(Client *c, int destroyed)
    focus(NULL);
    updateclientlist();
    arrange(m);
+   if (!(nexttiled(m->clients)))
+       resetlayout(NULL);
 }
 
 void
```

But I think it seems not a good way. Beacuse It will check all clients in a monitor instead of a specific tag. And this might be dangerous, beacuse we have `focus(NULL); updateclientlist(); arrange(m);` in the above of `resetlayout()`, the current focus tag might be already changed. Then it calls `resetlayout()`, the `setlayout()` subfunction (in `resetlayout()`) calls `arrange()` if the `selmon->sel` is not empty. So it might cause potential duplicate `arrange()` call.

So I wonder if there has a safe way to achieve the goal? Thanks ! :-)

**Comment by bakkeby** [comment]
This is a pretty clean way of doing it.

If you are worried about calling arrange twice then you could push the arrange from `unmanage` into an else statement.

> Beacuse It will check all clients in a monitor instead of a specific tag.

Yes. More specifically it will go through each client but only consider clients that are assigned to any of the tags that are currently visible. More so it will bail at the first visible and tiled client found.

This has to do with that dwm only has a single workspace per monitor and the clients that are shown on that workspace is controlled by the use of tags.

**Comment by ysl2** [comment]
Does this resetlayout patch may affect the behaviour of `shift-tools`? Beacuse I use this resetlayout patch and your `shiftviewclients` patch both. I'm struggling with the problem mentioned in #399 and try to find out if there are any patch conflicts in them.

**Comment by bakkeby** [comment]
I don't see how these two patches would ever conflict.

**Comment by ysl2** [comment]
I think there might be some bugs in [my modified version of the resetlayout patch](https://github.com/ysl2/dwm-flexipatch/commit/f9cf91d41d49e46f148b40579185318c23749773), so I fallback to [a more minimal version](https://github.com/ysl2/dwm-flexipatch/commit/b54b9183b0736f0ba1beec3fd01c5f85602de44a), now my dwm seems normal. The `MOD+p` problem does't appear. Temporally close this issue. If any bugs relative to this issue, I will re-open this issue.
