### ISSUE TITLE
Three-part extra status

### ISSUE THREAD

**Issue by salastro** [bakkeby/dwm-flexipatch#418]
Hello, I have been playing a bit with extra status, but I have not found a way to split the status into three parts: left, center, right. I don't whether I am missing the configuration or it is not implemented. Thank you.

**Comment by bakkeby** [comment]
You are not missing anything. The way dwm is implemented it has a single status that is read from the root window name. 

The extrastatus patch splits that status into two based on a delimiter (typically `;`) and uses the second status for the second bar. In dwm-flexipatch it is the same just that you can more freely place that second status.

Sure it would be possible to continue splitting by the delimiter, but it is not what that patch does and it would result in some duplication of code and space questions like how much space do you reserve for each status?

In my dusk build I went with a different approach where I can have as many individual statuses as I want (e.g. one for clock, one for CPU usage, etc.) which simplifies click handling and solves the underlying problem that dwmblocks and 20 other status programs try to solve; how to combine multiple status fields into a single update. That is not something that I'd backport to dwm-flexipatch though as it would be complicated to make it work alongside the traditional status handling when it comes to click handling for example.

**Comment by salastro** [comment]
Oh okay, guess will check dusk then. Thank you.
