### ISSUE TITLE
dwm duplicating focus with SWITCHTAG_PATCH

### ISSUE THREAD

**Issue by Ampnbsp** [bakkeby/dwm-flexipatch#425]
### How to reproduce

1. E.g. dwm has this rule `RULE(.class = "ArmCord", .monitor = 1, .switchtag = 3, .tags = 1 << 7)`;
2. Launch this program from the other monitor.

After these steps the focus duplicates.

![pictureissue](https://github.com/bakkeby/dwm-flexipatch/assets/41110719/2a341a57-48de-4a30-a0de-a4f17ffb3fc0)

This issue was fixed with `unfocus(selmon->sel, 1, NULL);` before the [selmon = c->mon;](https://github.com/bakkeby/dwm-flexipatch/blob/79404e419f627d5ad3583cc836d4a64054c5014a/dwm.c#L971C1-L971C21) and it seems work fine.

**Comment by bakkeby** [comment]
I have looked at this again and the unfocus call makes sense where you added it. Have committed it now. Thanks for highlighting.
