### ISSUE TITLE
Swallow patch not working on FreeBSD

### ISSUE THREAD

**Issue by plasmoduck** [bakkeby/dwm-flexipatch#43]
Hi again, not sure which version of swallow patch you are using, but it doesn't 'swallow' on FreeBSD. Perhaps you can upgrade it to this version which has FreeBSD support also?

https://dwm.suckless.org/patches/swallow/dwm-swallow-20200522-7accbcf.diff

**Comment by bakkeby** [comment]
Most certainly. It's been on my TODO list for quite a while now, just never got around to it. Also managed to fix some visual glitches when clients are swallowed.

**Comment by bakkeby** [comment]
Just pushed the changes:
https://github.com/bakkeby/dwm-flexipatch/commit/104c9909b59717702627324524b731b794b44f21

**Comment by plasmoduck** [comment]
Thanks for that, however I'm getting this error; 

./patch/swallow.c:112:28: warning: implicit declaration of function 'kinfo_getproc' is invalid in C99 [-Wimplicit-function-declaration]
        struct kinfo_proc *proc = kinfo_getproc(p);
                                  ^
./patch/swallow.c:112:21: warning: incompatible integer to pointer conversion initializing 'struct kinfo_proc *' with an expression of type 'int'
      [-Wint-conversion]
        struct kinfo_proc *proc = kinfo_getproc(p);
                           ^      ~~~~~~~~~~~~~~~~
./patch/swallow.c:116:10: error: incomplete definition of type 'struct kinfo_proc'
        v = proc->ki_ppid;
            ~~~~^
./patch/swallow.c:112:9: note: forward declaration of 'struct kinfo_proc'
        struct kinfo_proc *proc = kinfo_getproc(p);

**Comment by plasmoduck** [comment]
Looks like it needs declaring the function kinfo_getproc or including the header that declares it

**Comment by bakkeby** [comment]
Do you know what header file that is included in?

**Comment by plasmoduck** [comment]
KINFO_GETPROC(3)       FreeBSD Library Functions Manual       KINFO_GETPROC(3)

NAME
     kinfo_getproc – function for getting process information from kernel

LIBRARY
     System Utilities Library (libutil, -lutil)

SYNOPSIS
     #include <sys/types.h>
     #include <sys/user.h>
     #include <libutil.h>

     struct kinfo_proc *
     kinfo_getproc(pid_t pid);

DESCRIPTION
     This function is used for obtaining process information from the kernel.

     The pid field contains the process identifier.  This should be a process
     that you have privilege to access.  This function is a wrapper around
     sysctl(3) with the KERN_PROC_PID mib.  While the kernel returns a packed
     structure, this function expands the data into a fixed record format.

RETURN VALUES
     On success the kinfo_getproc() function returns a pointer to a struct
     kinfo_proc structure as defined by <sys/user.h>.  The pointer was
     obtained by an internal call to malloc(3) and must be freed by the caller
     with a call to free(3).  On failure the kinfo_getproc() function returns
     NULL.

SEE ALSO
     free(3), malloc(3), sysctl(3)

**Comment by bakkeby** [comment]
Does it work if you add this at the top of swallow.c?
```c
#include <libutil.h>
```

**Comment by plasmoduck** [comment]
Almost, now I only get 1 error;

./patch/swallow.c:117:10: error: incomplete definition of type
      'struct kinfo_proc'
        v = proc->ki_ppid;

**Comment by bakkeby** [comment]
OK, so it sounds like you can do
```c
#include <sys/kinfo_proc.h>
```
alternatively
```c
#include <sys/user.h>
```
I should probably set up a virtual machine with FreeBSD so that I can test stuff like this.

**Comment by plasmoduck** [comment]
Yeah it's handy. I talk to a few of the suckless devs on IRC OFTC #suckless and thats what they do. Just helps to make your code less buggy

**Comment by plasmoduck** [comment]
Using #include <sys/user.h> gave me 20 errors
using #include <sys/kinfo_proc.h> have me ;
fatal error: 'sys/kinfo_proc.h' file not found
#include <sys/kinfo_proc.h>

**Comment by plasmoduck** [comment]
I should try.

**Comment by plasmoduck** [comment]
I think this is the better patch https://dwm.suckless.org/patches/swallow/dwm-swallow-20200807-b2de9b0.diff that one seems broken.

**Comment by bakkeby** [comment]
Does the latter one work for you? I was looking at that, but wasn't entirely sure considering that they make a difference when it comes to whether `__OpenBSD__` or `__FreeBSD__` is defined.

**Comment by plasmoduck** [comment]
I'll try the latter patch tomorrow when I wake up. It doesn't matter so much as I have this script I use which does pretty much the same thing, would just be nice to have it automated.

#!/bin/sh
 2 # swallow-like script for the terminal.
 3 # Dependencies: xdotool
 4
 5 xdotool windowunmap "$WINDOWID"
 6 $@
 7 xdotool windowmap "$WINDOWID"

I use it like 'swallow vlc /path/to/video.file'

Anyhow I shall report back to you tomorrow.
Cheers

**Comment by plasmoduck** [comment]
Sorry for taking so long to get back to you. I can confirm the later patch https://dwm.suckless.org/patches/swallow/dwm-swallow-20200807-b2de9b0.diff works for me.

**Comment by bakkeby** [comment]
OK, that's good. As the other one clearly did not work I integrated the later patch instead so should be up on the latest on dwm-flexipatch.

**Comment by plasmoduck** [comment]
Any idea how to make tag 9 alaways floating and the rest tiled as usual? Doesnt matter if its on all monitors.

**Comment by plasmoduck** [comment]
I used pertag, to have indivitual layouts pertag, but I'd like one tag to always be floating when I start dwm. Like it doesntt save layouts.

**Comment by bakkeby** [comment]
Sure, have a look at the monitor rules here:
https://github.com/plasmoduck/modwm/blob/master/config.def.h#L421

I guess in your case you'd want monitor 0 (or -1 for all monitors), tag 9, and layout of 2.
