### ISSUE TITLE
Clickable dwmblocks config or dwmblocks flexipatch with Example

### ISSUE THREAD

**Issue by Dan7h3x** [bakkeby/dwm-flexipatch#437]
Great work buddy, just add dwmblocks config or example with clickable blocks

**Comment by bakkeby** [comment]
I think in the first place you should refer to the [statuscmd](https://dwm.suckless.org/patches/statuscmd/) patch page.

As for example config you could have a look at Luke Smith's dwmblocks build:
https://github.com/LukeSmithxyz/dwmblocks/blob/master/config.h

and the various scripts that his config refers to:
https://github.com/LukeSmithxyz/voidrice/tree/master/.local/bin/statusbar
