### ISSUE TITLE
Systray & Alpha bug

### ISSUE THREAD

**Issue by plasmoduck** [bakkeby/dwm-flexipatch#44]
Just a small bug I've noticed, when using the systray patch together with alpha, icons have a ugly black background. Changing the following code

/* use parents background color */
swa.background_pixel = scheme[SchemeNorm][ColBg].pixel;
XChangeWindowAttributes(dpy, c->win, CWBackPixel, &swa);

To something like;

swa.background_pixel = "#282828"; 

Should change the color, however alpha ignores that and prints black #000000. Disabling alpha patch makes systray use SchemeNorm bar bg color again.

Perhaps there is some wizardry you can conjure up to make these 2 patches play nicely together.
![tray](https://user-images.githubusercontent.com/38978656/92955920-5b803280-f4a9-11ea-99ad-bfaaee307bae.png)

**Comment by bakkeby** [comment]
Do you use a compositor?

**Comment by plasmoduck** [comment]
I used to use picom, but I kind of got over the whole
transparency/shadows thing now. It was working fine with transparency
just that ugly black background in the systray.

**Comment by bakkeby** [comment]
If you don't use a compositor then the background will be black if you use the alpha patch as there is nothing that handles the transparency effect. If you disable alpha then the background should be the same as the bar (SchemeNorm).

**Comment by plasmoduck** [comment]
Yes I understand this, however at the time I was using a compositor
which is how i noticed the bug. Are you able to reproduce this? alpha
+ systray patch + picom/compton.

**Comment by bakkeby** [comment]
![image](https://user-images.githubusercontent.com/1438008/92960531-125ebd00-f46e-11ea-83e3-87427876c910.png)
No for me the systray is fully transparent, both with picom and xcompmgr.

**Comment by plasmoduck** [comment]
Ah yes, looks like you're right. I was missing this line from picom.conf
shadow-exclude = [
"class_g = 'dnwmsystray'",
]

**Comment by bakkeby** [comment]
I don't think shadows themselves would give you that complete black background, but I have seen picom sometimes crashing when trying to draw shadows on a new systray icon. Not entirely sure why. Possibly it had crashed and was no longer running when you took that screenshot. Adding it to the shadow-exclude obviously avoids such issues.
