### ISSUE TITLE
xrdb not compatible with python-pywal color schemes

### ISSUE THREAD

**Issue by kronikpillow** [bakkeby/dwm-flexipatch#5]
seems that the xrdb patch here is not compatible with python-pywal color schemes, which I find weird, as when I applied the xrdb patch and generate a pywal color scheme on standard dwm + xrdb it works ... am I overlooking something here? if im not ... can you make the XRDB patch compatible with pywal color schemes? :)

**Comment by bakkeby** [comment]
I don't know, how did you get it to work with standard dwm + xrdb in the first place?

The xrdb patch reads resources named:
```
dwm.normbordercolor
dwm.normbgcolor
dwm.normfgcolor
dwm.selbordercolor
dwm.selbgcolor
dwm.selfgcolor
```

while python-pywal creates scheme names such as:
```
*foreground:        #79a5cb
*background:        #3c1b23
*.foreground:       #79a5cb
*.background:       #3c1b23
...
*.color0: #3c1b23
*color0:  #3c1b23
*.color1: #E65B26
*color1:  #E65B26
*.color2: #A24240
*color2:  #A24240
*.color3: #469C5B
*color3:  #469C5B
*.color4: #FB9420
*color4:  #FB9420
*.color5: #F3B35A
```

I guess if you wanted to you could change the names in function loadxrdb, see the XRDB_LOAD_COLOR calls:
https://dwm.suckless.org/patches/xrdb/dwm-xrdb-6.2.diff

You'd have to play around to see which of the colour codes would be most fitting. I had a quick look, but I didn't spot any way to make python-pyval create resources with specific names.

**Comment by bakkeby** [comment]
There's also https://github.com/dylanaraps/pywal/wiki/Customization#dwm, but that assumes that you'll restart dwm when colours change.

**Comment by kronikpillow** [comment]
pywal creates a colors-wal-dwm.h with content like

static const char norm_fg[] = "#e8dfcc";
static const char norm_bg[] = "#1c0e0d";
static const char norm_border[] = "#a29c8e";

static const char sel_fg[] = "#e8dfcc";
static const char sel_bg[] = "#AC8C57";
static const char sel_border[] = "#e8dfcc";

static const char urg_fg[] = "#e8dfcc";
static const char urg_bg[] = "#DD902B";
static const char urg_border[] = "#DD902B";

static const char *colors[][3]      = {
    /*               fg           bg         border                         */
    [SchemeNorm] = { norm_fg,     norm_bg,   norm_border }, // unfocused wins
    [SchemeSel]  = { sel_fg,      sel_bg,    sel_border },  // the focused win
    [SchemeUrg] =  { urg_fg,      urg_bg,    urg_border },
};


let me see my dwm.c and Luke's dwm.c to figgure out how its' reading it :D

**Comment by kronikpillow** [comment]
found it :) [https://github.com/LukeSmithxyz/dwm/commit/e2aeb53506500284069e796e2c5054b0b5665dab](https://github.com/LukeSmithxyz/dwm/commit/e2aeb53506500284069e796e2c5054b0b5665dab)

I guess I can do this manually ^^

**Comment by bakkeby** [comment]
If you wanted to you could also hook this up to [fsignal](https://dwm.suckless.org/patches/fsignal/) or [dwmc](https://dwm.suckless.org/patches/dwmc/) to have dwm reload the colours seamlessly after pywal runs.

**Comment by kronikpillow** [comment]
can you show me how? I use the dwmc patch

**Comment by bakkeby** [comment]
I haven't tested this, but I guess you'd add a signal reference in your signals array, e.g.
```
	{ "xrdb",           xrdb },
```
https://github.com/bakkeby/dwm-flexipatch/blob/master/config.def.h#L347-L371

Then you'd either run the command of:
```
xsetroot -name "fsignal:xrdb"
```
in your shell, or add `xrdb` to the dwmc shell script:
https://github.com/bakkeby/dwm-flexipatch/blob/master/patch/dwmc#L10

**Comment by kronikpillow** [comment]
will try it out and let you know if it works :)
