### ISSUE TITLE
Documentation: Add SPTAGMASK hint

### ISSUE THREAD

**Issue by B4rc1** [bakkeby/dwm-flexipatch#53]
When the scratchpad patch is added, the tagmask is altered, so to get a window onto all tags you have to do `~SPTAGSMASK` instead of `~0`, because otherwise, your window gets centred/the previous scratchpad position if the scratchpad remember patch is applied, this should be in a small comment either in the `config.h` or in the `patches.h`

**Comment by bakkeby** [comment]
This is a good point. It also plays a role in multiple parts of the build and I have added alternate code where relevant. Will have a look about documentation.
