### ISSUE TITLE
graphical glitch on apps

### ISSUE THREAD

**Issue by AtifChy** [bakkeby/dwm-flexipatch#57]
i am getting graphical glitch on many qt apps. Even without any patch enabled. I am using picom as my compositor.

**Comment by bakkeby** [comment]
What is the nature of these glitches? (do you have a screenshot)
Also what OS/distribution are you on?
Do these glitches go away if you use a plain 6.2 dwm?

**Comment by AtifChy** [comment]
yes this glitches go away when i use plain 6.2 dwm

**Comment by bakkeby** [comment]
I guess try and see if the glitches you are experiencing go away with the latest commit https://github.com/bakkeby/dwm-flexipatch/commit/016cdf385781d101221318d4ff8e029a357ff236 .

**Comment by AtifChy** [comment]
the glitch is gone but picom doesn't autostart anymore. I need to start it manually. Autostart patch is enabled.

**Comment by bakkeby** [comment]
`picom` is not the most stable of compositors, it is more likely that it crashes rather than that it does not start.

I'd recommend capturing the output of that picom command and saving that to a log file so that you can see what errors it prints.

If you use the systray for example then `picom` is prone to crashing if is configured to draw shadows on the systray area. If that is the case for you then I'd recommend adding
```
"class_g = 'dwmsystray'",
```
to the `shadow-exclude` setting in your picom.conf file.

**Comment by AtifChy** [comment]
ok nice. it works. i am trying to patch it myself. ![patchconflict](https://user-images.githubusercontent.com/42291930/95684164-77dece80-0c11-11eb-9d5a-b5668d9afbde.png)
how did you fix this?

**Comment by bakkeby** [comment]
The systray patch moves that XMoveResizeWindow line into a new function `resizebarwin` that is being called. The barpadding patch alters that XMoveResizeWindow line by adjusting the position and size of the bar based on two variables `sp` and `vp`.

The systray introduces this code:
```c
void
resizebarwin(Monitor *m) {
	unsigned int w = m->ww;
	if (showsystray && m == systraytomon(m))
		w -= getsystraywidth();
	XMoveResizeWindow(dpy, m->barwin, m->wx, m->by, w, bh);
}
```

Applying the barpadding patch on top of that you should end up with something like:
```c
void
resizebarwin(Monitor *m) {
	unsigned int w = m->ww - 2 * sp;
	if (showsystray && m == systraytomon(m))
		w -= getsystraywidth();
	XMoveResizeWindow(dpy, m->barwin, m->wx + sp, m->by + vp, w, bh);
}
```

**Comment by AtifChy** [comment]
thanks
