### ISSUE TITLE
BAR_ACTIVETAGINDICATORBAR_PATCH

### ISSUE THREAD

**Issue by plasmoduck** [bakkeby/dwm-flexipatch#59]
Hi bakkeby, what's the go with BAR_ACTIVETAGINDICATORBAR_PATCH are you able to get it working? I was using that patch before in another build and I configured it to display on the botton of the tag name like your BAR_ACTIVETAGINDICATORBAR_ALT1_PATCH which was quite nice instead of the standard small square.

**Comment by bakkeby** [comment]
These have been integrated in a different way, so the BAR_ACTIVETAGINDICATORBAR_PATCH definition in patches.def.h is merely for informational purposes.

Have a look at the two configuration items of 
```c
/* Indicators: see patch/bar_indicators.h for options */
static int tagindicatortype              = INDICATOR_TOP_LEFT_SQUARE;
static int floatindicatortype            = INDICATOR_TOP_LEFT_SQUARE;
```

You probably want INDICATOR_BOTTOM_BAR or INDICATOR_BOTTOM_BAR_SLIM for the `tagindicatortype` setting.

**Comment by plasmoduck** [comment]
What file is that in?
