### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by plasmoduck** [bakkeby/dwm-flexipatch#60]
Hey I thought about a new idea where when you press MODKEY+C the close a window dwm pops up dmenu asking "Do you want to close? yes/no". There should be an option which programs WM_CLASS to use this for so it can be used for some specific programs not all. How would I go about this? The dmenu script I can do, but the dwm modification of the close MODKEY+C command I can't do.

**Comment by bakkeby** [comment]
I'd recommend having a look at how the [layoutmenu](https://dwm.suckless.org/patches/layoutmenu/) patch works.

What it does is:
- you trigger a function using a keybinding
- that function executes a shell script
- that shell script runs xmenu
- the output of xmenu is also the output of the script
- the function reads the output of the shell script
- the function calls `setlayout` with an argument depending on the output of the script

You should be able to re-purpose this to have a script call dmenu instead asking whether the user is sure about closing the window. A rule option could also be used to check whether the user should be asked for the given client or not.

Alternatively you could achieve most of this using the IPC patch without any additional changes to dwm.

**Comment by plasmoduck** [comment]
Perfect thats just what I wanted. Thanks as always.

-Plasmo
