### ISSUE TITLE
increase the height of the bar without increasing systray icon size

### ISSUE THREAD

**Issue by AtifChy** [bakkeby/dwm-flexipatch#62]
i would like increase my bar height but it also increase my systray icon size. How do I stop my systray icons from getting bigger? 
![Screenshot_20201024_124231](https://user-images.githubusercontent.com/42291930/97070048-ec911000-15f6-11eb-9e4c-ff54a22e958e.png)

**Comment by bakkeby** [comment]
Hi @AtifChy,

I guess it is a patch incompatibility issue.

I have committed a change that aims to address this, let me know if there are any issues.

\
Thanks,

-Stein

**Comment by AtifChy** [comment]
it's fixed thanks.
