### ISSUE TITLE
bar_border_patch

### ISSUE THREAD

**Issue by plasmoduck** [bakkeby/dwm-flexipatch#65]
Howdy,

In regards to the bar_border_patch is it possible to just draw a border on the bottom of the bar and not the whole way around? More like an underline?

**Comment by bakkeby** [comment]
I wouldn't say that it's impossible, but it's certainly not straightforward to do. You'd need to hack it in quite a few places to change how the border pixel works, and you'd also have to take into account that the underline should be at the top if the bar is shown at the bottom.

It could possibly be less work to draw such a line separately, but I think that it would not be a quick fix.

**Comment by plasmoduck** [comment]
Fair enough. I thought it might be straight forward but nevermind.
