### ISSUE TITLE
Bengali character not loading properly on dwm status bar 

### ISSUE THREAD

**Issue by AtifChy** [bakkeby/dwm-flexipatch#67]
![Screenshot_20201102_130023](https://user-images.githubusercontent.com/42291930/97839017-88afcb00-1d0b-11eb-8fdb-1519cc6c2a20.png)
I see a box in the tile bar. I have pango and awesomebar patch enabled for the title bar.

**Comment by bakkeby** [comment]
The numbers listed in that square is for the character `0xFFFD` - do you have a font that can display this character? Is this font listed in your config.h?

**Comment by AtifChy** [comment]
![Screenshot_20201102_154842](https://user-images.githubusercontent.com/42291930/97853874-e865a080-1d22-11eb-9dde-2a8c84a64b47.png)
it's works fine when i have enough space in the title bar.

**Comment by bakkeby** [comment]
I see, so it is a multi-byte UTF-8 character that gets split.

I think it is worth finding out whether this affects the bare dwm or only when the pango patch is applied.

I am not sure how you would fix this, but you may be in a good position to tinker with it to find out. I suspect that you will want to have a look at the `drw_text` function within drw.c, about mid-way through you have these lines:
```c
            drw_font_getexts(usedfont, utf8str, utf8strlen, &ew, NULL);
            /* shorten text if necessary */
            for (len = MIN(utf8strlen, sizeof(buf) - 1); len && ew > w; len--)
                drw_font_getexts(usedfont, utf8str, len, &ew, NULL);

            if (len) {
                memcpy(buf, utf8str, len);
                buf[len] = '\0';
                if (len < utf8strlen)
                    for (i = len; i && i > len - 3; buf[--i] = '.')
                        ; /* NOP */
```
It is worth noting that the ... is missing. It could possibly be that overwriting the last three bytes in the string with dots is what is causing a broken UTF-8 character.

**Comment by AtifChy** [comment]
how can i remove window name from the title bar and only show app name on the title bar?

**Comment by bakkeby** [comment]
How would you work out what the application name is?

**Comment by AtifChy** [comment]
i think this is a bug with the pango patch. i don't i can fix it. so i wanted to know if there is any way to remove window name from the title bar and only show the name of the application i am currently using.

**Comment by bakkeby** [comment]
You can print whatever you want there, but how would you work out what the name of the application you are currently running is?

**Comment by AtifChy** [comment]
i keep my borders small. so the title bar is helpful to see which window is active.

**Comment by AtifChy** [comment]
this was an issue with noto-fonts
