### ISSUE TITLE
floating indicator broken with awesome bar  

### ISSUE THREAD

**Issue by AtifChy** [bakkeby/dwm-flexipatch#69]
[simplescreenrecorder-2020-11-05_15.16.24.tar.gz](https://github.com/bakkeby/dwm-flexipatch/files/5493309/simplescreenrecorder-2020-11-05_15.16.24.tar.gz)
watch this video

**Comment by bakkeby** [comment]
Thanks for reporting, the above should address that issue.

**Comment by AtifChy** [comment]
fixed
