### ISSUE TITLE
Doesn't compile without any modifications

### ISSUE THREAD

**Issue by kkga** [bakkeby/dwm-flexipatch#70]
Trying to compile without any changes to config.h or patches.h, but here's the output I get:

```
> make
dwm build options:
CFLAGS   = -std=c99 -pedantic -Wall -Wno-deprecated-declarations -Os -I/usr/X11R6/include -I/usr/include/freetype2   -D_DEFAULT_SOURCE -D_BSD_SOURCE -D_POSIX_C_SOURCE=200809L -DVERSION="6.2" -DXINERAMA
LDFLAGS  = -L/usr/X11R6/lib -lX11 -lXinerama -lfontconfig -lXft        
CC       = cc
cc -c -std=c99 -pedantic -Wall -Wno-deprecated-declarations -Os -I/usr/X11R6/include -I/usr/include/freetype2   -D_DEFAULT_SOURCE -D_BSD_SOURCE -D_POSIX_C_SOURCE=200809L -DVERSION=\"6.2\" -DXINERAMA dwm.c
dwm.c: In function 'cleanupmon':
dwm.c:1136:7: error: 'systray' undeclared (first use in this function)
 1136 |   if (systray && bar == systray->bar)
      |       ^~~~~~~
dwm.c:1136:7: note: each undeclared identifier is reported only once for each function it appears in
dwm.c: In function 'drawbarwin':
dwm.c:1671:22: error: 'draw_systray' undeclared (first use in this function)
 1671 |     (br->drawfunc != draw_systray || (lastmon->index >= br->monitor && bar->mon->index == 0))) // hack: draw systray on first monitor if the designated one is not available
      |                      ^~~~~~~~~~~~
make: *** [Makefile:24: dwm.o] Error 1
```

**Comment by bakkeby** [comment]
Ah, thanks, related to a recent commit of mine. I'll fix it.

**Comment by kkga** [comment]
I'm also getting a segfault crash on first opened window if I try to compile it _with_ any patches. Still trying to understand whether it's an issue on my end or something else :/

**Comment by bakkeby** [comment]
> I'm also getting a segfault crash on first opened window if I try to compile it with any patches. 

That's interesting, are there any specific patches you enable to reproduce that?

**Comment by kkga** [comment]
Figured out what my problem was: I had a clean `patches.h` file where i only copypasted the flags for needed patches from `patches.def.h`. This compiled fine, but crashed on first opened window.

If I `cp patches.def.h patches.h` instead and then change the flags, it works fine. Sorry for the trouble :sweat_smile:

**Comment by bakkeby** [comment]
That's curious, it should work fine either way.

Let me know if you manage to replicate it again, it sounds like it may just be a certain combination of patches that does this.

**Comment by kkga** [comment]
yeah, i'd expect it to work either way too, however if my `patches.h` has the following content, I get the crashes:

```
#define BAR_SYSTRAY_PATCH 1
#define NOBORDER_PATCH 1
#define PERTAG_PATCH 1
#define SENDMON_KEEPFOCUS_PATCH 1
#define STEAM_PATCH 1
#define TOGGLEFULLSCREEN_PATCH 1
```

**Comment by bakkeby** [comment]
Hi @kkga,

I wasn't able to replicate dwm crashing (i.e. being kicked out to the login manager) with the above, but that doesn't mean that there isn't an issue there.

It is a bit of an odd setup as the only thing that you have in the bar is the systray, so until you open an application that has a systray then the bar remains invisible. When you do open such an application then the bar shows, and the only thing on it will be the systray icon.

For reference, these are the settings that are enabled by default to reflect what you get with a bare dwm.
```c
$ grep -E "^#define .* 1$" patches.def.h
#define BAR_LTSYMBOL_PATCH 1
#define BAR_STATUS_PATCH 1
#define BAR_TAGS_PATCH 1
#define BAR_WINTITLE_PATCH 1
#define BAR_TITLE_LEFT_PAD_PATCH 1
#define TILE_LAYOUT 1
#define MONOCLE_LAYOUT 1
```

There is also the [dwm-flexipatch-1.0](https://github.com/bakkeby/dwm-flexipatch/tree/dwm-flexipatch-1.0) branch from before I integrated barmodules which has a more traditional bar.

Hope this helps.

\
Thanks,

-Stein

**Comment by kkga** [comment]
> It is a bit of an odd setup as the only thing that you have in the bar is the systray, so until you open an application that has a systray then the bar remains invisible. When you do open such an application then the bar shows, and the only thing on it will be the systray icon.

Oh I didn't realize that I have to manually enable patches for the bar to have the default parts (tags, wintitle and status) :sweat_smile:

The patches I listed are the ones I had in my original dwm setup, so I simply tried to replicate it here.

I will try once again, thanks for pointing this out :+1:
