### ISSUE TITLE
Flextile Monocle symbol not counting

### ISSUE THREAD

**Issue by Schueni1** [bakkeby/dwm-flexipatch#73]
With flextile the monocle symbol is always [M] even when there are more than 0 active clients.

Expected behavior: It should start counting the clients if there are more than 0 active clients.

**Comment by bakkeby** [comment]
There is also this patch https://dwm.suckless.org/patches/monoclesymbol/ so expectations can vary.

This is actually configurable, you have this setup right:

```c
static const Layout layouts[] = {
    /* symbol     arrange function, { nmaster, nstack, layout, master axis, stack axis, secondary stack axis, symbol func } */
...
    { "[M]",      flextile,         { -1, -1, NO_SPLIT, MONOCLE, 0, 0, NULL } }, // monocle
                                                                       ^^^^
```

That `NULL` value means that we are not dynamically updating the icon for this arrangement. You can set this to `monoclesymbols` if you want the number of clients displayed, same with `decksymbols`. You can also create your own functions if you want something more custom / fancy.

**Comment by Schueni1** [comment]
Nice thank you!!!!
