### ISSUE TITLE
hey man :) long time no see ... got a tons of questions ...

### ISSUE THREAD

**Issue by kronikpillow** [bakkeby/dwm-flexipatch#75]
hey man ... long time no see, I was stuck on Winblows for a couple of months due to switching graphics cards and being unable to figure out how to get it working :D and i'm finally back .... damn dude dwm-flexipatch has changed a lot and it's become confusing to me ... I have a version that has EWMH_WINDOWS_FLOAT_PATCH 1 on my github, but it seems it doesn't exist anymore ... why was this patch removed? or was it removed by mistake?

i got tons of more questions but I'll start from here to not make it all to confusing :) so far I have been unable to get the master branch working for me

**Comment by kronikpillow** [comment]
question #2 ... wtf does this mean? :D

```
❯ make
dwm build options:
CFLAGS   = -std=c99 -pedantic -Wall -Wno-deprecated-declarations -Os -I/usr/X11R6/include -I/usr/include/freetype2   -D_DEFAULT_SOURC
LDFLAGS  = -L/usr/X11R6/lib -lX11 -lXinerama -lfontconfig -lXft  -lXrender   -lX11-xcb -lxcb -lxcb-res
CC       = cc
cc -c -std=c99 -pedantic -Wall -Wno-deprecated-declarations -Os -I/usr/X11R6/include -I/usr/include/freetype2   -D_DEFAULT_SOURCE -D_
cc -c -std=c99 -pedantic -Wall -Wno-deprecated-declarations -Os -I/usr/X11R6/include -I/usr/include/freetype2   -D_DEFAULT_SOURCE -D_
In file included from patch/include.c:12,
                 from dwm.c:418:
patch/bar_wintitle.c:30:1: warning: ‘click_wintitle’ defined but not used [-Wunused-function]
   30 | click_wintitle(Bar *bar, Arg *arg, BarArg *a)
      | ^~~~~~~~~~~~~~
patch/bar_wintitle.c:8:1: warning: ‘draw_wintitle’ defined but not used [-Wunused-function]
    8 | draw_wintitle(Bar *bar, BarArg *a)
      | ^~~~~~~~~~~~~
patch/bar_wintitle.c:2:1: warning: ‘width_wintitle’ defined but not used [-Wunused-function]
    2 | width_wintitle(Bar *bar, BarArg *a)
      | ^~~~~~~~~~~~~~
In file included from patch/include.c:9,
                 from dwm.c:418:
patch/bar_status.c:16:1: warning: ‘click_status’ defined but not used [-Wunused-function]
   16 | click_status(Bar *bar, Arg *arg, BarArg *a)
      | ^~~~~~~~~~~~
cc -c -std=c99 -pedantic -Wall -Wno-deprecated-declarations -Os -I/usr/X11R6/include -I/usr/include/freetype2   -D_DEFAULT_SOURCE -D_
cc -o dwm drw.o dwm.o util.o -L/usr/X11R6/lib -lX11 -lXinerama -lfontconfig -lXft  -lXrender   -lX11-xcb -lxcb -lxcb-res
```

**Comment by bakkeby** [comment]
Right, yes I guess quite a few things have happened since last time.

1\) EWMH_WINDOWS_FLOAT_PATCH, this was a patch to make utility, toollbar and splash windows floating by default (in addition to dialog boxes which dwm by default makes floating).

This was replaced by client rules by allowing users to also filter on the window type (_NET_WM_WINDOW_TYPE), e.g. something like this:
```c
    // class      instance  title  wintype           tags mask  isfloating  monitor
    { NULL,       NULL,     NULL,  WTYPE "DIALOG",   0,         1,          -1 },
    { NULL,       NULL,     NULL,  WTYPE "UTILITY",  0,         1,          -1 },
    { NULL,       NULL,     NULL,  WTYPE "TOOLBAR",  0,         1,          -1 },
    { NULL,       NULL,     NULL,  WTYPE "SPLASH",   0,         1,          -1 },
    { "Gimp",     NULL,     NULL,  NULL,             1 << 4,    0,          -1 },
    { "Firefox",  NULL,     NULL,  NULL,             1 << 7,    0,          -1 },
```

2\) [barmodules](https://github.com/bakkeby/patches/wiki/barmodules) happened while you were away. That page should tell you what you need to know, but in short it lets you move things around on the bar (having tags on the right side for example).

The warnings you see when you compile means that the `barrules` setting in your config.h does not include the status or the window title (but BAR_WINTITLE_PATCH and BAR_STATUS_PATCH are enabled).

If barmodules is hard to swallow then I'd recommend having a look at https://github.com/bakkeby/dwm-flexipatch/tree/dwm-flexipatch-1.0 instead, that's branched off before barmodules was integrated.

3\) I use a different mechanism for setting up client rules, I explained this in some detail in https://github.com/bakkeby/dwm-flexipatch/issues/72#issuecomment-727604498

As for getting started with the master branch I'd recommend that you start with the default config and add in the keybindings, etc. from your old config one by one (same with patches.h).

**Comment by kronikpillow** [comment]
problem with your suggestion is that I never got familiar and comfy with the way the config is done, so I always used flexipatchfinalizer to do my builds :-/ I guess I'll have to do a lot of studying ... yes I saw v1.0, but I also noticed that many new patches aren't included there

**Comment by kronikpillow** [comment]
ok so I still don't get the bartags and how i'm supposed to properly set them up but i'll get to that :) 

question, did you notice the new awesomebar updated patch on the suckless website? they included the feature that I requested from you to make here once in a issue i opened, now it's able to cycle trough hidden windows, and to toggle them to unhide (if i understood it correctly) ... if thats the case could you merge it in to flexipatch?

**Comment by bakkeby** [comment]
You can already do this actually.

The default keybindings for `focusstack` is as follows:
```c
    { MODKEY,                       XK_j,          focusstack,             {.i = +1 } },
    { MODKEY,                       XK_k,          focusstack,             {.i = -1 } },
```
If you pass +/- 2 rather than 1 then that will include hidden clients.
```c
    { MODKEY,                       XK_?,          focusstack,             {.i = +2 } },
    { MODKEY,                       XK_?,          focusstack,             {.i = -2 } },
```
You'll have to decide on appropriate keybindings of course. It is fairly crammed in dwm-flexipatch hence I do not have these included by default.

**Comment by kronikpillow** [comment]
hm... that's strange, why'd they make a new function for it then? I'm wondering if the effect is the same as with the latest awesomebar patch ...

ok, so ... first thing I notice is that the ENABLE_COLOR_EMOJI patch is not working .... after enabling it and compiling, my status bar is not in color ... and this problem seems to persist on both v1 and master

**Comment by bakkeby** [comment]
The +2 is something I added following an unrelated discussion some time before they added similar logic to the awesomebar patch. Being able to hide clients is more of a separate feature that shouldn't be bundled with the awesomebar patch imho.

Was your expectation that you enable the colour emoji patch and your status is presented in colour? You'll need a font that has coloured emojis, a status that actually refer to those emojis, and an updated Xft library that supports coloured emojis for this to work.

**Comment by kronikpillow** [comment]
Yes i already have libxft-bgra installed, and a dwmblocks with colored emoji, as i use LukeSmiths LARBS as a base, well i forked it and tweaked it a little, but when i use his dwm build emoji are in color, when i use flexipatch they are not even with the patch enabled, until i actually manually remove the code that blocks color fonts

**Comment by kronikpillow** [comment]
yup ... color emoji patch doesn't work on neither master or v1 branch ...
here is proof: :)
[Lukesmithxyz/dwm & dwmblocks](https://0x0.st/ihee.png)
[dwm-flexipatch with color emoji patch enabled)](https://0x0.st/ihe2.png)

**Comment by bakkeby** [comment]
I suspect that your problem is that you are using your old patches.h file.

**Comment by kronikpillow** [comment]
nope mate, clean clone of your repo, new patches.h copied / renamed patches.def.h

**Comment by kronikpillow** [comment]
it's not a "error in steps" from my side mate, it's a clean system, libxft-bgra installed, a complete new and clean copy of the dwm-flexipatch repository, and the problem exists in both versions v1 and v.barmodules

**Comment by kronikpillow** [comment]
the if statement isn't properly done ... it says

`	#if !BAR_COLOR_EMOJI_PATCH
	/* Do not allow using color fonts. This is a workaround for a BadLength
	 * error from Xft with color glyphs. Modelled on the Xterm workaround. See
	 * https://bugzilla.redhat.com/show_bug.cgi?id=1498269
	 * https://lists.suckless.org/dev/1701/30932.html
	 * https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=916349
	 * and lots more all over the internet.
	 */
	FcBool iscol;
	if (FcPatternGetBool(xfont->pattern, FC_COLOR, 0, &iscol) == FcResultMatch && iscol) {
		XftFontClose(drw->dpy, xfont);
		return NULL;
	}
	#endif // BAR_COLOR_EMOJI_PATCH

which basically means "if color emoji patch, use this code" .. but the thing is, that that piece of code needs to be removed not used

so it should be if "color emoji patch" use without the above code, elseif use the above code

**Comment by bakkeby** [comment]
You are !right.

**Comment by kronikpillow** [comment]
make sure you fix both versions :) digging further in to barmodules .. . still lost thou, I'm gonna do a flexipatch finalizer build of the master repo later today, and ill push it to github, would appreciate if you could checkout the config and help me figure out what im missing when you have time

**Comment by bakkeby** [comment]
There is nothing to fix, you are just lost.

**Comment by kronikpillow** [comment]
sorry mate what do you mean there is nothing to fix? the patch doesn't work, i dunno why you don't believe me, I'v shown you screenshots ... here is another one
[screenshot](https://0x0.st/ihOD.png)

this last screenshot was made after manual applying the patch, in other words i made a clean dwm-flexipatch build with no patches enabled and I have removed this piece of code manually
```
	FcBool iscol;
	if (FcPatternGetBool(xfont->pattern, FC_COLOR, 0, &iscol) == FcResultMatch && iscol) {
		XftFontClose(drw->dpy, xfont);
		return NULL;
	}
```
and for some reason it still doesn't work ....

here is my master branch where EMOJI_COLOR_PATCH is set to 1 [master branch (patch selection)](https://github.com/kronikpillow/dwm-flexipatch/tree/master)
here is my flexipatch finalized build branch [build branch (finalized build)](https://github.com/kronikpillow/dwm-flexipatch/tree/build)
result = [screenshot](https://0x0.st/ihOD.png)

after further investigation i find that the code that blocks colored emoji is actually removed from drw.c but it still blocks colored emoji for some reason, on my [old flexipatch build](https://github.com/kronikpillow/dwm-flexipatch-old) colored emoji work althou on this build i applied it manually as this build was made before the patch was included as a flexipatch option, but now on the latest master branch even when I manually remove that code, it still doesn't work

**Comment by kronikpillow** [comment]
ok, so far I have figgured out that the `warning: ‘click_status’` happens when i enable statuscmd patch as the statuscmd patch removes this line and replaces it with its own bar module setting, reading your comment above again you say that it means that BAR_STATUS_PATCH is enabled, click_wintitle, draw_wintitle,width_wintitle happens when I enable awesomebar patch

so that basically means that I can remove BAR_WINTITLE_PATCH and BAR_STATUS patches from the patches.h right?

**Comment by bakkeby** [comment]
How the bar works in general is outlined in https://github.com/bakkeby/patches/wiki/barmodules.

The setup is clearer when you set this up from scratch (or finalise it) as the pre-processor directives can indeed make it confusing.

https://github.com/bakkeby/dwm-flexipatch/blob/acbf2de1c23085e0a8736498e5c7600f77f7a5f0/config.def.h#L455-L465

The https://dwm.suckless.org/patches/statuscmd/ patch adds click support for the status, it doesn't have anything directly to do with how the status is drawn.

In terms of drawing the status you have three options; the normal status as it comes with dwm, the powerline variant, and the status2d variant - each of which can be combined with the statuscmd patch to add click support.

With window titles you have five options:

https://github.com/bakkeby/dwm-flexipatch/blob/acbf2de1c23085e0a8736498e5c7600f77f7a5f0/config.def.h#L466-L476

You are right in that there is a warning about that the `click_status` is defined, but not used when you enable the statuscmd patch. Similarly there is a warning that the `*_wintitle` functions are not used when you enable awesomebar.

I could go out of my way to ensure that e.g. `click_status` is not defined when you enable the statuscmd patch or that the wintitle code is not sourced when any of the other title handlers are used, but that would be besides the point as the bar is entirely modular and you can pick and mix as you want. For example you could have awesomebar on your main monitor and the standard one-client wintitle on your second monitor if you wanted to.

**Comment by kronikpillow** [comment]
Hm... That's interesting, i think im finally getting the point in bar modules :-) ty for your patience and time, i can easily comment out the unused functions as i do in vanitygaps,

**Comment by kronikpillow** [comment]
did you do something to the scratchpads patch? I notice it's using keybindings from the SCRATCHPAD_ALT_PATCH and not the original ones from the original SCRATCHPADS, it doesn't even have 1 keybinding as a example of how to toggle multiple scratchpads ... (not that i don't know how to, but it used to ... and the bellow functions and code definetly wasn't part of it, how do these functions work in corespondance to static Sp scratchpads definitions? was this function taken from the alt patch and modified to represent similar behavior to i3? eg I can add any window to a scratchpad with setscratch, and remove it from a scratchpad with removescratch? and which scratchpad will togglescratch toggle? 

	{ MODKEY,                       XK_grave,      togglescratch,          {.ui = 0 } },
	{ MODKEY|ControlMask,           XK_grave,      setscratch,             {.ui = 0 } },
	{ MODKEY|ShiftMask,             XK_grave,      removescratch,          {.ui = 0 } },

**Comment by bakkeby** [comment]
Yes the scratchpads patch got a major overhaul to make it work and feel less amateurish. Multi-monitor support being one of them.

Let's say that you have a terminal bound up for MOD+t. If you don't run that (or close the terminal) and you focus on, say, gedit and hit MOD+Ctrl+t then gedit can now be used as the scratchpad and be toggled with MOD+t.

Before there were three example scratchpads, taking up one keybinding each. Adding this for all three would take up nine keybindings. Available keys are already scarce in dwm-flexipatch, hence I had to reduce the number of examples plus having all scratchpad patches use the same keybinding made sense as trying out two at once is less common.

**Comment by kronikpillow** [comment]
love it :) i really love how you improve some of the base patches from suckless :D like I believe your implementation of awesomebar patch is better then the latest update that was released on suckless website, they actually use 2 separate keybindings for hide and unhide :D while on yours it works with 1 ... althou, I noticed that on the v1 repo, unhide doesnt work at all, on that version it just hides the window, althou the old one is convenient as well depending on usecase, for example, i have a terminal scratchpad bound to mod+s, and a calculator bound to mod+' ... is this still applicable on this version as well?

**Comment by bakkeby** [comment]
Yes you can have as many scratchpads as you want. (Well, I guess there is a limit of 32 - number of tags.)

I have four, bound to w, e, r, and t.
