### ISSUE TITLE
nametag prepend not working with new tagicons 

### ISSUE THREAD

**Issue by rop98** [bakkeby/dwm-flexipatch#78]
Hi, I've tried to patch nametag prepend and it isn't working because of how tags are handled in this release. Would it be possible to add it to the patches in flexipatch?  Awesome work by the way!

**Comment by bakkeby** [comment]
Does that patch even work on a plain 6.2 dwm? 

I have tried them in the past, but they always result in dwm crashing in my experience.

**Comment by bakkeby** [comment]
Nearly two years later, but I added a bespoke version of the nametag patch that is compatible with tagicons.
