### ISSUE TITLE
systraypinning query

### ISSUE THREAD

**Issue by anonymous352** [bakkeby/dwm-flexipatch#80]
I don't seem to find any reference to systraypinning in dwm-flexipatch?

static const unsigned int systraypinning = 0;    "/* 0: sloppy systray follows selected monitor, >0: pin systray to monitor X */"

I see systraypinning in the suckless systray patches , dwm-systray-6.2.diff for example contains it.

Any insights why it's not in flexipatch would be much appreciated.

btw, great work on flexipatch and keeping it up-to-date

**Comment by bakkeby** [comment]
Yes systraypinning was superseded by [barmodules](https://github.com/bakkeby/patches/wiki/barmodules).
https://github.com/bakkeby/dwm-flexipatch/blob/76292ba325278a38bf8a486b118468a7c6e151c2/config.def.h#L422-L435
https://github.com/bakkeby/dwm-flexipatch/blob/76292ba325278a38bf8a486b118468a7c6e151c2/config.def.h#L448-L450

                ^ the 0 there means that the systray is pinned on the first (primary) monitor

You can set this to 1 to have it pinned on the second monitor, or you can set this to 'A' to have it follow the focused monitor (I think that's the default behaviour for the original patch). You can also re-arrange the rules such that the systray appears on the left hand side of the bar if you should want that.

**Comment by anonymous352** [comment]
That setting of the 'A' for the systray barmodule barrule works for me; thank you so much for the explanation and education on barmodules.
________________________________
