### ISSUE TITLE
[FEATURE] flextile use stack layout when nmaster is 0

### ISSUE THREAD

**Issue by Schueni1** [bakkeby/dwm-flexipatch#81]
Do you think it would be 'easily' possible to change the behavior of flextile,
so that it uses the stack layout instead of the master layout when nmaster is 0?

That is also the default behavior for all the other non flextile layouts.

**Comment by bakkeby** [comment]
https://github.com/bakkeby/dwm-flexipatch/blob/76292ba325278a38bf8a486b118468a7c6e151c2/patch/layout_flextile-deluxe.c#L90-L94

I think you just need to change the above `MASTER` to `STACK` to get the behaviour you want. It can be slightly misleading if you are using a dual stack or centered layout though.

**Comment by Schueni1** [comment]
Hmmm. That does not work for the monocle layout. As the monocle layout does not have a stack.

**Comment by bakkeby** [comment]
Yes I guess you would want to set sensible stack arrangements in the layouts config.

**Comment by Schueni1** [comment]
Nice this works!
But it produces another problem. Now if n is greater or equal nmaster the stack layout is being used.

**Comment by bakkeby** [comment]
> Now if nmaster is greater or equal n the stack layout is being used.

In what context? The monocle layout?

**Comment by Schueni1** [comment]
No. Because the monocle layout does not have a stack. But the horizontal stack layout for example

**Comment by bakkeby** [comment]
Oh right, I see. This feels more natural.
```c
(&flextiles[m->ltaxis[m->nmaster >= n ? MASTER : STACK]])->arrange(m, x, y, h, w, ih, iv, n, n, 0);
```

**Comment by Schueni1** [comment]
Nice 🥳 This works great! Thanks a lot again!
