### ISSUE TITLE
New layout for dwm

### ISSUE THREAD

**Issue by plasmoduck** [bakkeby/dwm-flexipatch#83]
Hey I'm wondering if it's possible to create a new style of layout like this one from herbsluftwm where it splits the windows to get that pattern
![image](https://user-images.githubusercontent.com/38978656/100365444-9bd86100-3053-11eb-95d9-5aecbc8e9f86.png)

**Comment by bakkeby** [comment]
herbsluftwm is a manual tiling window manager though, not a dynamic one. This means that every time you open a new window you have to decide whether the current are is going to be split horizontally or vertically to give room for the next client.

You are welcome to try and make a layout like this, provided that you can work out what that pattern actually is (what does it look like when there are two clients, three, four, six, etc.).

I guess it might sort of remind of the [tatami](https://dwm.suckless.org/patches/tatami/) layout (with a bit of imagination).

**Comment by plasmoduck** [comment]
Yeah I knew about the manual tiling of hwm I thought there might be some way to draw windows half the size in dwm to get this pattern. The tatami layout looks similar. I didn't even know about this layout must be new. I should check sickles.org more often. Thanks
