### ISSUE TITLE
Systray greyed out on 2nd screen

### ISSUE THREAD

**Issue by anonymous352** [bakkeby/dwm-flexipatch#84]
I have a 2 monitor set up and noticed (using alpha and systray patches) that focusing to my 2nd monitor, systray icons are all greyed out and don't react to a mouse click; if I change via xrandr (for example) to duplicate/mirror the 2 monitors the systray and icons on both monitors are fine and bright and clickable.  I have 'A' set in the systray barrule.  I have built a stock dwm with alpha and systray patches and that works fine via systraypinning=0.  Hopefully I have managed to include 2 screenshots here to help illustrate the problem.
1st monitor bar and systray:
![mon0bright2020-11-28_09-19](https://user-images.githubusercontent.com/6057088/100498692-ee04a980-315b-11eb-8072-e0d3dd774287.png)
2nd monitor bar and greyed out systray:
![mon2greyed2020-11-28_09-17](https://user-images.githubusercontent.com/6057088/100498717-20aea200-315c-11eb-9b33-e7c514186b8a.png)

Hopefully a puzzle you can spread some light on, thank you.

**Comment by bakkeby** [comment]
It looks like the systray is behind the bar window on the second monitor, easy to confirm by e.g. killing the compositor and see that the systray icons disappear completely.

I guess this could be a hotplugging issue, where the second monitor (and thus the bar) is created after the systray has been created.

I should have a fix for this, I'll upload that shortly.

**Comment by bakkeby** [comment]
Hi @anonymous352,

can you try the above and see if that sorts things out for you?

\
Thanks,

-Stein

**Comment by anonymous352** [comment]
Not sure i can see "the above"  [??]
________________________________

**Comment by anonymous352** [comment]
I killed the compositor (picom) and yes, the systray on 2nd monitor disappered as you suggested.
________________________________

**Comment by anonymous352** [comment]
I see your fix now; I'll test it out and report back, thank you.
________________________________

**Comment by anonymous352** [comment]
yes, that change worked to solve the problem; thank you so much for such a quick fix and response; keep up the great work [:)?]
________________________________
