### ISSUE TITLE
newbie question about dwmblocks ....

### ISSUE THREAD

**Issue by thierrybo** [bakkeby/dwm-flexipatch#85]
Hi,
it seems you included dwmblocks patch in you r build, as I see it in patches.def.h. However where am I supposed to edit "block[]"?

**Comment by kronikpillow** [comment]
I don't think the patch actually installs dwmblocks for you, it instead makes it compatible with the statuscmd patch... it even says so in the description

/* This patch depends on statuscmd patch and adds integration with a (patched) dwmblocks
 * instance to give a clickable status bar.
 * Patch: https://gist.github.com/danbyl/54f7c1d57fc6507242a95b71c3d8fdea
 * dwmblocks: https://github.com/torrinfail/dwmblocks

so you install torrinfail/dwmblocks
and then patch it with that above danbyl gist, and then enable the statuscmd and dwmblocks patches here to make them fully compatible with each other, and then you can have a dwmblocks like lukesmithxyz/dwmblocks for example, that has clickable scripts and completly emulates the behavior of i3blocks

**Comment by thierrybo** [comment]
MEHHH, I realize that!
