### ISSUE TITLE
draw underline under statusbar elements with status2d patch

### ISSUE THREAD

**Issue by plasmoduck** [bakkeby/dwm-flexipatch#87]
Hi again, is it possible to draw an underline under my statusbar elements using the status2d patch like the tag indicator underlines to match? If so then how? I know you can draw shapes with it.
![combined](https://user-images.githubusercontent.com/38978656/103403611-ded2aa80-4ba4-11eb-8594-c95588408b6b.png)

**Comment by bakkeby** [comment]
I haven't tested this, but before returning from the `draw_status2d` function ref.
https://github.com/plasmoduck/modwm2/blob/main/patch/bar_status2d.c#L50-L58

try adding a line like this:
```c
drawindicator(bar->mon, NULL, 1, a->x, a->y, a->w, a->h, 0, 1, 0, tiledindicatortype);
```

**Comment by plasmoduck** [comment]
I tried this but it didnt work.

draw_status2d(Bar *bar, BarArg *a)
{
       #if BAR_EXTRASTATUS_PATCH || BAR_STATUSCMD_PATCH
       drawindicator(bar->mon, NULL, 1, a->x, a->y, a->w, a->h, 0, 1, 0, tiledindicatortype);
       return drawstatusbar(a, rawstext);
       #else
       drawindicator(bar->mon, NULL, 1, a->x, a->y, a->w, a->h, 0, 1, 0, tiledindicatortype);
       return drawstatusbar(a, stext);
       #endif // #if BAR_EXTRASTATUS_PATCH | BAR_STATUSCMD_PATCH
}

**Comment by bakkeby** [comment]
In what way did it not work?

I believe you would have to draw the line after the status has drawn, something like this:

```c
draw_status2d(Bar *bar, BarArg *a)
{
	int ret;
	#if BAR_EXTRASTATUS_PATCH || BAR_STATUSCMD_PATCH
	ret = drawstatusbar(a, rawstext);
	#else
	ret = drawstatusbar(a, stext);
	#endif // #if BAR_EXTRASTATUS_PATCH | BAR_STATUSCMD_PATCH
	drawindicator(bar->mon, NULL, 1, a->x, a->y, a->w, a->h, 0, 1, 0, tiledindicatortype);
	return ret;
}
```

**Comment by plasmoduck** [comment]
I tried that too and no underline on my statusbar

**Comment by bakkeby** [comment]
I don't know, I tried the above and I got a line.

![image](https://user-images.githubusercontent.com/1438008/103415113-0c0d6180-4b81-11eb-8e42-92f577860d0d.png)

**Comment by plasmoduck** [comment]
Okay it worked, sorry my fault. Is it possible to get broken lines _   _   _ etc under the statusbar? Or only a solid line like that?

**Comment by bakkeby** [comment]
It's only a solid line. As far as dwm is concerned the status is just a single string.

I am not sure how you'd go about making a line for each "block" as it is not straightforward to differentiate between when one block starts and another one begins.

**Comment by plasmoduck** [comment]
I thought it might be tricky, fair enough. Thanks mate

**Comment by plasmoduck** [comment]
Btw, someone reported a memory leak bug with my fork, not sure if you patched yours but here is the reference https://github.com/plasmoduck/modwm/issues/2

**Comment by raxchaPanceps** [comment]
what's the name of this font?

**Comment by plasmoduck** [comment]
Jetbrains Mono
