### ISSUE TITLE
new color for each tag

### ISSUE THREAD

**Issue by plasmoduck** [bakkeby/dwm-flexipatch#88]
Hi man, how can I create a new color for each tag, so tag1 is red tag2 is yellow tag2 is green etc? I could never figure it out before.
Cheers

**Comment by bakkeby** [comment]
First you'll want to define a color scheme for each tag. Then you'll want to set the color scheme associated with the given tag before drawing it.

Have a look here for how the colors are chosen for selected, urgent and unselected tags:
https://github.com/plasmoduck/modwm2/blob/0797fff84f9ae64ea80899d16acbb468c9ff37cc/patch/bar_tags.c#L51-L57

The powerline variant for example simply uses the first n schemes defined:
https://github.com/plasmoduck/modwm2/blob/0797fff84f9ae64ea80899d16acbb468c9ff37cc/patch/bar_powerline_tags.c#L55
