### ISSUE TITLE
awesomebar, fancybar, systray patches are incompatible barpadding patch

### ISSUE THREAD

**Issue by kronikpillow** [bakkeby/dwm-flexipatch#9]
awesomebar, fancybar, systray patches are incompatible with barpadding patch

awesomebar + barpadding or fancybar + barpadding: the title bars overlap the right side status bar for some reason
systray+barpadding: systray gets stuck floating in the top right corner instead of next to the statusbar

[awesomebar/fancybar + barpadding](https://0x0.st/iitx.png)
[just barpadding (what my statusbar should show)](https://0x0.st/iit3.png)

**Comment by bakkeby** [comment]
Hi @kronikpillow,

I added two patches to address these issues, could you check if that works for you?

Thanks,

-Stein

**Comment by kronikpillow** [comment]
on it

**Comment by kronikpillow** [comment]
with awesomebar systray working, and titles not overlapping statusbar :) with fancybar the icon wouldn't draw, but the systray was there ^^

**Comment by kronikpillow** [comment]
no, actually, icons in systray wont draw if fontsize is bigger then 10 ... tried 12 13 14 ... it just leaves a empty black systray :)

**Comment by bakkeby** [comment]
I can't replicate that. It might potentially depend on the font you use, or possibly it has something to do with the specific application that adds the tray icon. I have often seen this when recompiling, exiting, and starting dwm a lot - maybe also with systray applications that start up alongside dwm.

In any case I noticed some flickering in the systray area when barpadding was enabled, so committed another fix for that.
