### ISSUE TITLE
Appreciation

### ISSUE THREAD

**Issue by kam3k** [bakkeby/dwm-flexipatch#93]
Hi @bakkeby, I just want to let you know how much I appreciate all the work you've put into this project. It's made experimenting with different patches until I have my ideal setup super easy and really fun. I also use your dmenu, slock, and st flexipatch forks as well.

Please let me know if I can buy you a coffee or something!

**Comment by bakkeby** [comment]
Hey, no worries. I'm just glad it has saved you some time. The idea behind this project was always to be able to "try before you buy" when it comes to dwm patches, as in having a way to test out patches before committing time to integrating them into your own build.
