### ISSUE TITLE
stacker patch cycling and awesomebar hidden functionality

### ISSUE THREAD

**Issue by Batresh** [bakkeby/dwm-flexipatch#94]
i've noticed that when i hide windows using awesomebar, i can still cycle through them with stacker keys, which sometimes  screws me and i kill a hidden window by mistake. 
compiling without the stacker patch and using focusstack instead fixes the issue. but i do like having stacker.
Is there a way to make stacker avoid cycling through hidden windows.
Or is there a way to stop hidden windows from ever getting focused unless explicitly clicked on (this would be perfect for me)

thanks for taking the time to read my nitpick issue

**Comment by bakkeby** [comment]
Ah cool, so you have found a patch incompatibility issue. I'll have a look.

**Comment by bakkeby** [comment]
I just pushed the proposed changes to address this issue, would it be possible for you to test and report back?

**Comment by Batresh** [comment]
As far as i've tested, yes, it works perfectly now! Awesome. Thx!
