### ISSUE TITLE
combo patch: can't combo tag 1 and tag 2 together

### ISSUE THREAD

**Issue by Batresh** [bakkeby/dwm-flexipatch#98]
hi its me again
combo patch tag 1-3, 1-4, 2-4, 3-5-6, 4-5, 5-6 etc works. but can't combo tag 1 and tag 2 or 2 and 1. same goes for tag 3 and 4.

**Comment by bakkeby** [comment]
Just to clarify - we are talking about `combotag` here - i.e. assigning tags to a client - as opposed to `comboview` - i.e. selecting which tags to show.

The difference being that the former uses `MOD+Shift+<number>` while the latter uses `MOD+<number>`. 

My question is are you running this on a laptop? On mine I was never able to send clients to tag three because the `Super+Shift+3` combination would be hijacked by some special laptop function which was pretty annoying.

You may want to double check what comes through in `xev` (Event Tester) when you hit these combinations.

**Comment by Batresh** [comment]
talking about comboview. 
I cant' view windows from tag 1 and tag 2 if i press mod4(superkey) + 1 + 2. but it works with mod4 + 2 + 3.
i tested it in TTY and i'm able to press mod4 + 1 +2 at the same time and get number 1 and 2 printed. i know superkey in TTY is doesn't do anything but i think it shows the laptop is capable of pressing mod4 and 1 and 2 the same time without problems

**Comment by bakkeby** [comment]
The good news is:
* I worked out what causes this issue, the laptop's function keys conflict with the keybinding

The bad news is:
* I don't think there is anything you can do about it

On my laptop for example the function key + right arrow increases volume.

If you look at the technical details about how the function keys on a laptop works (outlined here: https://askubuntu.com/questions/270416/how-do-fn-keys-work) then what happens is that internally the special key combination is found in a map and it is replaced with the scancode to increase volume.

In my case I can use `Super+3` to move to that tag just fine, but when I do the combination of `Super+Shift+3` to move a window to that tag it doesn't work. The reason for this is that the key combination happens to also be replaced by the scancode to increase volume. Using an external keyboard has the same result in my case.

By adding logging I was also able to confirm that the key did not come through as a keypress for this combination, but I see the volume increasing. I have never had any issues like this on a desktop computer.

I'm inclined to suspect that the same happens in your case when you do these special combinations, just depends on what actual functionality is triggered.

I know you can include XF86 keysyms and override the behaviour, but I'm not sure if the combos are worth giving up things like changing volume or brightness, toggling wifi, etc.
https://bbs.archlinux.org/viewtopic.php?id=77832

**Comment by Batresh** [comment]
yea.. I changed mod4 to mod1(alt key) and now comboview works like it should.
I'll stick with mod4 and take the loss. Thx alot for help
