### ISSUE TITLE
Maybe a Feature Request: Extrastatus ( Multi-Extrastatus )

### ISSUE THREAD

**Issue by Kemmojo** [bakkeby/dwm-flexipatch#99]
Hey again,

just wanted to ask if there is a "defined" way to have multible extrastatus modules on different sides of the extrastatusbar?

I kinda achieved this by duplcating everything dedicated to extrastatus, statuscmd and status2d and created a second seperator.
To my surprise, this was working flawlessly, except the rawtext handling, that needed some nesting.
But thats of course a totally messy way.

Here a screenshot:
![dwm_multi_extrastatus](https://user-images.githubusercontent.com/11157873/110170443-81ecae00-7dfa-11eb-9570-dad80a879cd2.png)

( By the way, i love the statusbar module appoach, that´s what inspired my to try. )

Have a good one.

**Comment by bakkeby** [comment]
Yes that's the way you'd have to do it, duplicate and deal with the nesting. It should be fine in general, but one of the complications is that you can't guarantee that there will be enough space for each of the three statuses - so you end up having a large array just to make sure there is enough.

What if you wanted more though? How about six of them? Rather than going through the root window name and have dwm detect the name change to update the statuses what you can do is have dedicated functions to do this via the IPC patch. That way you can also update each status individually.

This is actually fairly straightforward to do, but it will depend on what you use to update the bar and if you expect button clicks as well.

**Comment by Kemmojo** [comment]
That actually works for me. 

Having the IPC Patch to handle certain things sound like a thing i could use in one or two scenarios.

Thanks a lot, that answered the question.

**Comment by bakkeby** [comment]
I actually ended up implementing support for multiple statuses in my personal [dusk](https://github.com/bakkeby/dusk) build. I have yet to write up documentation for that though.

The gist of it is that each status has a separate ID number, 0, 1, 2, etc. and you can have as many statuses as you want and they are all updated separately via the IPC patch.

Some of the benefits I observed were:
   - you are pretty much free to place the individual statuses anywhere on any bar, they do not need to be together in one block of statuses
   - each status updates separately, the update of one status does not affect the others
   - only the bar where the individual status being updated resides is redrawn, the other ones are left untouched
   - the code that handles X root name updates could be removed
   - no separator needed to have status + extrastatus
   - no need for external programs like dwmblocks to handle the updating of status(es) - you could use a cron job if you prefer
   - when it comes to button clicks there is no need to calculate how far along the status the click was to work out which of the statuses you actually clicked on
   - you can have ad-hoc statuses that you just set and clear when you need them
   - button clicks are handled by a single external script (which can delegate to others depending on the status that was clicked on and what kind of click it was using environment variables)
   - the status actually feels a bit more snappy when it comes to using scroll wheel, clicks, etc. presumably the overhead of sending and handling kill signals in relation to dwmblocks added a tiny bit of delay
 
Some obvious cons in terms of bloat:
   - you need barmodules
   - you need the IPC patch
 
I'm not sure if I'd actually _recommend_ others to go down this route, but for me I don't think I'm ever going back.

In any case I think it is a bit too involved / invasive to integrate into dwm-flexipatch.

**Comment by Kemmojo** [comment]
In terms of people showing interest for and extrabar & create / align multible statuses, 
i found myself getting asked by some work colleagues about my setup ( Still WIP and similar to the positioning in the image above ) and how difficult it would be to implement something similar themselves.
For some i got the time to show them a little bit about the patching process and the module system, and was pleasantly surprised by how positiv some of them responeded to it. ( Mainly because of patch.h documentation )

But i additionally checked some [r/unixporn](https://www.reddit.com/r/unixporn/) posts and the number of people using setups like this on any WM ( mostly using polybar ) seam fairl low.

So, my guesses would be that people either just don´t care that much, are totally happy with simply having some statuses at the top right, or don´t know multible statuses and/or plus an extrabar is a thing ( In dwm ). ( By now )
Or they know, but can´t find the time, or find it to difficult to setup.

Would be interesting to have some what more direct feedback about the idea in general and if people willing to take the time to setup, customize dwm with this approach.

I can´t right know, but i think i will check out your dusk build somewhat later that year. 
But for now, i´m totally happy with what is implemented in dwm-flexipatch.
